### ISSUE TITLE
Documentation no longer available?

### ISSUE THREAD

**Issue by jc-dgit** [mozilla/rhino#1002]
Looking for Rhino documentation, to point some of our developers towards because one of our old legacy projects uses it.

However, the documentation link in the README.md seems to be broken:

```
Information for script builders and embedders:

https://developer.mozilla.org/en-US/docs/Rhino_documentation
```

That link is 404-ing now.  Any idea if there's a new working link I can point people at?  Nothing obvious is showing up when searching the Mozilla website.

**Comment by p-bakker** [comment]
See #954 and specifically comments https://github.com/mozilla/rhino/issues/954#issuecomment-882685747 and https://github.com/mozilla/rhino/issues/954#issuecomment-885656764

**Comment by jc-dgit** [comment]
Cool, thanks @p-bakker.  :smile:
