### ISSUE TITLE
return of javascript Object 

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1014]
![image](https://user-images.githubusercontent.com/15280143/131435477-65e4d80b-185a-4432-b2c5-c1e5316b1ab1.png)
![image](https://user-images.githubusercontent.com/15280143/131435572-bbb409ec-ff1b-4f90-bf39-0c97cde9800a.png)

**Comment by MikeGrateful** [comment]
![image](https://user-images.githubusercontent.com/15280143/131435733-891d77fb-2a76-4f94-ad20-efe60f4e9fce.png)
![image](https://user-images.githubusercontent.com/15280143/131435747-d784278e-98d8-49bf-9cd4-c1e247ef5ea1.png)
print jsobject

**Comment by p-bakker** [comment]
Think this needs further explanation, because the screenshots alone dont quite make clear what you're trying to communicate.

Just based on the above, I have no idea what potential issue you're trying to point out

**Comment by MikeGrateful** [comment]
> Think this needs further explanation, because the screenshots alone dont quite make clear what you're trying to communicate.
> 
> Just based on the above, I have no idea what potential issue you're trying to point out

tq！I mean why is the return value not an object?  Only one size?

**Comment by p-bakker** [comment]
Dunno... If you want people to help out, please prove runnable sample code that reproduces the issue, instead of screenshots
