### ISSUE TITLE
Scripts declare cycle issues

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1017]
Each time a method in the script is called, the entire script needs evaluateString?  If this script introduces other scripts, then execute them all once?  

    public Object call(String src, String call, Object[] args, List<String> inherits, boolean superCall) {

        String jsFunction = call;
    

        Context context = ContextFactory.getGlobal().enterContext();
        ;
        Scriptable scope = context.initStandardObjects(null);
        ;
        context.setOptimizationLevel(-1);
        context.setLanguageVersion(Context.VERSION_1_8);

        try {
            ScriptableObject.defineClass(scope, ExtendUtil.class);
        } catch (IllegalAccessException e1) {
            e1.printStackTrace();
        } catch (InstantiationException e1) {
            e1.printStackTrace();
        } catch (InvocationTargetException e1) {
            e1.printStackTrace();
        }
        ExtendUtil util = (ExtendUtil) context.newObject(scope, "util");
        scope.put("util", scope, util);
        Object ret = null;
     
        for (String s :  inherits){
            context.evaluateString(scope,this.jsList.get(s), s, 1, null);
        }
        if(!superCall){
         
            context.evaluateString(scope, this.jsList.get(src), src, 1, null);
        }
        
     
        Object fObj = scope.get(jsFunction, scope);
        return ((Function) fObj).call(context, scope, scope, args);
    }

**Comment by p-bakker** [comment]
If you hang onto fObj, context and scope, you can call function as many times as you want

**Comment by MikeGrateful** [comment]
> If you hang onto fObj, context and scope, you can call function as many times as you want

TQ
