### ISSUE TITLE
Experts, can you show me how to use coroutines, I want to execute JS in parallel  

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1029]
Experts, can you show me how to use coroutines, I want to execute JS in parallel

**Comment by MikeGrateful** [comment]
`  public void testFunctionWithContinuations() {
      Context cx = Context.enter();
      try {
          cx.setOptimizationLevel(-1); // must use interpreter mode
          cx.evaluateString(globalScope,
                  "function f(a) { return myObject.f(a); }",
                  "function test source", 1, null);
          Function f = (Function) globalScope.get("f", globalScope);
          Object[] args = { 7 };
          cx.callFunctionWithContinuations(f, globalScope, args);
          fail("Should throw ContinuationPending");
      } catch (ContinuationPending pending) {
          Object applicationState = pending.getApplicationState();
          assertEquals(7, ((Number)applicationState).intValue());
          int saved = (Integer) applicationState;
          Object result = cx.resumeContinuation(pending.getContinuation(), globalScope, saved + 1);
          assertEquals(8, ((Number)result).intValue());
      } finally {
          Context.exit();
      }
  }


`
Is that so?

**Comment by p-bakker** [comment]
Closing this, as this is neither a bug report or a feature request. Use the Google Group for such questions

**Comment by p-bakker** [comment]
Tnx for the heads-up, wasn't aware that option existed
