### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by mrQvera** [mozilla/rhino#1035]
It looks like the documentation was removed:

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Documentation

Is it hosted somewhere else?

**Comment by tonygermano** [comment]
duplicate of #1002 
(and others)

**Comment by tonygermano** [comment]
Everything that was removed from MDN is archived here https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/rhino, but it is in html form.

Until #954 is complete, it's probably easiest to view in the archive.org wayback machine
https://web.archive.org/web/20210304081342/https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Documentation

**Comment by mrQvera** [comment]
Thank you for the information.  That'll work.
