### ISSUE TITLE
this is not a coroutine like operation, <saved> feels like a position at the top of the stack 

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1038]
public void testFunctionWithContinuations() {
      Context cx = Context.enter();
      try {
          cx.setOptimizationLevel(-1); // must use interpreter mode
          cx.evaluateString(globalScope,
                  "function f(a) { return myObject.f(a); }",
                  "function test source", 1, null);
          Function f = (Function) globalScope.get("f", globalScope);
          Object[] args = { 7 };
          cx.callFunctionWithContinuations(f, globalScope, args);
          fail("Should throw ContinuationPending");
      } catch (ContinuationPending pending) {
          Object applicationState = pending.getApplicationState();
          assertEquals(7, ((Number)applicationState).intValue());
          int saved = (Integer) applicationState;
          Object result = cx.resumeContinuation(pending.getContinuation(), globalScope, saved + 1);
          assertEquals(8, ((Number)result).intValue());
      } finally {
          Context.exit();
      }
  }

Excuse me, this is not a coroutine like operation, <saved> feels like a position at the top of the stack to me, I wanted to ask a question in the group, but no one answered the question in the group

**Comment by MikeGrateful** [comment]
??

**Comment by tonygermano** [comment]
This is likely better suited for a [Discussion](https://github.com/mozilla/rhino/discussions) than an Issue. Please format your code and clarify your question. It is not clear what you are asking.

**Comment by p-bakker** [comment]
Closing this as this is not an issue, see previous comment
