### ISSUE TITLE
Internal cleanup: Reassess ObjToIntMap and friends

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#1064]
Rhino has an ObjToIntMap, which is the moral equivalent of HashMap<Integer, Object>, as well as a few similar classes. These date back to olden times when "everyone knew" that Java was too slow if you tried to do things in a generic way.

I have actually benchmarked these classes and they are indeed a bit faster than the generic HashMap. However, I still think that they're risky. As one example, HashMap has built-in protection from hash flooding attacks, while our internal classes don't. It's likely not a problem because we mainly use these in places like the compiler, but if we implement classes used to execute actual, user-generated, code, it's at least theoretically possible that these classes should become a problem.

I think it'd be just fine to clean up the codebase by replacing these classes with their generic equivalents.

**Comment by p-bakker** [comment]
Resolved by #1562 & #1564
