### ISSUE TITLE
Support ES2022 `Error.cause`

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1091]
Proposal: https://github.com/tc39/proposal-error-cause
MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error#rethrowing_an_error_with_a_cause

**Comment by camnwalter** [comment]
I was looking at trying to solve this but I'm not sure on some things. What should we set the `fileName` and `lineNumber` properties to if they are using the `Error(message, { cause })` constructor? Also how should something like `new Error("message", { cause: "cause", otherProp: 1234 })` look like in `toSource()`? Should it return it exactly as it looks like in the source or should we ignore any keys in the object that aren't `cause`?

**Comment by p-bakker** [comment]
Great that you're looking into this!

As fileName and lineNumber are non-standard extensions supported by Rhino, my take would be to NOT support those when when the 2nd param of the Error constructor call is a Scriptable having a `cause` property

I think https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error explains it quite well how to deal with the overloaded nature of the Error constructor

As to `.toSource()`: that is a non-standard method anyway, so I do not really care what it returns :-) From my perspective you can leave its implementation as is, but I do not know if anyone else feels differently about it
