### ISSUE TITLE
Can you implement coroutines using such code?

### ISSUE THREAD

**Issue by MikeGrateful** [mozilla/rhino#1093]
pseudocode
```
for 10000000....
   Context.runScrtip("let a=1; a++;")
end for
```
Can you implement coroutines using such code?

**Comment by p-bakker** [comment]
Could you please stop tagging who's not in your issues and stop posting issues that aren't issues?

**Comment by MikeGrateful** [comment]
> Could you please stop tagging who's not in your issues and stop posting issues that aren't issues?
> 
> I've removed that random tags for people now, please stop doing that

sorry

**Comment by p-bakker** [comment]
Closing, as this is neither an issue or feature request, so it doesn't belong here
