### ISSUE TITLE
'warning: empty <p> tag' in `UpdateExpression.java`

### ISSUE THREAD

**Issue by MaxisTekfield** [mozilla/rhino#1100]
```
> Task :javadoc
F:\rhino\src\org\mozilla\javascript\ast\UpdateExpression.java:15: warning: empty <p> tag
 * the start of the operand to the operator (for postfix).<p>
                                                          ^
1 warning
```

**Comment by MaxisTekfield** [comment]
emmm, please someone fix this warning by merging PR #1101 so that no one will get this warning when compling.
If we fix this later in v1.7.15, everybody who uses v1.7.14 will get this warning.

**Comment by p-bakker** [comment]
@gbrail Want to merge this one as well for 1.7.14?

**Comment by gbrail** [comment]
Yes -- the PR seems very safe. Let me take one last look.
