### ISSUE TITLE
TypeError when passing a string to Object.values() on 1.7.14

### ISSUE THREAD

**Issue by SuperMonster003** [mozilla/rhino#1102]
```js
Object.values("abc");
```

Expected result: (As node.js returns in the screenshot below)

![image](https://user-images.githubusercontent.com/30370009/143726089-44a2d8d6-3fc7-44d3-b60f-8f824cf82e6a.png)

**Comment by tuchida** [comment]
Please add `-version 200` or `cx.setLanguageVersion(Context.VERSION_ES6)`.
```sh
$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar -version 200
Rhino 1.7.14-SNAPSHOT 2021 11 28
js> Object.values("abc")
a,b,c
```

**Comment by SuperMonster003** [comment]
@tuchida thx a lot :)
