### ISSUE TITLE
Changes to AST classes break PMD

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#1107]
The PMD tool, which uses Rhino to parse JavaScript, depends on classes in the "ast" package which changed with 1.7.14.

Specifically, this commit, by @tuchida , changed the UnaryExpression class, which PMD depends on.

https://github.com/mozilla/rhino/commit/fb77164ac4889ffa4be26d5d24cb538a8dbd632b

I think that we should update the PMD tool to support Rhino 1.7.14, but I don't know enough about what PMD is trying to do to try and fix it. Perhaps someone else can take a look.

To reproduce, check out https://github.com/pmd/pmd, change the pom.xml in the "pmd-javascript" directory to reference Rhino 1.7.14-RC1, and rebuild.

**Comment by MaxisTekfield** [comment]
I've taken a glance at this problem. I think there maybe no easy way to keep rhino compatible with current PMD.Because @tuchida added `**` and `**=` operator so he have seperated `UnaryExpression` into `UnaryExpression` and `UpdateExpression`. Also some changes have taken place in `UnaryExpression` which PMD are using - like `isPrefix()` and `isPostfix()` which have been removed.
If PMD needs to use latest rhino, some changes have to happen with PMD.

I have tried to make `UpdateExpression` inherts from `UnaryExpression`. After this, PMD can be compiled successfully, but test fails. I've got something like this:
```
ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.019 s <<< FAILURE! - in net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParserTest
[ERROR] net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParserTest.shouldNotFailWithOutOfMemory  Time elapsed: 0.003 s  <<< ERROR!
java.lang.IllegalArgumentException: There is no Node adapter class registered for the Node class: class org.mozilla.javascript.ast.TemplateLiteral
        at net.sourceforge.pmd.lang.ecmascript.ast.EcmascriptParserTest.shouldNotFailWithOutOfMemory(EcmascriptParserTest.java:191)
```
It seems that PMD cannot recognize the newly added `UpdateExpression`.
So there seems to be no simple way to make new rhino compatible with current PMD.

**Comment by tuchida** [comment]
I think it is possible to eliminate the class `UpdateExpression` from AST. However, in the ECMA262 specification, `UnaryExpression` and `UpdateExpression` are clearly defined as different things.
https://262.ecma-international.org/12.0/#sec-exp-operator
> ExponentiationExpression[Yield, Await] :
>   UnaryExpression[?Yield, ?Await]
>   UpdateExpression[?Yield, ?Await] ** ExponentiationExpression[?Yield, ?Await]

**Comment by tonygermano** [comment]
How critical is it that pmd compile against Rhino 1.7.14? What would it be missing by staying at 1.7.13 besides the new operator that caused the breaking change?

Is it likely that we will have a lot more breaking changes to the AST when the parser eventually gets rewritten?

**Comment by gbrail** [comment]
I think it'd be fine and community-minded to work with the PMD team to make
PMD work with 1.7.14 by patching PMD. Unfortunately and for historical
reasons the public API surface of Rhino is huge and we can't promise that
nothing will ever change in areas like the AST.

**Comment by p-bakker** [comment]
> when the parser eventually gets rewritten?

That, or when we start adding missing EcmaScript features that extend the syntax.

As @gbrail said, the updates should happen on the PMD side, not on the Rhino side

Think what Greg was hinting at was if we could supply a patch to PMD

**Comment by p-bakker** [comment]
> Unfortunately and for historical
reasons the public API surface of Rhino is huge

Maybe something to look at for v2.0.0?

**Comment by tuchida** [comment]
If Rhino's AST is a published specification, then an ESTree-compliant implementation may reduce the problem.
https://github.com/estree/estree

**Comment by p-bakker** [comment]
But do we really need a public AST API?

What features does the Rhino AST offer that could not be achieved by for example loading Acorn and parsing some JS code?

Just thinking out loud here 🙂

**Comment by p-bakker** [comment]
And on the other side: how close (or far off) are we from ESTree compliance, since ESTree originates from somewhat the same origin as Rhino, namely SpiderMonkey

Even found references online to using Rhino AST in projects, because it returns an ESTree-compatible AST tree... Not sure how accurate that statement is/was though

**Comment by msridhar** [comment]
From a quick glance at the PMD code, it looks like they are building their own AST based on the Rhino AST:

https://github.com/pmd/pmd/blob/033e817ed6edc31f513ad8b078798a0e136b5dbe/pmd-javascript/src/main/java/net/sourceforge/pmd/lang/ecmascript/ast/ASTUnaryExpression.java

There are a few places relying on their `ASTUnaryExpression` type that may need to be updated if there were also an `ASTUpdateExpression` type.  My feeling is this wouldn't be too hard and we could help the PMD folks do it.  So IMO this shouldn't block the 1.7.14 release and it's not worth trying to keep the Rhino AST backward-compatible in this case.

FWIW, I have a WIP PR to update WALA to Rhino 1.7.14, at https://github.com/wala/WALA/pull/1061.  I also had to deal with the `UpdateExpression` change, and once I understood it, it wasn't too painful.

**Comment by p-bakker** [comment]
I'm proposing to close this issue: looks like that changes made on the Rhino side are the correct ones, as they are in line with the EcmaScript spec and also ESTree has the distinction between Unary and Update expression

Unfortunately it breaks PMD (and other projects), but EcmaScript progresses, so so will EcmaScript-compatible Casts.

While it would be great if the Rhino project had the resources to help out downstream projects, i think we've got our hands full with our own project.

And I'm not seeing any action on this issue anymore

Thoughts @gbrail (as you opened this issue)?

**Comment by p-bakker** [comment]
Closing this now since there's no further activity on this issue
