### ISSUE TITLE
Failing test under Mac OS X

### ISSUE THREAD

**Issue by dbroeglin** [mozilla/rhino#111]
The test suite includes a char-002.js test file which expects File.separatorChar to be equal to 58 (':') whereas on Mac OS X like unix, it is equal to 47. This fails the test suite.

I would have provided a patch but the file is in tests.tar.gz which does not seem to be a part of the rhino sources. How can I proceed to make the tests pass in my environment ? I would be glad to provide a patch back once the issue solved.

**Comment by gbrail** [comment]
I fixed this in master and in 1.7R5.

Part of the fix was to explode "tests.tar.gz" and check the source in to git, which will make it easier to manage going forward.
