### ISSUE TITLE
ImporterTopLevel regression in 1.7.14RC1, with possible fix

### ISSUE THREAD

**Issue by CGJennings** [mozilla/rhino#1111]
When testing against 1.7.14 RC1, some changes to `ImporterTopLevel` broke an app that has integrated Rhino for many years. I tracked the problem down to `realScope`, specifically [this bit](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/ImporterTopLevel.java#L270). It seems that the new code assumes that the top level scope will always be a `ScriptableObject` and not just a `Scriptable`, whereas previously when `topScopeFlag` was set, it simply returned `this`. I got the app working again by checking for this and reverting to the old behaviour if that assumption proves false:

```java
private ScriptableObject realScope(Scriptable scope, Scriptable thisObj, IdFunctionObject f) {
    if (topScopeFlag) {
        // when used as top scope importPackage and importClass are global
        // function that ignore thisObj. We use the the top level scope
        // which might not be the same as 'this' when used shared scopes
        thisObj = ScriptableObject.getTopLevelScope(scope);
        // revert to old (<= 1.7.13) behaviour if top level scope is not a ScriptableObject
        if (!(thisObj instanceof ScriptableObject)) {
            thisObj = this;
        }
    }
    return ensureType(thisObj, ScriptableObject.class, f);
}
```

I'd be happy to submit a PR for this, but I'm not familiar enough with Rhino to know if this the best solution.

Edit: I should mention that in case anyone needs a similar workaround, you also need to update `getPackageProperty` to use `scope = this`, or classes from imported packages won't be found.

**Comment by gbrail** [comment]
Thanks -- I'm happy to include this fix but I'd really like to have a test case. I tried to write one but I'm stabbing in the dark. Can you send us a little test case, or explain how you're using your custom non-ScriptableObject scope?

**Comment by CGJennings** [comment]
I'll see if I can pare something useful down from our code base.

I can tell you that the original version of what we did was based on, as I recall, sample Sun code from the Java 6 days to get a JSR 223 interface to the full version of Rhino rather than the stripped-down version included with the JRE. It creates an `ImporterTopLevel` instance in the constructor, then stores it for later. When it is time to run a script it wraps the JSR bindings object with an adapter that creates a `Scriptable`, then sets the prototype of the adapter object to the stored `ImporterTopLevel`. The adapter object is then passed as the scope to a `Context.evaluate*` method.

If this is an isolated issue only affecting me, you don't need to hold off the release on my account. We do some minor customization of the parser anyway; it's no big deal for me to add another patch to our process.

**Comment by gbrail** [comment]
Thanks for the info. I think that we should do the 1.7.14 release without this. There's now a supported ScriptEngine interface in Rhino -- can you try that out, and then we can always address anything else that we need to fix as we go forward. Thanks!

**Comment by p-bakker** [comment]
@CGJennings Is there still a reason to keep this case open? In order to process with this case we'll need to have a testcase or at least some code that reproduces the issue

**Comment by CGJennings** [comment]
I'm fine with closing it. I did try to pull out some code to reproduce the issues against the code I was working with, but it proved more complicated than I had time available.
