### ISSUE TITLE
Possible issue with Array.from

### ISSUE THREAD

**Issue by tonygermano** [mozilla/rhino#1112]
Rhino:
```js
js> JSON.stringify(Array.from({length:3}).map(_ => 1))
[null,null,null]
```

Firefox and Chrome consoles return `[1,1,1]`

I haven't looked into the spec yet, but it appears that Array.from is returning a sparse array when it shouldn't be.

**Comment by tuchida** [comment]
This will fix it.
```diff
index bd35bcbf..28143dd0 100644
--- a/src/org/mozilla/javascript/NativeArray.java
+++ b/src/org/mozilla/javascript/NativeArray.java
@@ -812,13 +812,11 @@ public class NativeArray extends IdScriptableObject implements List {
         final long length = getLengthProperty(cx, items);
         final Scriptable result = callConstructorOrCreateArray(cx, scope, thisObj, length, true);
         for (long k = 0; k < length; k++) {
-            Object temp = getRawElem(items, k);
-            if (temp != Scriptable.NOT_FOUND) {
-                if (mapping) {
-                    temp = mapFn.call(cx, scope, thisArg, new Object[] {temp, Long.valueOf(k)});
-                }
-                defineElem(cx, result, k, temp);
+            Object temp = getElem(cx, items, k);
+            if (mapping) {
+                temp = mapFn.call(cx, scope, thisArg, new Object[] {temp, Long.valueOf(k)});
             }
+            defineElem(cx, result, k, temp);
         }
 
         setLengthProperty(cx, result, length);
```
I couldn't find the test in test262, so I reported it.

**Comment by tuchida** [comment]
ref. https://github.com/tc39/test262/pull/3337
The test case has been added to the latest test262. When the test262 used by Rhino is updated, I will create a Pull Request.

**Comment by p-bakker** [comment]
> When the test262 used by Rhino is updated, I will create a Pull Request.

Why wait on that before creating a PR? Unfortunately we cannot update to the latest version of the Test262 Suite, because Rhino is missing EcmaScript features that the TestSuite code uses, so if we update to a newer version of the Test262 suite than we're currently are on, the entire Testsuite bombs out

**Comment by tuchida** [comment]
Okay, I understand. I'll create the test myself.
