### ISSUE TITLE
Github classifies Rhino as a C++ project

### ISSUE THREAD

**Issue by tonygermano** [mozilla/rhino#1129]
I found it's because many of the old mozilla js tests have an incorrect emacs mode of C++ specified.

for example: https://github.com/mozilla/rhino/blob/f75125901ee1df681510200f63a6eb033342f488/testsrc/tests/lc3/ArrayMethods/byte-001.js#L1-L4) 

I think if all of them were fixed it would reclassify the project as javascript. Not sure if we'd want to exclude certain test directories from the calculation entirely so that Java is the predominant language.

Github uses [linguist](https://github.com/github/linguist) to calculate language usage in projects.

**Comment by p-bakker** [comment]
Ah, nice. Always wondered where that ~50% C++ classification came from.

Would be nice to fix this

**Comment by p-bakker** [comment]
Could this be as straight forward as in our .gitattributes adding `*.js linguist-language=JavaScript` (according to https://github.com/github/linguist/blob/master/docs/overrides.md#using-gitattributes)?

**Comment by p-bakker** [comment]
Or exclude the entire testsrc folder... Dunno if it makes sense to have testcode source included in the stats
