### ISSUE TITLE
Rhino 1.7.14 breaks typeof for Java Classes

### ISSUE THREAD

**Issue by Schmidor** [mozilla/rhino#1173]
typeof on classes of imported packages is not working anymore.

```
importPackage(Packages.java.io);
importPackage(Packages.java.lang);

System.out.println("File: " + (typeof File));
```

outputs "File: function" till 1.7.13 and "File: undefined" in 1.7.14

**Comment by archethic** [comment]
I tried running the source in the article, but the execution result was very normal.
```
$ java -jar ./rhino-1.7.14.jar -debug -version 200 test.js
File: function
```

Can I know in which environment you ran Rhino a little more?

**Comment by Schmidor** [comment]
Indeed, i've assumed it is always the case.

We run multiple scripts with a shared global scope, which is set as prototype and removed as parent:
```
    Context context = Context.enter();
    Scriptable globalScope = ScriptRuntime.getGlobal( context );
    ScriptableObject scope = ( ScriptableObject )context.newObject( globalScope );
    scope.setPrototype( globalScope );
    scope.setParentScope( null );
    context.evaluateString( scope, "importPackage(Packages.java.io);\r\n"
        + "importPackage(Packages.java.lang);\r\n"
        + "\r\n"
        + "System.out.println(\"File: \" + (typeof File));", "", -1, null );
    Context.exit();
```

**Comment by Schmidor** [comment]
This has something to do with the changes from mozilla/rhino@a9597c9293e08691fc896f4ad7554fe332b3277a

It seems typeof only works there, after the type was invoked directly, as the following test shows:
[testsrc/org/mozilla/javascript/tests/SealedSharedScopeTest.java](https://github.com/mozilla/rhino/commit/a9597c9293e08691fc896f4ad7554fe332b3277a#diff-2559a8bc99633b188ed5b3068f7fbb923fafd8c7174e7338219b46a9a0714893) 
```
    @Test
	public void testGlobalScope() throws FileNotFoundException, IOException {
    	evaluateString(scope1, "importPackage(Packages.java.io);");
    	
    	// Loading object via direct class type evaluate and then checking with typeof works
		Object o = evaluateString(scope1, "File");
		assertEquals(java.io.File.class, o);
		o = evaluateString(scope1, "typeof File");
		assertEquals("function", o);
		
	// Direct checking with typeof fails
    	evaluateString(scope2, "importPackage(Packages.java.io);");
		o = evaluateString(scope2, "typeof File");
		assertEquals("function", o);
	}
```

**Comment by p-bakker** [comment]
@rPraml any thought on this, given you worked on the mentioned change?

**Comment by kopfsport** [comment]
#798 same problem here with BindingsObject?
