### ISSUE TITLE
Return type error

### ISSUE THREAD

**Issue by little-alei** [mozilla/rhino#1177]
When I call a protected Java method, I should get a Java object of uiobjectcollection type, which actually returns a JS array object and cannot be successfully converted with the jstojava method

**Comment by p-bakker** [comment]
Some (pseudo) code demonstrating this + at least the version of Rhino you're seeing this on is required i think for someone to be able to say something about this

**Comment by p-bakker** [comment]
Am closing this for lack of information, like a reproducible example.

If you're still experiencing the reported issue, feel free to reopen with better information
