### ISSUE TITLE
Considering Support Proxy?

### ISSUE THREAD

**Issue by xuchiya** [mozilla/rhino#1179]
like : 
const p = new Proxy(target, handler)

**Comment by p-bakker** [comment]
Duplicate of #268

**Comment by p-bakker** [comment]
> You can do something similar by implementing Scriptable.

Note that when implementing Scriptable.get in JavaScript as suggested, that is the get impl. returns (JavaScript) undefined, the 'proxy' returns null for the gotten property. If you need it to return undefined, the get method should return `org.mozilla.javascript.Undefined.SCRIPTABLE_UNDEFINED` instead
