### ISSUE TITLE
Can you make your signing keys available. 

### ISSUE THREAD

**Issue by rodwiddowson** [mozilla/rhino#1194]
Previous releases of this artifact were signed (on maven central) by this key
```
pub   rsa2048 2017-08-24 [SC]
      EA0B70B5050192C98CFA7E4F3F36885C24DF4B75
uid           [ unknown] Gregory Brail <gregbrail@google.com>
sub   rsa2048 2017-08-24 [E]
```
1.7.14 is signed by this key
```
pub rsa3072/e9af5293c334c7c0b583227d2f45f85cdf082e68 2022-01-04T22:47:38Z
	 Hash=36f2732e5377e3f90d17a54b1ef48b2e

uid Gregory Brail (Rhino Automated Builds) <greg+rhino@brail.org>
sig  sig  2f45f85cdf082e68 2022-01-04T22:47:38Z ____________________ ____________________ [selfsig]

sub rsa3072/c6cef0e9ff26615aceca04ea6f67467bc1adb846 2022-01-04T22:47:38Z            
sig sbind 2f45f85cdf082e68 2022-01-04T22:47:38Z ____________________ ____________________ []
```
It would be extremely useful to people who check signatures on artifacts prior to using them (because of fears of supply chain attacks) if you could publish your PGP_KEYS.txt file either on your website or as a file in this repository.

Failing which, some checkable assertion that this key is valid would be appreciated

Thanks

**Comment by p-bakker** [comment]
@gbrail @carlosame any chance either of you could take a look at this? 

I know we already expose a bunch of singing info files (md5, sha1, sha256, sha512) through maven (see https://repo1.maven.org/maven2/org/mozilla/rhino/1.7.14/), but is this an additional thing we ought to expose?

**Comment by rodwiddowson** [comment]
Any progress here?  I'd like to be able to update to your latest but whilst I cannot trust the artifacts I download I cannot do this

**Comment by rodwiddowson** [comment]
<nudge/>?

**Comment by gbrail** [comment]
PTAL at the file I added -- it lists the fingerprint and shows where to get the signature. Let me know if that is workable. Thanks!

**Comment by rodwiddowson** [comment]
@gbrail Many thanks for that.  It has allowed me to insert that key into our supply-chain-defence infrastructure and thus to move forward to the latest version. (Also to close a [case ](https://shibboleth.atlassian.net/browse/JPAR-201) which has been opened against me for some time)

As far as I'm concerned the work here us done, so feel free to close the case as your processes allow.

Thanks again
