### ISSUE TITLE
Chinese users cannot view rhino documents properly

### ISSUE THREAD

**Issue by etjson** [mozilla/rhino#1197]
![image](https://user-images.githubusercontent.com/41315967/159853713-d8705e21-723e-4f20-a9ad-f6b0f63d2e12.png)

Chinese users cannot view rhino documents properly.

**Comment by p-bakker** [comment]
Duplicate of #954

Mozilla removed all the docs they aren't maintaining anymore, including the Rhino docs.

We're in the process of hosting the docs here in this repo, see #954
