### ISSUE TITLE
How to enable feature in ScriptEngine?

### ISSUE THREAD

**Issue by cc1072027237** [mozilla/rhino#1198]
how to use FEATURE_ENABLE_JAVA_MAP_ACCESS
how can i do?

**Comment by tuchida** [comment]
Is this helpful to you?
https://github.com/mozilla/rhino/blob/70cb6aa9229d172834d1a83e61c62e2bc6e198e1/testsrc/org/mozilla/javascript/tests/NativeJavaMapTest.java#L27-L36

When using FEATURE_ENABLE_JAVA_MAP_ACCESS, please note the following.
https://github.com/mozilla/rhino/blob/70cb6aa9229d172834d1a83e61c62e2bc6e198e1/src/org/mozilla/javascript/Context.java#L319-L342

**Comment by p-bakker** [comment]
@tuchida not 100% sure, but I think there's no way to control the context when using Rhino through the ScriptEngine interface. See #1043 for a similar request

**Comment by cc1072027237** [comment]
OK, thank you!
