### ISSUE TITLE
Release Rhino 1.7R5

### ISSUE THREAD

**Issue by mathiasbynens** [mozilla/rhino#121]
On 2012-07-20 02:15:52 PDT, [Hannes said](https://bugzilla.mozilla.org/show_bug.cgi?id=775566#c2):

> This is a known regression in 1.7R4 that has been fixed in git master. It is
> the main reason 1.7R5 will be released soon.

It’s been almost a year. When can we expect a new official release? Is there anything we can do to help with the new release? (It seems to me just a release based on the current master branch would be fine.)

**Comment by gbrail** [comment]
Done!

https://github.com/mozilla/rhino/releases/tag/Rhino1_7R5_RELEASE

Will be up on Maven Central in a few hours.

**Comment by huntc** [comment]
Wow! Congratulations Greg!

**Comment by mathiasbynens** [comment]
Patch for the Homebrew formula: https://github.com/Homebrew/homebrew/pull/37142

(Could this be made part of the release checklist?)

**Comment by gbrail** [comment]
Thanks -- will add it to the checklist for future releases (which will come
in a lot less than every two years).

On Tue, Feb 24, 2015 at 12:47 PM, Mathias Bynens <notifications@github.com>
wrote:

> Patch for the Homebrew formula: Homebrew/homebrew#37142
> <https://github.com/Homebrew/homebrew/pull/37142>
>
> (Could this be made part of the release checklist?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/121#issuecomment-75819360>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>
