### ISSUE TITLE
.toString() on well-known Symbols does't work (properly)

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1221]
Evaluating `Symbol.replace` throws and exception: `TypeError: The object is not a string`

And when I do `"test"[Symbol.search]()` I get `TypeError: Cannot find function Symbol(Symbol.search).`
The issue with this later TypeError is that the `Symbol(Symbol.search)` comes from the SymbolKey.toString() impl, which should return just `Symbol.search`, however, SymbolKey.name already has `Symbol.search` as value, so the toString impl returns `Symbol(Symbol.search)` instead

Haven't looked at whats going on and whether this is limited to just Symbol.replace, all well-known Symbols or a larger issue

**Comment by karthiknadar1204** [comment]
I would like to work on this issue,please assign it to me

**Comment by p-bakker** [comment]
We don't typically assign cases to individuals. If you want to pick up a case, letting the community know as you've done above will do. Next just prepare and submit a PR 🙂

Looking forward to your contribution!

**Comment by p-bakker** [comment]
Closing this one as it isn't valid:
- It's technically correct that evaluating Symbol.replace throws a TypeError, as coercing a Symbol to a string should throw a TypeError according to the spec. Problem is only in the Rhino Shell where apparently it tries to coerce to a string, instead of detecting that the value is a Symbol and then calling .toString() on it
- The part of this case that suggested that the .toString() impl. of Symbol.search is incorrect is also not true. It's only that Rhino just throws a differently formatted Error message, using `Symbol(Symbol.search)` whereas Chrome for example uses [Symbol.search], but how to format error messages isn't defined in the spec, so either way is valid
