### ISSUE TITLE
Parent-child relationship in TaggedTemplateLiteral

### ISSUE THREAD

**Issue by kuzjka** [mozilla/rhino#1238]
Hi,

Our team is really happy to see string templates and tagged string templates support in Rhino 1.7.14.

However, I have noticed that descendants of `TaggedTemplateLiteral` node, which are _tag_ (target) and _string literal_, don't have parent relationship with `TaggedTemplateLiteral` node.

It looks a little illogical to me, and among other things, breaks `getAstRoot()`.

If parent is not set intentionally, please let me know.

I'll try to prepare a PR with tests and a fix soon.

Best regards,
Ihor.

**Comment by rbri** [comment]
LGTM
