### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by vcitiriga** [mozilla/rhino#1246]
My use case is embedded Rhino in a webapp running on Tomcat 9 with JDK8/11 to give my users automation/customization support.

The following code executes successfuly on 1.7.13:

```
var flags = SomeNamespaceObject.FLAG_SET_1; 
// this is a native java long value exceeding the 32-bit domain
// (the 'long' primitive, lowercase 'L')

var anObject = SomeNamespaceObject.findObjectByName("Mando", new java.lang.Long(flags));
// at this point, anObject is a native Java object which has protected property fields 
// with public getters and setters

var idByGetter = anObject.getId();
var idByField = anObject.id;
```

I should mention that the `Context.FEATURE_*` availability was left untouched, so default values should be assumed.

The same code, however, will crash on 1.7.14 as following. If the `Context.FEATURE`-s are let to defaults, then 

`var idByField = anObject.id;`

will throw a NPE even though `hasFeature(Context.FEATURE_ENHANCED_JAVA_ACCEES)` returns `false` on both 1.7.13 and 1.7.14 .

If I explicitly enable `Context.FEATURE_ENHANCED_JAVA_ACCEES`, then the above line of code will work, however,

`new java.lang.Long(flags);`

will throw a `NumberFormatException: For input string: "undefined"` on any of 1.7.13 or 1.7.14.

I should mention that the code pattern exemplified here is used extensively in my clients' codebase and 
is a big part of the customization each one adds to the webapp, so the code already written is beyond my control. 

Is there a way to make it work on 1.7.14? And if not then is there any chance it will be fixed in a future release?

Thanks.

**Comment by tonygermano** [comment]
Is it possible to share an example that can be tested by someone else? I think there are too many implementation details hidden to get a clear picture of what is going on.

**Comment by p-bakker** [comment]
Closing this as a reproducible example, as requested, has not been provided.

Feel free to reopen with a reproducible example
