### ISSUE TITLE
mozila rhino document website can't open

### ISSUE THREAD

**Issue by svfgvvvu** [mozilla/rhino#1258]
[www.mozilla.org/rhino/](https://www.mozilla.org/rhino/)

![image](https://user-images.githubusercontent.com/25682621/186558608-f8415ba3-521e-4bc6-ba9e-69083206c7f1.png)

![image](https://user-images.githubusercontent.com/25682621/186592339-ec1f464c-6ab4-4b18-b206-d532e0a5ff5f.png)

**Comment by p-bakker** [comment]
This is a know issue, see #954
