### ISSUE TITLE
IllegalStateException with code generated as standard by esbuild

### ISSUE THREAD

**Issue by gausie** [mozilla/rhino#1259]
When esbuild translates ESM imports to CJS, you get something like this

```js
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = function(target, all) {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: !0 });
}, __copyProps = function(to, from, except, desc) {
  if (from && typeof from == "object" || typeof from == "function")
    for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++)
      key = keys[i], !__hasOwnProp.call(to, key) && key !== except && __defProp(to, key, { get: function(k) {
        return from[k];
      }.bind(null, key), enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  return to;
};
var __toCommonJS = function(mod) {
  return __copyProps(__defProp({}, "__esModule", { value: !0 }), mod);
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: function() {
    return main;
  }
});
module.exports = __toCommonJS(main_exports);

// src/main.ts
function main() {
  console.log("Congrats!");
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {});
```

Because of `.bind(null, key)` that means that `cx.topCallScope` is null and so we throw an `IllegalStateException` when trying to access that export (see `ScriptRuntime.getTopCallScope`). Changing `null` to `this` in the JS fixes the issue.

Is this a problem with Rhino or ESBuild? Why does Rhino need to have `this` scope to access that function?

**Comment by gausie** [comment]
I think I understand the issue - internally we use `null` to mean that there is no `boundThis`, but this collides with setting an `boundThis` explicitly to JavaScript `null`.

**Comment by p-bakker** [comment]
I wonder whether this is due to Rhino not properly supporting strict mode, see #940

In strict mode when passing null for the this value, it ought to remain null is my understanding.

As your generated code has the "use strict" directive, I'm thinking in that direction.

Dunno if you're build system can generate that can run in non-strict?

**Comment by gausie** [comment]
> Dunno if you're build system can generate that can run in non-strict?

Not easily - for now I seem to have solved it in KoLmafia by making sure we're always running scripts with `doTopCall` if there is no top scope.

**Comment by p-bakker** [comment]
Am closing this, as imho this is due to #940
