### ISSUE TITLE
RHINO USAGE WARNING

### ISSUE THREAD

**Issue by yanonaoki** [mozilla/rhino#126]
The warning message that Rhino outputs when duplicate methods are registered may be unkind.
Can't find which class has duplicate method xxx from the message like "warning: RHINO USAGE WARNING: Invalid method "jsFunction_xxx": name "xxx" is already in use."

Please include class name in the message.

**Comment by gbrail** [comment]
FWIW we no longer write a "USAGE WARNING" to stderr for certain cases.
