### ISSUE TITLE
Support ES2023 hashbang grammer

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1274]
See https://github.com/tc39/proposal-hashbang

**Comment by CanadaHonk** [comment]
This is already supported for the most part with [a few minor test262 edgecase failures](https://test262.fyi/#language/comments/hashbang|rhino). Just fixed 2 in #1341 :)

**Comment by tuchida** [comment]
I have two questions.

1. `HashbangComment` is supposed to start with `#!` according to the ECMA262 specification.
https://tc39.es/ecma262/2023/#sec-hashbang
However, Rhino only checks `#`. I thought they were not ES2023 compliant.
https://github.com/mozilla/rhino/blob/f24883f7579b1a704c626b196914147afe1c2913/toolsrc/org/mozilla/javascript/tools/shell/Main.java#L564-L567

2. The feature of the `org.mozilla.javascript.tools.shell.Main` class is only enable in shell mode. Should `HashbangComment` be enabled when using Rhino from Java source code?

**Comment by CanadaHonk** [comment]
Good catch, I didn't spot that on a quick first look. It should check the next char and be moved into the main parser (most likely).

**Comment by p-bakker** [comment]
Agree with @tuchida that Hashbang should also work when using the Rhino engine directly, so not through the Shell
