### ISSUE TITLE
in js how to use java reflect

### ISSUE THREAD

**Issue by teaey** [mozilla/rhino#128]
# java

java.util.Date.class.getField()
# js

how to wirte?
1. new java.util.Date().getClass().getField()
2. Class.forName('java.util.Date').getField()

Is there a simple method to get the Class object?

**Comment by p-bakker** [comment]
This works:  new java.lang.String().class.getField("CASE_INSENSITIVE_ORDER")

Maybe you got errors because you didn't supply the name of the field to get? Class only has the methods .getFields() and .getField(String name)
