### ISSUE TITLE
Position incorrect for Parenthesized expression.

### ISSUE THREAD

**Issue by peterhal** [mozilla/rhino#129]
Given a file containing:

(a);

The absolute position of the AstNode will be 1 (the char index of the 'a'). 
Expected absolute position to be 0 (the index for the '(').

Contrast this with an array literal which has absolute position set correctly:

[a];

**Comment by kuzjka** [comment]
Yes, for example having `(a).b();` and extracting function call's target from source string according to node position we got `a).b` which looks pretty weird.

I'm preparing PR to fix this. We can use constructor with explicit position in `Parser#parenExpr()`. I'll check if it doesn't brake tests.
