### ISSUE TITLE
Support in Graalvm 

### ISSUE THREAD

**Issue by AkashItorix** [mozilla/rhino#1303]
Not able to run rhino Script in java using graalvm sdk.Getting this error while running it.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/105375362/217915557-5c2f5bfc-f5fe-4abf-9170-bb1a36b5bafe.png">
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/105375362/217915696-e3c7348b-c7d2-4dfb-8e10-1d0153d5e811.png">

**Comment by p-bakker** [comment]
Compiling graal.js with Rhino while running in graalvm? Interesting setup...

No graalvm expert here, but judging the stacktrace you're trying to build or run a graalvm native image and your Rhino code it trying to load or dynamically create Java Classes and Native
Image doesn't support/like/allows that.

Anyway, this is not something to report here, as it has to do with graal and native image, not with Rhino.

So am closing this issue
