### ISSUE TITLE
Support ES2023 Change Array by copy

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1307]
Proposal: https://github.com/tc39/proposal-change-array-by-copy

**Comment by pkkht** [comment]
Hello, 
Thanks for flagging this as "good first issue". Can I work on this please.

**Comment by p-bakker** [comment]
Yes, we'd welcome a PR for this

Check [Contributing PRs](https://github.com/mozilla/rhino#contributing-prs) for some guidelines and pointers

As for tests: unfortunately we cannot run the latest version of the Test262 testsuite, which means the [Change Array by Copy tests](https://github.com/tc39/test262/commit/6f4601d095a3899d6102f2c320b671495cbe8757) are not included yet within Rhino.

So depending on your timeline, you'll need to include tests yourself or we might be able to switch to the latest version of Test262 before you're finished, see ([#958](https://github.com/mozilla/rhino/issues/958#issuecomment-868532333))

**Comment by pkkht** [comment]
Cool, please assign the issue to me. I am reading the docs to get an understanding of the changes. I will post any question in the Google group.

**Comment by p-bakker** [comment]
We don't typically assign issues to people, just submit a PR and everything will work out.

**Comment by pkkht** [comment]
Thanks, I will be able to start work late next week.

**Comment by p-bakker** [comment]
FYI: I just found out that all TypeArray implementations that Rhino supports are missing (almost) all methods that they ought to share with regular Arrays.

As such, I think there might be way more to it to also implement the new methods that are part of the 'Change Array by Copy' proposal to all Typed Arrays, so maybe use this case to just add the proposed methods to NativeArray and let the TypedArray part of the proposal be part of #1411
