### ISSUE TITLE
CI: Set minimal permissions on GitHub Workflows

### ISSUE THREAD

**Issue by diogoteles08** [mozilla/rhino#1309]
Hi!

I'm here to suggest the definition of minimal permissions on your workflows, as it would harden your security agains supply-chain attacks. 

I see your workflows [publish-github.yml](https://github.com/mozilla/rhino/blob/master/.github/workflows/publish-github.yml) and [publish-maven](https://github.com/mozilla/rhino/blob/master/.github/workflows/publish-maven.yml) are already declaring their jobs minimal permissions, and that's great! The idea would be to do similarly to your [gradle.yml](https://github.com/mozilla/rhino/blob/master/.github/workflows/gradle.yml) workflow, but the ideal would be to declare a read-only top-level permission, so that any job on that workflow (including jobs added in the future) would inherit these safe permissions if they don't declare their own.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://securityscorecards.dev/#learn-more) and [StepSecurity](https://github.com/step-security).

Please let me know what you think about this change, I'd be happy to raise a PR if you agree.

#### Context
I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

**Comment by p-bakker** [comment]
Tnx for raising this. A PR would be more than welcome
