### ISSUE TITLE
Resume continuation by throwing exception

### ISSUE THREAD

**Issue by eshepelyuk** [mozilla/rhino#131]
Hello, 

is there any example of resuming continuation not be passing value but to make JS to throw exception from function invocation ?

**Comment by Kevin-Jin** [comment]
Hi eshepelyuk,

I wanted to know why you closed this issue. I seem to be running into the same problem.

**Comment by Kevin-Jin** [comment]
I found a workaround. While it's impossible to throw a WrappedException, I was able to throw a EvaluatorException.

    // Declare as a variable accessible by the continuation capturer and resumer.
    WrappedException resumeContinuationEx;
    ...

    // In continuation capturer.
    resumeContinuationEx = new WrappedException(new Throwable());
    ContinuationPending interrupter = cx.captureContinuation();
    ....

    // In continuation resumer.
    Throwable resultEx = ...;
    EvaluatorException cause = new EvaluatorException("Wrapped " + resultEx.toString(), resumeContinuationEx.sourceName(), resumeContinuationEx.lineNumber());
    cause.initCause(resultEx);
    throw cause;
