### ISSUE TITLE
PVS-Studio

### ISSUE THREAD

**Issue by AndreyKarpov** [mozilla/rhino#132]
PVS-Studio: http://www.viva64.com/en/pvs-studio/
----
V567 Undefined behavior. The 'currentMap' variable is modified while being used twice between sequence points. aossessionmanager.cpp 140

u4 AOSSessionManager::threadprocSessionManager(AThread& thread)
{
  ....
  currentMap = ((++currentMap) % pThis->m_HolderSize);
  ....
}

---
V576 Incorrect format. Consider checking the fourth actual argument of the 'sprintf_s' function. To print the value of pointer the '%p' should be used. memleakdetect.cpp 231

void*	address;

void CMemLeakDetect::dumpMemoryTrace()
{
  ....
  sprintf_s(buf, MLD_MAX_NAME_LENGTH, "Memory Leak <0x%X> "
            "bytes(%d) occurance(%d) %s(%d)\n",
            ainfo.address, ainfo.size, ainfo.occurance,
            ainfo.fileName, ainfo.lineNumber);
  ....
}

And:
V576 Incorrect format. Consider checking the fourth actual argument of the 'sprintf_s' function. To print the value of pointer the '%p' should be used. memleakdetect.cpp 236
V576 Incorrect format. A different number of actual arguments is expected while calling 'sprintf_s' function. Expected: 4. Present: 5. memleakdetect.cpp 490
----
V662 Consider inspecting the loop expression. Different containers are utilized for setting up initial and final values of the iterator. aosconfiguration.cpp 93

MAP_LOCALE_DIRS m_LocaleStaticDirs;
MAP_LOCALE_DIRS m_LocaleDataDirs;

void AOSConfiguration::debugDump(std::ostream& os, int indent) const
{
  ....
  for (AOSConfiguration::MAP_LOCALE_DIRS::const_iterator cit =
         m_LocaleStaticDirs.begin();
       cit != m_LocaleDataDirs.end(); ++cit)
  ....
}  
---
V576 Incorrect format. Consider checking the sixth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 261

DWORD memoccurance;

void CMemLeakDetect::dumpMemoryTrace()
{
  ....
  _stprintf_s(buf, MLD_MAX_NAME_LENGTH,
   _T("Total %d Memory Leaks: %d bytes Total Alocations %d\n\n"),
   numLeaks, totalSize, memoccurance);
  ....
}

And
V576 Incorrect format. Consider checking the fifth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 231
V576 Incorrect format. Consider checking the sixth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 231
V576 Incorrect format. Consider checking the eighth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 231
V576 Incorrect format. Consider checking the fifth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 236
V576 Incorrect format. Consider checking the sixth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 236
V576 Incorrect format. Consider checking the fourth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 256
V576 Incorrect format. Consider checking the fifth actual argument of the 'sprintf_s' function. The SIGNED integer type argument is expected. memleakdetect.cpp 479

**Comment by gbrail** [comment]
I am inclined to close this as having nothing to do with Rhino unless someone else has an idea here.
