### ISSUE TITLE
Upgrade the minimum Java version

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#1339]
I have in the past been adamant that we maintain Java 8 compatibility in this project, but with all the changes going into Java today, that's getting increasingly difficult -- right now it's a lot of work to have a project that builds with both Java 8 and Java 20, for example. Large organizations seem to be deploying Java 17 pretty broadly, for example, so I think that policies that were holding people on Java 8 may be gone by now.

Given all that, what Java version does the community think that we should be targetting? I could see easily going up to Java 11, for example, but there are additional advantages to supporting even newer versions.

**Comment by p-bakker** [comment]
Better move this to discussions? We already have somewhat of a discussion going there: https://github.com/mozilla/rhino/discussions/1169

**Comment by p-bakker** [comment]
As of the nether of #1479 the minimum Java version for Rhino is 11
