### ISSUE TITLE
In object literals, Rhino considers the property names `13` and `0x13` to be identical

### ISSUE THREAD

**Issue by hegemonic** [mozilla/rhino#134]
Rhino throws an exception when it tries to parse the following file, with the message `Property "13" already defined in this object literal`:

```js
'use strict';

var foo = {
    13: 'bar',
    0x13: 'baz'
};
```

This is because Rhino treats `13` and `0x13` as identical values, and in strict mode, object literals can't contain duplicate property names.

This bug is similar to #99.

**Comment by eshepelyuk** [comment]
@hegemonic This is not reproducible in latest `Rhino`.
I've tried to launch shell and execute code snippet.
Maybe the bug can be closed ?

**Comment by hegemonic** [comment]
@eshepelyuk Sure, that's fine with me. (I haven't tested this myself, but I'll take your word for it.)
