### ISSUE TITLE
Dead download link for rhino1_7R4

### ISSUE THREAD

**Issue by lainwir3d** [mozilla/rhino#1345]
Hi, 

Following download link is dead:

https://github.com/downloads/mozilla/rhino/rhino1_7R4.zip

Just thought I'd let you know.

**Comment by p-bakker** [comment]
And where did you find this link?

**Comment by p-bakker** [comment]
right, well that link is not under our control, but I see that the same invalid link is used is our new documentation, so that needs fixing anyway.

You can find 1.7R4 on Maven btw: https://mvnrepository.com/artifact/org.mozilla/rhino

**Comment by oohsai** [comment]
Hey! I'd like to work over this! Could you explain how i could be of help?

**Comment by p-bakker** [comment]
I've found the correct link to the 1.7R4 'release' and updated it in our own release overview on https://rhino.github.io/releases/

As we're not in control of http://udn.realityripple.com/docs/Mozilla/Projects/Rhino/Downloads_archive, there's not much we can do there, so am closing this case now

@oohsai if you'd like to contribute to the Rhino documentation, please ask in #954
