### ISSUE TITLE
Unable to get rhino to convert json

### ISSUE THREAD

**Issue by steowens** [mozilla/rhino#135]
The following unit test fails due to the fact that Rhino 1.7r4 does not initialize the global scope with JSON:

``` java
@Test
public void findOutTypeReturnedFromRhino() throws JsonProcessingException{
    String jsScript = "function f(){ return JSON.stringify({property1:\"hello\", array1:[{subobject:1}]}); } f();";
    Context jsContext = Context.enter();
    Scriptable jsScope= jsContext.initStandardObjects();
    Object result = jsContext.evaluateString(jsScope, jsScript, "myscript.js", 1, null);
    System.out.println(result.getClass().getName());    
}
```

The exception returned is:
org.mozilla.javascript.EcmaError: ReferenceError: "JSON" is not defined. (myscript.js#1)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3557)
    ... more ...

**Comment by gbrail** [comment]
This seems to be working OK in 1.7R5. Can you re-test?

**Comment by steowens** [comment]
Will do

**Comment by tonygermano** [comment]
@gbrail I think this can be closed. A test case was added.
