### ISSUE TITLE
Suggest Adoption of Scorecard GitHub Action

### ISSUE THREAD

**Issue by diogoteles08** [mozilla/rhino#1354]
Hey, I'm Diogo and I've raised the issues #1309 and #1327 contributing with some security enhancements. I'll happily continue contributing with such improvements (it's literally my job, see [my profile](https://github.com/diogoteles08/diogoteles08/blob/main/README.md#about-gosst-ghost)), but this time I come to suggest the tool that I used myself to find those security issues.

I'd like to suggest that the project add the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). The OpenSSF Scorecard uses GitHub's public API to gather public informations about your project and runs a sort of "meta-analysis" of the project's security posture. The Action then populates the project's [Security Panel](https://github.com/mozilla/rhino/security) with possible improvements to its security posture. It's specially helpful to ensure you won't regress on the security measures you have already adopted 😄.

Additionally, the tool integrates with the [OSV Scanner](https://security.googleblog.com/2022/12/announcing-osv-scanner-vulnerability.html), which evaluates a project's transitive dependencies looking for known vulnerabilities.

When working on the Security enhancements pointed by Scorecard, you're also able to apply for the [OpenSSF's Secure Open Source Rewards](http://sos.dev/) program, which financially rewards developers for improving the security of important open source projects

This tool is developed by the OpenSSF [in partnership with GitHub](https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/) and it's already been adopted by 1800+ projects, including [Tensorflow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch), [Angular](https://github.com/angular/angular), and [Flutter](https://github.com/flutter/flutter).

If you're interested, let me know and I'll send a PR!

**Comment by diogoteles08** [comment]
Hey! This issue/PR has been idle for quite some time. Do you plan on considering this suggestion? If not, I'll probably wait up to 2 more months and close the issue.

Thanks!

**Comment by p-bakker** [comment]
@gbrail @rbri thoughts on this?

**Comment by rbri** [comment]
Have done it for HtmlUnit - if you like you can have a look at the results

https://securityscorecards.dev/viewer/?uri=github.com/HtmlUnit/htmlunit

**Comment by p-bakker** [comment]
I'd say it's wouldn't hurt to have it, no?

**Comment by rbri** [comment]
It hurts only if you try to increase the score

**Comment by diogoteles08** [comment]
> It hurts only if you try to increase the score

haha indeed. But keep in mind that none of the security improvements suggested by Scorecard should be interpreted as highest priority and implemented right away -- you should understand the suggestions and evaluate if they make sense to the scope of your project. And I'll be happy to help on that, and eventually also contribute with some desired changes, as I did on #1309 and #1327.

I'd say the main advantages of using this action are actually:
1. Ensure the project doesn't regress on security mesures already adopted
2. Keep track on possible transitive vulnerabilities through OSV Scanner
3. Show-off how your project cares about your security posture, as Scorecard also has its [customer-faced side](https://www.sonatype.com/state-of-the-software-supply-chain/open-source-security-practices) -- it helps OSS consumers to evaluate the confiability of packages before their consumption.

**Comment by p-bakker** [comment]
I'd say we'd welcome the PR to do this then :-)
