### ISSUE TITLE
print() inside a script sometime may not print the args

### ISSUE THREAD

**Issue by nmondal** [mozilla/rhino#1356]
This is coming from here:
https://github.com/nmondal/cowj/issues/35

The reason why the print() was not working is a premature optimization in the rhino code base.
Specifically:
org/mozilla/javascript/engine/Builtins.java

Has this code:

```java
public static void print(Context cx, Scriptable thisObj, Object[] args, Function f)
      throws IOException {
    Builtins self = getSelf(thisObj);
    for (Object arg : args) {
      self.stdout.write(ScriptRuntime.toString(arg));
    }
    self.stdout.write('\n'); // bug here, assumes line buffering and auto flush 
  }
```

Problem happens with this, self.stdout is not flushed. If one does flush it, the result is immediate.
This is a bug and we should let Mozilla folks replace the last line as:

```java
self.stdout.println()
```

That should do it.

**Comment by p-bakker** [comment]
Feel like providing a PR with a testcase and a fix?

**Comment by nmondal** [comment]
Sure.. let's do it!

**Comment by nmondal** [comment]
@p-bakker here we go : https://github.com/mozilla/rhino/pull/1358

**Comment by p-bakker** [comment]
@rbri how does this PR look to you?

**Comment by nmondal** [comment]
@p-bakker  ... things run! Now .. we need to get some committers.. how?

**Comment by p-bakker** [comment]
As @rbri is one of the committers, I think/hope he'll take care of it :-)

Otherwise, just give it a bit of time 'till one of the other comitters gets around to it, all volunteers here.

**Comment by rbri** [comment]
Thanks again.
