### ISSUE TITLE
String type of arguments supporting for importClass and importPackage

### ISSUE THREAD

**Issue by SuperMonster003** [mozilla/rhino#1359]
The code below works well:

```js
importPackage(Packages.org.foo.bar.xyz);
```

I hope that code below could also work:

```js
importPackage("Packages.org.foo.bar.xyz");
importPackage("org.foo.bar.xyz"); /* Same as above. */
```

**Comment by p-bakker** [comment]
Don't think we should do this. Instead we should do #1058

**Comment by p-bakker** [comment]
> Don't think we should do this. Instead we should do https://github.com/mozilla/rhino/issues/1058

I stand partially corrected: importPackage/Class(...) imports all the (public?) classes of the provided package name into the top level scope, which maybe be handy in some use cases, but quite dangerous in others. As such, environments like GraalJS and Nashorn don't have such api at all.

Still not sure of we should allow strings as parameter, as that has the same issue as providing Packages.x.y.z: make a typo and no errors will be thrown

Instead I think if anything, we should support importPackage/Class(Java.type(name:string))

What is your use-case though?

**Comment by SuperMonster003** [comment]
Thank you for the reply.

Here is a use case.

- Copy some imports statements from java / kotlin
- Paste them to a JavaScript file
- Replace import with importClass/importPackage
- Run the JavaScript file

An exception often thrown with message like `ReferenceError: "xxx" is not defined`.

Then i should append with a prefix `Packages.`

If i could use string param, only one key (`'` or `"`) would be needed. Then the class or package will be quoted by a pair of quotation mark without appending the prefix `Packages.`.

That's the reason why i hope that "string type of arguments supporting for importClass and importPackage" might happen.

![image](https://github.com/mozilla/rhino/assets/30370009/a64a3d65-c323-4cce-9980-0620cacf10da)

**Comment by p-bakker** [comment]
Am going to close this as I do not think we should build upon the old mechanism and instead invest in [implementing a better API](#1085) similar to what GraalJS does (https://www.graalvm.org/latest/reference-manual/js/JavaInteroperability/#access-java-from-javascript), which has several benefits 

Maybe in the future we could/should also allow importing Java classes/packages using EcmaScript Module import syntax: I think ESM allows for importing modules implemented in other languages
