### ISSUE TITLE
"net" should not be a preloaded Java package

### ISSUE THREAD

**Issue by botic** [mozilla/rhino#1360]
It looks like `net` is a pre-loaded Java package, but I find no documentation or use of it:

```
rhino > java -jar buildGradle/libs/rhino-1.7.15-SNAPSHOT.jar
Rhino 1.7.15-SNAPSHOT
js> net
[JavaPackage net]
```

Where gets the `net` variable loaded / is there any need for this behavior in future Rhino releases?

**Comment by p-bakker** [comment]
`net` is just like java/javax/com/edu/org/com and points to the base `net` package identifier gets loaded here: https://github.com/mozilla/rhino/blob/76fc05e8c6cc53c5d270ff9f40c3b358006c4818/src/org/mozilla/javascript/ScriptRuntime.java#L311

**Comment by botic** [comment]
Oh thanks for that hint! No idea why I missed that with my searches, but now it's clear why `const net = …` fails.

**Comment by botic** [comment]
Okay, after searching again I still have no idea why `"org", "com", "edu", "net"` are in that list, since they where never part of any Java specification I know. So I guess this was for developer convenience instead of being close to a plain JavaScript environment.

https://github.com/mozilla/rhino/commit/8ec32e65ceeb9ca148016e1de06e7f164646da2d

Maybe this should be changed to the remaining `java` and `javax` top-level packages defined by [Java SE](https://docs.oracle.com/en/java/javase/19/docs/api/allpackages-index.html) or an configuration option to drop this behavior in a strict JavaScript mode?

**Comment by p-bakker** [comment]
If you embed Rhino, you can already control what gets added to the top leven scope I think, through various means
