### ISSUE TITLE
ES2015 Object own keys order issues

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1389]
Rhino doesn't conform to the rules laid out in ES2015 wrt the ordering of own keys in objects

Some quick examples of at least some of the issues:
```
var x = {'D': true, '-1': true}
x.A = true
x.Z = true
x.V = true
x.h = true

Object.keys(x) // yields [-1, D, A, Z, V, h], should be  [D, -1, A, Z, V, h] as -1 is not an array index key
JSON.stringify(x) // yields {"-1":true,"D":true,"A":true,"Z":true,"V":true,"h":true}, same issue as with Object.keys
JSON.parse(JSON.stringify(x)) // yields {true,D:true,A:true,Z:true,V:true,h:true}: -1 key completely missing so invalid JSON
```

See:
- https://mozilla.github.io/rhino/compat/engines.html#ES2015-misc-own-property-order
- https://dev.to/frehner/the-order-of-js-object-keys-458d

**Comment by rbri** [comment]
At least for HtmlUnit i did some hacking in this way https://github.com/HtmlUnit/htmlunit-rhino-fork/commit/e6c4c79bf0a20a7bae6cbe121e9149691a7ac927

But i guess we can't fix this without breaking the backward compatibility.

**Comment by p-bakker** [comment]
In what way does it break backwards compatibility? Just that the keys will be ordered differently (but properly)?

**Comment by gbrail** [comment]
Thanks -- can we narrow this down to a specific list of issues?

It sounds like there is an issue with numeric keys that can't be used as
array indices -- Rhino is improperly treating them as numbers whereas they
should be left as strings. It's not clear yet whether this is a problem
when the keys are inserted or in the comparator that's used to compute the
(unnecessarily expensive, IMO) sort order required to implement the spec.

It sounds like there also might be an issue with JSON.stringify, as it
should never skip keys.

Are there other specific issues?

**Comment by p-bakker** [comment]
I haven't done a full analysis, the same code above was just a quick test I did locally after I saw the many failures in the ES2015 own keys section in the Kangax Compat table

**Comment by rbri** [comment]
more details about the HtmlUnit story are here https://github.com/HtmlUnit/htmlunit/pull/595
