### ISSUE TITLE
Project website says "Page not found"

### ISSUE THREAD

**Issue by jlmuir** [mozilla/rhino#1390]
At <https://github.com/mozilla/rhino/>, the website URL of this project is listed as <https://www.mozilla.org/rhino/>, but when I open that, I get redirected to <https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino>, which says, "Page not found":

<img width="743" alt="rhino-page-not-found" src="https://github.com/mozilla/rhino/assets/959381/4be49deb-7561-4f0f-b478-4aa68ac81721">

Maybe it should be <https://mozilla.github.io/rhino/> instead?

**Comment by p-bakker** [comment]
See #954

**Comment by jlmuir** [comment]
I don't follow.  I can't update the website URL of the project because I don't have permissions to do so.  I can't submit a PR because the project website URL is not stored in a file in the repo.  I suggested what the website URL could be changed to, but I'm sure you know better than me.  If there is no website, then I suggest removing the website URL from the project so that people don't click on it and get a "Page not found" page.

**Comment by p-bakker** [comment]
Issue #954 is about the fact that we're in the process of getting our documentation back up and running. See the last few comments on that case to get a grasp of where things stand
