### ISSUE TITLE
Suggestion: Split jar into core and tools

### ISSUE THREAD

**Issue by hrj** [mozilla/rhino#141]
The Rhino jar bundles tools, REPL and debugger in it.

I suggest that the Rhino package be split into separate jars. Tentatively into "core" and "tools".

This will help reduce the size of the "core" package, which is what many projects would probably use for deployment.

Apart from size, there are other benefits to be had from a security point of view, such as reduction in surface-area of attacks.

The next major Rhino release (say 1.8.0) might be an opportunity to make the change.

**Comment by potyl** [comment]
I would love to have the jar split into. This will make embedding javascript in an android app much more easier. In android an application is limited to reference 65,536 methods. If more methods are used then we need to go trough lots of complications to avoid this hard limitation.

Right now rinho adds more than 7,000 methods. If we remove the "tools" package we can remove 1,200 methods.

I am writing a stetho plugin that provides a javascript REPL (see https://github.com/potyl/stetho/tree/stetho/repl) and being able to have a streamlined rhino jar would greatly be appreciated.

**Comment by p-bakker** [comment]
@gbrail Isn't this sorted in v1.7.13? Looks like the rhino-runtime-1.7.13.jar artifact excludes tools, whereas rhino-1.7.13.jar includes it

**Comment by gbrail** [comment]
I wanted to split them completely, but too much code uses core and tools
together that it made sense to create a new JAR like we did. And yes, you
should split it.

**Comment by gbrail** [comment]
Agreed -- creating a separate runtime jar made more sense.
