### ISSUE TITLE
ES2015 TypedArrays missing all methods they ought to share with regular Arrays, like map/indexOf/includes etc

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1411]
All TypedArray implementations ought to have a large chunk of methods that regular Arrays also have, like indexOf/includes/map/forEach etc. However, those all seem to be missing, see https://compat-table.github.io/compat-table/es6/ > built-ins > typed arrays

In addition to the missing methods that are defined in ES2015 (ES6):
- ES2016 specified the addition of the .includes() method on (Typed)Arrays
- ES2020 specifies two new TypedArray variants, see #1410
- ~ES2022 specifies the .at() method on (Typed)Arrays~ 
- ES2024 adds new methods via the `Array find from last`
- ES2024 adds new methods via the `Change Array by copy`, see #1307

**Comment by p-bakker** [comment]
@andreabergia do you agree that all method are now implement (albeit having failing tests here and there), except for static stuff that ought to be implemented in the missing TypedArray prototype? 

If so, I think we can close this case, as we have individual cases for the other stuff, agree?

**Comment by gbrail** [comment]
Neither here nor there, but I think that someone should take the time to
convert the NativeArray to lambdas (it's a big job) and then take a sharp
look at the architecture of the native arrays and see if that can be
improved once we've done that -- I did the native arrays a long time ago, I
recall that they were weird, and I recall doing a lot of weird things to
make them work that might not be necessary any more now that we have a
construct that maps more closely to the actual language.

**Comment by p-bakker** [comment]
I think doing that in #1565, which involves creating a NativeTypedArray class containing most of the scripting API impl. And have that be the prototype for all typed array constructors would make sense

**Comment by p-bakker** [comment]
@andreabergia what's your take on whether the scope of just adding the missing method is now done or not?

**Comment by andreabergia** [comment]
> @andreabergia do you agree that all method are now implement (albeit having failing tests here and there), except for static stuff that ought to be implemented in the missing TypedArray prototype?
> 
> If so, I think we can close this case, as we have individual cases for the other stuff, agree?

Sorry for the late answer. 
I agree with you - everything should be implemented, except for the static `TypedArray.from` and `.of`. I couldn't find an issue for those, though.

**Comment by p-bakker** [comment]
Everything mentioned in this case for done in various derived cases and PRs, so closing
