### ISSUE TITLE
ES2015 Generators don't work properly in non-interpreted mode

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#1412]
Consider the following testcode `(function*(a) {console.log(a)})(11,22).next()`:
- interpreted: value of `a` parameter is `11`
- non-interpreted: value of `a` parameter is some function object

**Comment by p-bakker** [comment]
@gbrail since you authored the implementation of ESGenerator ~4 years ago, any idea what might be going on here?

**Comment by tonygermano** [comment]
There was an old javascript 1.7 generator implementation that I believe worked that way. My guess is that it's hitting that old code.

**Comment by tonygermano** [comment]
Scratch that. I just reread what the issue was and the problem is with passing the parameter, not the result of next(). Is it still possible that it has something to do with the legacy implementation?

**Comment by tonygermano** [comment]
I did some more testing. It assigns the same new generator function object to all of the parameters with the same function body as the original function. It appears to do that only when the generator function has no yield statement. 

```javascript
s> var param1, param2, g = function*(a,b) {param1 = a; param2 = b}, it = g(11,12)
js> typeof param1
undefined
js> it.next()
[object Object]
js> param1

function (a, b) {
    param1 = a;
    param2 = b;
}

js> param1 === param2
true
js> Object.prototype.toString.call(param2)
[object __GeneratorFunction]
js> param2 === g
false
js> oldResult = param2

function (a, b) {
    param1 = a;
    param2 = b;
}

js> param1 = undefined
js> oldResult(13,14).next()
[object Object]
js> param1

function (a, b) {
    param1 = a;
    param2 = b;
}

js> param1 === param2
true
js> param1 === oldResult
false
```

```javascript
js> var param1, param2, g = function*(a,b) {param1 = a; param2 = b;yield}, it = g(11,12)
js> it.next()
[object Object]
js> param1
11
js> param2
12
```

**Comment by p-bakker** [comment]
Thnx for looking into it. Hope @gbrail can deduct what might be going wrong from all this input

**Comment by gbrail** [comment]
I’ll try to look at this next week when I am back from vacation

**Comment by p-bakker** [comment]
@gbrail any luck giving this a look?
