### ISSUE TITLE
`Math.atanh` is broken

### ISSUE THREAD

**Issue by andreabergia** [mozilla/rhino#1437]
The implementation of `Math.atanh` is broken: it is currently implemented as 

```java
            return Double.valueOf(0.5 * Math.log((x + 1.0) / (x - 1.0)));
```

but it should be:

```java
            return Double.valueOf(0.5 * Math.log((x + 1.0) / (1.0 - x)));
```

See for example [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atanh) or [Wikipedia](https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions)

**Comment by rbri** [comment]
OMG - looks like this was my fault - Sorry for that....

The Test262 tests suite seem to have no real values tests - only border cases.

@andreabergia maybe you can add some more test for ordinary values for the different functions

And THANKS for this great finding and the PR

**Comment by andreabergia** [comment]
> The Test262 tests suite seem to have no real values tests - only border cases.

Guess I'll need to open a PR there, too. 🙂 

> @andreabergia maybe you can add some more test for ordinary values for the different functions

I think I already did? For the functions that were already covered, there were normal and edge cases. For the uncovered functions, I have added a bit of both.
