### ISSUE TITLE
toLocaleDateString not supporting non-english locales

### ISSUE THREAD

**Issue by ilapavuluri** [mozilla/rhino#1439]
I am using rhino 1.7.14 (latest version) in my java application as JS engine

The below code is returing: 'January 15, 2024' (is the value of create_date_de2)

options = {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric',
};

create_date_de2 = (new Date()).toLocaleDateString('de-DE',options);

In online javascript, if I run:
const options = { year: 'numeric', month: 'long', day: 'numeric' };
console.log((new Date()).toLocaleDateString('de-DE',options))

it is working fine by providing: 15. Januar 2024

Why rhino is not supporting locale? am I missing anything here? do I need to do any configuration ? Mine is windows machine German language pack also installed.

Appriciate any help on this.

Thanks
Ashok.

**Comment by p-bakker** [comment]
Many of the Locals-related APIs aren't part of cute EcmaScript, but of the (optional) Intl-402 EcmaScript extension 

Rhino does not have support for (most of the) extended APIs defined by Intl-402 unfortunately
