### ISSUE TITLE
`default xml namespace` oddity

### ISSUE THREAD

**Issue by xandris** [mozilla/rhino#144]
While debugging a function that uses `default xml namespace` while building a large document and calls out to other functions to build smaller nested chunks of the document, I noticed some sub elements were being written with `xmlns=""` and some weren't. I narrowed down the difference to the `xmlns=""` elements being generated by functions that contained inner functions. Here's an example that demonstrates the anomaly in 1.7R5:

``` javascript
function a() { return <a/>; }
function b() { var f = function() { }; return <b/>; }
function ab() { default xml namespace = 'urn:default'; var r = <ab/>; r.ab+=a(); r.ab+=b(); return r; }
ab()
```

Notice that `var f = function() { };` is never used, just declared.

Result:

```
<ab xmlns="urn:default">
  <a/>
  <b xmlns=""/>
</ab>
```

Expected either:

```
<ab xmlns="urn:default">
  <a xmlns=""/>
  <b xmlns=""/>
</ab>
```

or

```
<ab xmlns="urn:default">
  <a/>
  <b/>
</ab>
```

Maybe? I can't tell from reading the E4X specification which if any of these is correct.

**Comment by henning-meinhardt** [comment]
Hey Alexandra, can you give some information why you closed the issue again? Did the problem disappear after updating the rhino version or did you solve it any other way?
Kind regards
Henning

**Comment by xandris** [comment]
Hi Henning,

I don't work on the project that has this issue anymore (that was over 4 years ago...), so I have no idea if this is still an issue or not.
