### ISSUE TITLE
Question: TimeSchedule of 1.17.15 to built new release - release plan given?

### ISSUE THREAD

**Issue by speckyspooky** [mozilla/rhino#1443]
Hello together,

the rhino engine is a powerfull engine and it is integrated at the BIRT project with the latest version 1.17.14 thorugh the orbit-project.
I know the latest official release is from 2022. Is a release plan given to publish a new release 1.17.15?

I see the rhino project is active and many bugfixes and improvements are added.
So it would be greate if there is a plan to create 1.17.15.

Thanks in advance for some details of it.

**Comment by p-bakker** [comment]
Rhino 1.7.15 has been releases early May

**Comment by speckyspooky** [comment]
Great!
