### ISSUE TITLE
Rhino link in the "About" section is broken

### ISSUE THREAD

**Issue by akkadaya** [mozilla/rhino#1452]
Rhino link in the "About" section is broken, use https://mozilla.github.io/rhino/ instead.

<img width="330" alt="image" src="https://github.com/mozilla/rhino/assets/1834445/77078aac-bcc6-4425-ad7c-bc84da98300a">

**Comment by michaelachrisco** [comment]
It might need to be this: http://mozilla.github.io/rhino/

**Comment by p-bakker** [comment]
Duplicate of #954
