### ISSUE TITLE
Is Java 17 a requirement for building the library? 

### ISSUE THREAD

**Issue by why-not-try-calmer** [mozilla/rhino#1465]
_updated_: I am now able to build using openjdk17. Is it the latest openjdk version supported for building the library? If so do you mind I PR this information to the README?

_deprecated_:
I am unable to build with
```
./gradlew jar
```
with
```
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-nixos)
OpenJDK 64-Bit Server VM (build 19.0.2+7-nixos, mixed mode, sharing)
```
Here is the log:
[error.txt](https://github.com/mozilla/rhino/files/15041232/error.txt)

Any hint warmly appreciated!

**Comment by p-bakker** [comment]
It is not, Java 11 is the minimum

**Comment by why-not-try-calmer** [comment]
Sure, sorry I forgot to close, I found the issue a long time ago
