### ISSUE TITLE
Adjust module structure for better backward compatibility

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#1488]
@carlosame has pointed out that the new module structure doesn't work for projects that already adopted modular Java using Rhino 1.7.14 and after. Here are two proposals for changes.

I would prefer the first proposal, which makes Rhino maximally compatible with the spirit of Java modules, but will require many people to change their build configurations to adopt this release.

Current structure (master branch):

| Directory | Module | JAR Name | Contents |
| -- | -- | -- | -- |
| rhino-runtime | org.mozilla.rhino-runtime | rhino-runtime.jar | Core Classes |
| rhino-tools | org.mozilla.rhino-tools | rhino-tools.jar | Shell and Debugger |
| rhino-xml | org.mozilla.rhino-xml | rhino-xml.jar | XML implementation |
| rhino-engine | org.mozilla.rhino-engine | rhino-engine.jar | Script Engine |
| rhino | N/A | rhino.jar | All-in-one JAR |

Implications:
* Modular applications that relied on the "rhino" module need to change the name of the module that they import so that they import "rhino-runtime" instead.
* Modular applications that previously used the "rhino.jar" need to use a different JAR because "rhino.jar" is no longer modular
* Non-modular applications *should* switch to the new modular JARs but need not switch.

Proposal 1: 
(-tools, -XML, and -engine remain the same)

1) Rename "rhino-runtime" module to "rhino"
2) Rename all-in-one JAR to "rhino-all"

| Directory | Module | JAR Name | Contents |
| -- | -- | -- | -- |
| rhino | org.mozilla.rhino | rhino.jar | Core Classes |
...
| rhino-all | N/A | rhino-all.jar | All-in-one JAR |

Implications:
* Projects that previously relied on "rhino.jar" may fail to build if they relied on tools or XML -- they will need to either switch to the modules or use "rhino-all.jar". We can hope that most projects will fail quickly on build and only require a dependency change. Projects bigger than Rhino have done this before.
* Modular projects may need to make the same build changes but will still keep working
* Command-line tools based on the all-in-one JAR will need to change the JAR name that they use.

Proposal 2:

1) Change the module name of "rhino-runtime" but nothing else

| Directory | Module | JAR Name | Contents |
| -- | -- | -- | -- |
| rhino-runtime | org.mozilla.rhino | rhino-runtime.jar | Core Classes |
...
| rhino | N/A | rhino.jar | All-in-one JAR |

Implications:
* Modular applications will have to change their build to select "rhino-runtime" instead of "rhino".
* Non-modular applications can continue to operate without change, but won't get the advantage of the modular JARs, and is that something that we really want in the long run?
* The "rhino-runtime" module name doesn't match the JAR name.

Proposal 3:

1) Add "automatic module" support to the all-in-one JAR so that it exports the names of all the modules and packages that it includes.

| Directory | Module | JAR Name | Contents |
| -- | -- | -- | -- |
| rhino-runtime | org.mozilla.rhino-runtime | rhino-runtime.jar | Core Classes |
...
| rhino | org.mozilla.rhino, exports all exported packages | rhino.jar | All-in-one JAR |

Implications:
* Modular applications that previously used rhino.jar need not change, but they *should*.
* Non-modular applications that previously used rhino.jar need not change
* Modular applications that include rhino.jar along with any of the other four modular JARs will break in strange ways

**Comment by carlosame** [comment]
Thanks for reacting so fast, Greg. I believe that proposal 1 is the most appropriate because people using automated builds (Maven, Gradle, etc.) do not need to change anything if they are using the current `org.mozilla.rhino` module name, unless they are using something from tools (most embedders don't).

Regarding proposal 3, any package which is (directly) exported by two different modules (`org.mozilla.rhino.runtime` and `org.mozilla.rhino` in this case) breaks the rules of modularity and is a disaster waiting to happen (imagine a JVM which includes multiple dependencies, some of them using `org.mozilla.rhino.runtime` while others use `org.mozilla.rhino`). So I'd discard proposal 3 and keep a `rhino-all.jar` which lacks module support.

**Comment by gbrail** [comment]
Thanks! I just made a huge change, and I have some time the next week or so
to work on Rhino stuff so I want to move fast while I can.

I like Option 1 the best myself as well. I'm going to wait a day or two to
see if anyone else feels strongly and then do this so that I can get past
merging things with all the renamings...

**Comment by p-bakker** [comment]
Proposal 1 looks fine to me as well.

Only thing I wonder about is the naming of the 'all' jar. Most project use either fat, uber or all-in-one. 

Maybe call it rhino-all-in-one, instead of just rhino-all?

**Comment by carlosame** [comment]
> Only thing I wonder about is the naming of the 'all' jar. Most project use either fat, uber or all-in-one.
> 
> Maybe call it rhino-all-in-one, instead of just rhino-all?

The names 'uber-jar' and 'fat-jar' are generally used when the jar includes all of the packages of a project _as well as their dependencies_. `rhino-all.jar` would not embed any dependency, so calling it 'uber', 'fat' or 'all-in-one' seems a bit overkill to me.

**Comment by rbri** [comment]
Did some experiments today. Looks like i can easily apply the changes to my fork and build a correct core-js for htmlunit. Therefore I'm fine with all your plans...
