### ISSUE TITLE
1.7.15: NativeRegexp calls ScriptRuntime.addInstructionCount when instruction counting is not enabled

### ISSUE THREAD

**Issue by rde2** [mozilla/rhino#1497]
org.mozilla.javascript.regexp.NativeRegExp at line 1891 does:

ScriptRuntime.addInstructionCount(cx, 5);

this will trigger a call to observeInstructionCount even if instructionThreshold is 0.  

To reproduce, create a Context class which overrides observeInstructionCount and use regexps.  observeInstructionCount  will be called even though setInstructionObserverThreshold has not been called

**Comment by rbri** [comment]
@rde2 thanks for that report. Please have a look at the provided PR - hopefully you agree with the test case (and the fix).
