### ISSUE TITLE
Rhino API decodes a script using `rhino.decompileScript(encryptDex, 0);` and displays:`function () {[native code, arity=0]}` What is the reason?

### ISSUE THREAD

**Issue by yuuu-2023** [mozilla/rhino#1499]
public void decryptDex() {
        try {
            Context rhino = Context.enter();
            rhino.setOptimizationLevel(-1);
            Scriptable scope = rhino.initStandardObjects();
            
            File cacheDir = getCacheDir();
            String dexPath = cacheDir + "/classes2.dex";
            print("dexPath => " + dexPath);
            Script encryptDex = loadDex(getApplicationContext(), dexPath);

            String decompileScript = rhino.decompileScript(encryptDex,0);
            print("decompileScript =>" + decompileScript);
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            Context.exit();
        }
    }
    public Script loadDex(android.content.Context context, String dexPath){
        try {

            DexClassLoader dexClassLoader = new DexClassLoader(dexPath, null, null, getClass().getClassLoader());
            Class<?> loadClass = dexClassLoader.loadClass("org.autojs.autojspro.gen._fa44d3cc352f9070d69d15a779b7f5b2");

            Script instance = (Script) loadClass.newInstance();
            print("loadClass => " + instance);
            return instance;
        }catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }

![image](https://github.com/mozilla/rhino/assets/117560070/1d4ac87d-2978-40c0-960c-5e9e013f98a6)

**Comment by p-bakker** [comment]
Your examples seem related to using Rhino on Android, using autojs.

You filed this 'issue' with the Rhino project. As we do not know anything about the autojs project, we cannot answer your question. 

If you think there's an issue or have a Rhino related question, please provide a stand-alone Rhino-based code sample demonstrating the issue you're experiencing

For now I'm closing this issue, feel free to reopen with a better example
