### ISSUE TITLE
Add support for typed arrays

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#151]
The branch "greg-typed-arrays" has the typed array code from the Apigee GitHub fork in it, with the addition of support for the "List" interface for each array type.

https://github.com/mozilla/rhino/tree/greg-typed-arrays

I'm planning to merge this in the next week. Typed array support is only available when the language version is set to 1.8 or higher.

**Comment by gbrail** [comment]
Closed and merged in to master for 1.8.0.

**Comment by d10** [comment]
:+1:
