### ISSUE TITLE
mozilla.javascript.EcmaError: ReferenceError: "java" is not defined. (internal#105)

### ISSUE THREAD

**Issue by janakmulani** [mozilla/rhino#1513]
Getting the above error while trying to evaluate a PAC proxy script which uses functions like isInNet, dnsResolve etc. which in turn use java.net.InetAddress methods. For example:

`
function dnsResolve(host) {
    return java.net.InetAddress.getByName(host).getHostAddress() + "";
}

function myIpAddress() {
    return java.net.InetAddress.getLocalHost().getHostAddress() + "";
}
`

Also, when using Rhino to process the PAC proxy script lot of heap memory is used leading to  “GC overheated”.

**Comment by p-bakker** [comment]
With regards to the `"java" not defined` error: without knowing how you use Rhino, there's not much we can help you with

With regards to the PAC proxy scripts using a lot of heap: again, without specifics not much we can help you with. 

Closing this case as not actionable, feel free to reopen with detailed info and reproducible issues
