### ISSUE TITLE
None of the TypeScript "base" libraries can be loaded 

### ISSUE THREAD

**Issue by nmondal** [mozilla/rhino#1555]
This came because we were trying to check if we can use Rhino to ensure we have a TypeScript Scripting Engine. This in principle is not that hard - 

1. Get typescript code from : https://cdnjs.com/libraries/typescript 
2. And then load it in Rhino 
3. and eval with the typescript object in Rhnio to trans compile to JS, and then 
4. load the JS again in Rhino.

The issue is, latest Rhino fails to load *ANY* version of this typescript library.
This is a very time consuming process - the latest one ( 5.5.4 ) fails with a variant of for() loop - 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

it is unable to parse it, 

And the previous fails to various issues, some parses it proper, but fails on execution.
What should we do to fix this? 
Is there something I am missing entirely? It probably is not much to do with JS versions, because GRAAL VM and GRAALJS also fails, as far as I have tested.

**Comment by p-bakker** [comment]
Without any runnable example at all or more specifically a focused example of exactly what goes wrong where, I doubt you'll get much response on your 'bug' report....

**Comment by p-bakker** [comment]
An going to close this as there's no actionable info for us atm (broken testcase, some runnable Java code demonstrating the issue, ...)

Feel free to reopen with more information

On a last note: if loading of the typescript library fails, specifically on a for-of loop, I wonder which EcmaScript version the library targets. Rhino isn't 100% EcmaScript-compatible, so you might have to pull the library through Babel first
