### ISSUE TITLE
Several line break related issues when running the test suite on windows

### ISSUE THREAD

**Issue by rbri** [mozilla/rhino#1584]
For other reasons i do most of the work on this lib on windows. There are several tests that failing due to problems with line breaks.

* tests\test262\test\built-ins\Function\prototype\toString\line-terminator-normalisation-LF.js
this fails because the checkout created cr lf line as line terminator and the test expects the original lf to be preserved

We can add this line to the .gitattributes in folder tests\test262

    line-terminator-normalisation-LF.js text eol=lf

but i'm not sure if this is the right way to do that

@p-bakker @gbrail what do you think?

**Comment by p-bakker** [comment]
Great! See #919 and #918 for some, possibly related, prior art

**Comment by rbri** [comment]
For me this is  done. Will open a new one if something more comes up
