### ISSUE TITLE
Assignment operators with a function expression should give name to the function

### ISSUE THREAD

**Issue by andreabergia** [mozilla/rhino#1599]
When assigning a variable to an anonymous function, that function should get its name from the variable. Example:

```js
test = function() {}
test.name
```

should be `test`. This should work with normal functions and with lambda functions (and with classes, one day).
It should also work with operators such as `||=` or `&&|=`.

**Comment by p-bakker** [comment]
Think this one duplicates what is already in #1297, which has more details to it. Ok with me closing this one?

**Comment by andreabergia** [comment]
> Think this one duplicates what is already in #1297, which has more details to it. Ok with me closing this one?

Sure, go ahead

**Comment by p-bakker** [comment]
Duplicates #1297
