### ISSUE TITLE
Getting test results from failed CI tests

### ISSUE THREAD

**Issue by tonygermano** [mozilla/rhino#1606]
### Discussed in https://github.com/mozilla/rhino/discussions/1602

<div type='discussions-op-text'>

<sup>Originally posted by **tonygermano** August 30, 2024</sup>
I can open an issue if I need to, but I wanted to get some feedback first. When I first opened https://github.com/mozilla/rhino/pull/1594, the automated build failed. The run results are at https://github.com/mozilla/rhino/actions/runs/10622780835/job/29447815131. Near the end of the log after it failed, it says:
> There were failing tests. See the report at: file:///home/runner/work/rhino/rhino/tests/build/reports/tests/test/index.html

Is there some way that I'm missing to view that report or does the github action need to be adjusted to allow those test results to be viewable?</div>

**Comment by tonygermano** [comment]
It appears that the Upload Results step doesn't run when the tests do not complete successfully.

**Comment by p-bakker** [comment]
Think this is solved by #1646, so closing
