### ISSUE TITLE
Issue comparing bigint to string

### ISSUE THREAD

**Issue by tonygermano** [mozilla/rhino#1608]
```javascript
9007199254740992n < "9007199254740993"
```
Expected: true
Actual: false

**Comment by tonygermano** [comment]
I have a PR coming for this, and I found there is a test262 test which already covers it.

**Comment by rbri** [comment]
@p-bakker have added some tests in #1681 but it looks like this is already solved on the head. I think we can close this.

**Comment by p-bakker** [comment]
Closed as already fixed
