### ISSUE TITLE
Support ES6 additions to String

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#163]
These include:

startsWith
endsWith
repeat
codePointAt
normalize
includes

**Comment by eshepelyuk** [comment]
@gbrail I've started to work on the issue, could you please assign it to me ?

**Comment by tntim96** [comment]
Will there be any AST changes with the implementation?

**Comment by eshepelyuk** [comment]
Should not be any. Just injecting method to `NativeString` class.

**Comment by gbrail** [comment]
Officially marking you as the owner seems to be something that I need help
from the Mozilla GitHub team for because you (and a lot of people,
actually) are not part of the project.

In the meantime, we'll have to work with comments...


On Sun, Apr 26, 2015 at 10:47 PM, Evgeny Shepelyuk <notifications@github.com
> wrote:

> @gbrail <https://github.com/gbrail> I've started to work on the issue,
> could you please assign it to me ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/163#issuecomment-96513792>.
>



-- 
*greg brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail>

**Comment by eshepelyuk** [comment]
Doest GitHub allow only *colalborators*  to be assigned to an issue ?

**Comment by gbrail** [comment]
Yes, please keep working on it -- I need to find out how to add collaborators in the "Mozilla" org.
