### ISSUE TITLE
Use enums more freely

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#1639]
We have a lot of places, especially in parser-related things, where we have a pattern of integer identifiers that have to remain unique, like this:

https://github.com/mozilla/rhino/blob/b08de525f3daefa9800a509a5e5a5b27848da7ff/rhino/src/main/java/org/mozilla/javascript/Token.java#L32

Now that people are adding lots of new language features (thanks!) this is becoming a maintenance nightmare, because all it takes is two or three people modifying the same list of integers to create a merge conflict.

Fortunately, since the 1990s Java has added proper enums. 

It would be wonderful if someone could take on the task of replacing these enum-like structures in Rhino with proper Java enums.

**Comment by p-bakker** [comment]
This would constitute a breaking change, for people that interact with the parser directly, no?

Do note that roughly, these are the current language features that Rhino doesn't yet support that involve new syntax: 
- rest & spread #1217, #968, #756, #652 (some rest support introduced in #1451)
- modules #945 
- class #835
- async & await #395 
- optional chaining operator #937 (PR in progress)
- nullish assignment operator #936
- super (in Objects) #1299 

And stuff in the TC39 proposals pipeline (stage [2.7](https://github.com/tc39/proposals?tab=readme-ov-file#stage-27) & [3)](https://github.com/tc39/proposals?tab=readme-ov-file#stage-3):
- [decorators](https://github.com/tc39/proposal-decorators)

All this to say: yes we had quite a few language features added recently with super being added for some additional operators, but likely going forward well have less conflicting PRs. Not saying we shouldn't do this, but given this resulting in a breaking change, I think we should consider not doing this before a V2.x.x

**Comment by andreabergia** [comment]
IMHO the benefits would overweight the cost. If someone has opened PRs yes, it might take a bit of refactoring, but the maintenance of some of these existing patterns (for example, the `Token`, which I've had to touch for some recent PR) is a lot worse.

**Comment by rbri** [comment]
fine for me, please do it

**Comment by rPraml** [comment]
I've tried to do this, but I see serveral show stoppers:
- There is `Token` and there is `ICode` - it would be necessary to keep all codes either in one enum or do a huge refactoring
- There is `currentFlaggedToken` which has additional bits and would require refactoring
- There is `https://github.com/mozilla/rhino/blob/master/rhino/src/main/java/org/mozilla/javascript/ast/Scope.java#L118C15-L118C22` what I do not understand: Scope.type is converted in Scope.position (I *think* this could be a bug)

Here is the start of the PR https://github.com/mozilla/rhino/pull/1647 if really someone want to continue

**Comment by rbri** [comment]
#1648 is merged, i think we can live with the current solution for a while

**Comment by p-bakker** [comment]
Closed by #1648
