### ISSUE TITLE
Support ES6 additions to Array

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#164]
These include:

fill
keys
values
entries

(find and findIndex are already implemented)

**Comment by rbri** [comment]
Seems to be done, i suggest to close this.

**Comment by gbrail** [comment]
Those are done. But although I didn't list them all those years ago, we still don't have:

from
of
and copyWithin

**Comment by p-bakker** [comment]
Seems all taken care of, except for new Array methods in ES2019 (flat & flatMap), for which we have https://github.com/mozilla/rhino/issues/949 and https://github.com/mozilla/rhino/issues/948, so closing this issue
