### ISSUE TITLE
getSourcePositionFromJavaStack cannot perform well on Android system

### ISSUE THREAD

**Issue by anonyein** [mozilla/rhino#1680]
https://github.com/mozilla/rhino/commit/f3f1b3f93833f477d59043e26a0bd1ef59a90163#diff-d0e61fbbe651a547bf81371014f77ac41baa787abac5f56122e9b5e791be91dcR2579
https://github.com/requirejs/r.js

```
File rJs = new File(rhinoJsDir, "r.js");
if (rJs.exists() && rJs.isFile()) {
    try (FileInputStream inputStream = new FileInputStream(rJs)) {
        InputStreamReader envReader = new InputStreamReader(inputStream);
        cx.evaluateReader(scope, envReader,
                "r.js", 1, null);
    } catch (RhinoException re) {
    }
}
```
cannot be evaluated after this commit with desugar_jdk_libs on Android system.
Maybe desugar_jdk_libs changes "java.util.Optional" to "$j.util.Optional".
I have reverted this commit.

**Comment by rPraml** [comment]
Sorry for this. I throughd, android uses Interpreter mode only and we should not get there. Can you (or anyone) tell me, how to run tests on android?

**Comment by rbri** [comment]
if i got @anonyein right this is not a runtime issue it happens at build time - @anonyein correct?

**Comment by anonyein** [comment]
@rbri I found this not the problem of Android API version and desugar_jdk_libs. This also happens on Android 11. I will decompile  "Context" class.

**Comment by rbri** [comment]
looks like StackWalker was added at API Level 34 / Android 14 (https://developer.android.com/reference/java/lang/StackWalker)

**Comment by anonyein** [comment]
> looks like StackWalker was added at API Level 34 / Android 14 (https://developer.android.com/reference/java/lang/StackWalker)

All right, that's too high

**Comment by p-bakker** [comment]
> Can you (or anyone) tell me, how to run tests on android?

This has been a pending question without a cheat answer for quite a while: #1152

**Comment by gbrail** [comment]
It looks like we could address this by replacing the StackWalker with the old "new Throwable().getStackTrace()" technique. That would prevent any Android problems (as shown by the fact that we had to add an annotation here for ErrorProne.

@rbri do you recall why we changed this and whether it'd make sense to change it back?

**Comment by rbri** [comment]
my memory says it was done to modernize the code based on jdk11 but i was not the author.
For core-js i had to revert that to be jdk8 and android compatible
