### ISSUE TITLE
ScriptRuntime.initStandardObjects should be factored into sections, particularly lazilyNames

### ISSUE THREAD

**Issue by ziesemer** [mozilla/rhino#170]
Attempting to use Rhino to evaluate JavaScript expressions.  These expressions are not necessarily trusted, and have no reason to directly callback to Java, unless specific functionality is explicitly exported into the JavaScript context.

Calling Context.setClassShutter(...) is a start; however, the "lazilyNames" used by ScriptRuntime.initStandardObjects (called by Context.initStandardObjects(...)) still inserts references to org.mozilla.javascript.NativeJavaTopPackage ("Packages", "java", "javax", "org", "com", "edu", "net", "getClass"), org.mozilla.javascript.JavaAdapter ("JavaAdapter"), and org.mozilla.javascript.ImporterTopLevel ("JavaImporter").  These are not necessary for this and other use-cases, and there should be a method to make these optional.

It is not currently possible (without mass copy & paste) to avoid these declarations without loosing all the other core functionality provided by the initStandardObjects method, particularly all the Native*.init(...) calls for NativeObject, NativeError, NativeGlobal, NativeArray, NativeString, etc.

(This is a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=468385 from 2008-12-07 .  See also: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6782031 .)

Daniel Friesen had submitted a patch against the Mozilla bug in 2009:

> Since the primary issue appears to be the LiveConnect classes, what about splitting initStandardObjects into initSafeStandardObjects which does everything in initStandardObjects except initialize the LiveConnect stuff, and initStandardObjects which wraps around it and adds the LiveConnect stuff. Then secure environments can just use initSafeStandardObjects instead.

Can this please be included in 1.8 (or even a 1.7R6, if one ever comes about)?

**Comment by gbrail** [comment]
That makes sense to me and it'd be a good thing to have in a number of contexts.

It wasn't too difficult to make a quick patch. Can you take a look at the pull request and see if it makes sense to you (and better yet, if it works in your context?)

https://github.com/mozilla/rhino/pull/171

**Comment by ziesemer** [comment]
This looks perfect, and would be much appreciated - thanks!

**Comment by gbrail** [comment]
Closed and shipped in 1.7.6.
