### ISSUE TITLE
"Cannot overwrite existing ClassShutter object" on a new Context

### ISSUE THREAD

**Issue by NGSpace** [mozilla/rhino#1710]
doing

```java
Context cx = Context.enter();
cx.setClassShutter(clazz->false);
```

Throws "Cannot overwrite existing ClassShutter object"

**Comment by rPraml** [comment]
Warning: Do not rely on the false security, that classShutter etc. may provide. See #1045 #861 
I've tried a lot and either liveConnect was useless or we found ways to bypass the "rules".

ClassShutter is easy: `new java.util.HashMap().getClassLoader()` and then load class you want or even define new class from bytecode level.

**Comment by NGSpace** [comment]
Thank you for your reply, is there a way to completely disable liveConnect or something more secure than ClassShutter?

**Comment by rPraml** [comment]
you can use initSafeStandardObjects, but then there are still ways, where a user can abuse the system. E.g. with complex regexps or endless loops.

**Comment by rPraml** [comment]
You can try this
```java
BaseFunction myFunc = new BaseFunction() {
    public Object call(Context _cx, Scriptable _scope, Scriptable _thisObj, Object[] _args) {
        // your code goes here
    }
}
scope.put("myFunc", scope, myFunc)
```
or `ScriptableObject.defineProperty` if you just want a getter/setter property

**Comment by gbrail** [comment]
Also, the LambdaFunction class is designed for exactly this -- you create
an instance of this class and pass it your lambda and you have a legal
JavaScript function.

**Comment by NGSpace** [comment]
Thank you for your help!
