### ISSUE TITLE
"intercept" java function calls?

### ISSUE THREAD

**Issue by NGSpace** [mozilla/rhino#1725]
I have a Java Object which I inject into the JS context, in that object, 3 layers deep there is a function which I want to overwrite it's result, unfortunately I am unable to modify the Object itself, redesign it or extend it.

Is there a way to intercept the result of that function?

**Comment by rPraml** [comment]
You can use the same strategy as here: https://github.com/mozilla/rhino/issues/1727

Inject a proxy class that does change the return value

```java
class MyClassAdapter {
        MyClass delegate;
       
        int myFunc() {
            return delegate.myFunc() + 42;
        }
    }
```

 or return a custom function in "get":

``´java
public Object get(String name, Scriptable start) {
    if (name.equals("myFunc") {
       Function f = super.get(name, start); // this is most likely a Function or Callable
       // create new function that intercepts calls to this function
       return new Function() {
           public Object call(Context cx, Scriptable scope, Scriptable thisObj, Object[] args) {
               return f.call(cx,scope,thisObj,args) + 42;
           }
       }
    }
    return super.get(name, start)
  }
```

but why do you want to do that? Can't you easily change your script?
If not, the easiest way coud be to search & replace in the script (depending on use case not robust enough)

**Comment by NGSpace** [comment]
Sorry for the late reply, I already solved the issue but thank you!
