### ISSUE TITLE
Change the way Rhino handles a certain Java Class?

### ISSUE THREAD

**Issue by NGSpace** [mozilla/rhino#1727]
There is a certain class which is passed over to JavaScript and I'd like to change the behavior of the class when it is used by JavaScript (ex. if JS wants to read variable X, it will return variable Y instead)

Is there a way to do this globally (or at a scope level)?

**Comment by rPraml** [comment]
You can set/implement your own wrapfactory, which wraps java objects. When wrapping an instance of your class, you can either wrap some kind of java proxy object, that intercepts each call or also a subclass of NativeJavaObject, that does the conversion

**Comment by NGSpace** [comment]
May I ask how to implement said wrapfactory?

**Comment by rPraml** [comment]
Create a subclass and override wrapAsJavaObject: https://github.com/mozilla/rhino/blob/master/rhino/src/main/java/org/mozilla/javascript/WrapFactory.java#L114

Method 1 (with proxy-adapter):
```java
    public Scriptable wrapAsJavaObject(
            Context cx, Scriptable scope, Object javaObject, Class<?> staticType) {
        if (javaObject instanceof MyClass) {
            javaObject = new MyClassAdapter((MyClass) javaObject)
        }
        return super.wrapAsJavaObject(cx, scope, javaObject, staticType);
    }

    class MyClassAdapter {
        MyClass delegate;
       
        void callX() {
            delegate.callY();
        }
    }
```

Method 2 with own scriptable:
```java
    public Scriptable wrapAsJavaObject(
            Context cx, Scriptable scope, Object javaObject, Class<?> staticType) {
        if (javaObject instanceof MyClass) {
            return new MyNativeJavaObject(scope, javaObject, staticType);
        }
        return super.wrapAsJavaObject(cx, scope, javaObject, staticType);
    }

class MyNativeJavaObject extends NativeJavaObject {
// override get/has etc.

  public Object get(String name, Scriptable start) {
    if (name.equals("callX") {
       return super.get("callY", start)
    }
    return super.get(name, start)
  }
}
