### ISSUE TITLE
Cannot define an object literal with a getter for a symbol property

### ISSUE THREAD

**Issue by andreabergia** [mozilla/rhino#1729]
This is not allowed by rhino, but it should be:

```js
obj = { get [Symbol.match]() {} }
```

The error printed is `TypeError: The object is not a string`, but that's confusing. The reason is that there is a code path where the symbol is casted to a string, which does not work.

**Comment by p-bakker** [comment]
Think this is a dup of #1614

**Comment by andreabergia** [comment]
@p-bakker you're right, it is!
