### ISSUE TITLE
Clean git rhino project

### ISSUE THREAD

**Issue by asashour** [mozilla/rhino#192]
Hi all,

There are three points that are encountered:

1. 'head' tag

    This causes the error `refname 'HEAD' is ambiguous` whenever you type `git status` (or other commads)

    This is caused by a tag named 'HEAD' and it can be fixed by:
        `git tag -d head`
        `git push origin :refs/tags/head`

2. 'done' tag

    This doesn't mean something meaningful.

    This can be fixed by:
        `git tag -d done`
        `git push origin :refs/tags/done`

3. There is a branch called 'origin', which is confusing with the 'origin' remote.

    This can be deleted by something like:

        git push origin --delete origin

I tried to post a pull request, but it is doesn't recognize any of those mentioned points.

Thanks,

**Comment by gbrail** [comment]
Simple enough. Thanks!
