### ISSUE TITLE
Publish Snapshots To A Maven Repository

### ISSUE THREAD

**Issue by tntim96** [mozilla/rhino#197]
It would be useful to regularly publish snapshots to a public maven repository (e.g. Sonatype).

This could either be done automatically on every build (probably easiest) or manually at various milestones.

**Comment by BigBoneDaddy** [comment]
@tntim96 Are you volunteering to do?

**Comment by gbrail** [comment]
I fought with Gradle for about half a day and gave up. The task would be to
update the build.gradle to publish to maven, preferably with the ability to
sign the JAR using GPG. It was surprisingly hard. But if anyone has some
experience then that would help.

On Wed, Jul 1, 2015 at 4:59 PM, BigBoneDaddy <notifications@github.com>
wrote:

> @tntim96 <https://github.com/tntim96> Are you volunteering to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/197#issuecomment-117856546>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by eshepelyuk** [comment]
@gbrail what is the exact problem with build scripts ?
It already has support for publishing to `Maven` compatible repositories, and the procedure is described at project `README`.
I've tried it with local `Artifactory` and both SNAPSHOT and RELEASE were working OK.
So, unless Sonatype has some other way of processing publishing requests - all should work now.

**Comment by eshepelyuk** [comment]
Hello @gbrail

Is there still problems with publishing artifacs from Gradle ?
If yes - which ones, so maybe I could help on fixing them.

**Comment by tntim96** [comment]
Seems to be publishing OK to https://oss.sonatype.org/content/repositories/snapshots/org/mozilla/rhino/1.7.8-SNAPSHOT/

**Comment by gbrail** [comment]
This is being done now by the ci server. So I am going to close this...
