### ISSUE TITLE
Consider removal of FEATURE_V8_EXTENSIONS flag

### ISSUE THREAD

**Issue by eshepelyuk** [mozilla/rhino#199]
With introduction of `VERSION_ES6` do we still need `FEATURE_V8_EXTENSIONS` flag ?
I suggest to remove it and replace with analysis of language version only.
Right now this flag is used only for declaring availability of `Typed Arrays` and since those arrays are part of `ES6` it seems natural to declare them available when version >= `ES6`.

**Comment by gbrail** [comment]
Yeah, but the problem is that versions of V8 without any other "ES6" stuff
have typed arrays, and lots of Node code, in particular, depends on ES6. So
if we change the typed arrays to only work >= ES6 now, we'll break someone.
So I'd like to leave it the way it is for now.

On Wed, Jun 17, 2015 at 12:09 AM, Evgeny Shepelyuk <notifications@github.com
> wrote:

> With introduction of VERSION_ES6 do we still need FEATURE_V8_EXTENSIONS
> flag ?
> I suggest to remove it and replace with analysis of language version only.
> Right now this flag is used only for declaring availability of Typed
> Arrays and since those arrays are part of ES6 it seems natural to declare
> them available when version >= ES6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/199>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by gbrail** [comment]
And I meant that lots of Node code that doesn't specify "--harmony" depends
on typed arrays anyway.

On Wed, Jun 17, 2015 at 12:09 AM, Evgeny Shepelyuk <notifications@github.com
> wrote:

> With introduction of VERSION_ES6 do we still need FEATURE_V8_EXTENSIONS
> flag ?
> I suggest to remove it and replace with analysis of language version only.
> Right now this flag is used only for declaring availability of Typed
> Arrays and since those arrays are part of ES6 it seems natural to declare
> them available when version >= ES6.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/199>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by eshepelyuk** [comment]
I am not sure how NodeJS and its flag `--harmony` relates to Rhino languge version.
But to reduce ambiguity in Rhino code maybe let's just rename version from 1.8 to ES6 and remove FEATURE_V8_EXTENSIONS flag. 
So this can be planned for version 1.7.8 or even later with clean announcement that those flag and version will be removed in favor of ES6.

Again, I am not understanding relation between NodeJS and Rhino so maybe I miss the whole point about those flags.
