### ISSUE TITLE
Generated maven source file "rhino-1.7R3-sources.jar" does not contain org.mozilla.javascript.tools.* and others

### ISSUE THREAD

**Issue by iron9light** [mozilla/rhino#20]
http://repo1.maven.org/maven2/org/mozilla/rhino/1.7R3/rhino-1.7R3-sources.jar

and

http://repo1.maven.org/maven2/org/mozilla/rhino/1.7R3/rhino-1.7R3-javadoc.jar

**Comment by eshepelyuk** [comment]
This will be resolved after approval of #179

**Comment by p-bakker** [comment]
Closing this as #179 has long been approved and merged and the latest Rhino jars on maven don't seem to have this issue
