### ISSUE TITLE
CompilerEnvirons.setOptimizationLevel(-1) not works

### ISSUE THREAD

**Issue by iron9light** [mozilla/rhino#21]
Still get "generated bytecode for method exceeds 64K limit"

But Context.setOptimizationLevel(-1) works fine.

Rhino 1.7R3
Oracle JDK 1.7.0_01

**Comment by p-bakker** [comment]
Closing this issue: It's very old and doesn't contain a reproducible example.

Please reopen with an example if this is still a problem. 

Also see https://github.com/mozilla/rhino/issues/286, which might be related
