### ISSUE TITLE
Cleanup VMBridge ?

### ISSUE THREAD

**Issue by hrj** [mozilla/rhino#218]
From Rhino 1.7.6 onwards, Java 5 and below are not supported.

Hence, `org/mozilla/javascript/jdk13/VMBridge_jdk13`can be removed and `org/mozilla/javascript/jdk15/VMBridge_jdk15` can be folded into the base `VMBridge`. 

Going further, and to be more aggressive with the cleanup, `VMBridge` itself could be removed because there is nothing left to bridge as of now, as far as I can see.

If there's a green signal for either of the above, I volunteer to submit a PR.

**Comment by gbrail** [comment]
We might want to have a "VMBridge" concept in the future. For instance, we have an open PR that makes it easier to use default parameters in Java 8, but that depends on some Java 8-specific APIs. Plus, we might be able to use "InvokeDynamic" in code generation in some cases in the future.

However, you are correct that we're not going to go back and support Java 1.5 or before.

So I think that we should keep the "VMBridge" concept but in the current implementation, all of the existing implementations can be merged into the base class.
