### ISSUE TITLE
 Add more tests for arrow functions

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#220]
For instance, we could add tests from the V8 test suite.

**Comment by sainaen** [comment]
When I was trying to update  @tuchida's arrow functions implementation to make it more spec-compliant, I wrote couple of tests using my understanding of spec plus V8's and SpiderMonkey's test suites as sources, maybe some of them could be useful: https://github.com/sainaen/rhino/blob/arrow-functions/testsrc/jstests/harmony/arrow-functions.js

Also, there are a lot of tests for arrow functions in test262 suite.

**Comment by tntim96** [comment]
Is there some reason why the arrow function tests (and many others) from test262 are not enabled in [test262.properties](https://github.com/mozilla/rhino/blob/master/testsrc/test262.properties)?

**Comment by gbrail** [comment]
The arrow function implementation from @tuchida is quite an old PR and pre-dates the addition of test262 tests. We just need to enable those tests and then address any failures.

As for the 262 test suite in general, the current approach is to enable the tests as they pass, so that the main Rhino build stays clean. That way it is much easier to identify regressions.

I also have a separate CI job that runs test262 in a more vanilla way, and runs all the tests. However that just broke so let me look at it...

**Comment by gbrail** [comment]
Merged the PR. Thanks!
