### ISSUE TITLE
org.mozilla.javascript.JavaScriptException Error: unknown environment

### ISSUE THREAD

**Issue by oswetto** [mozilla/rhino#223]
My call:
String uri = "http://oasjs.kataweb.it/adagiojs/gele.js" 
Context ctx = ContextFactory.getGlobal().enterContext();
Scriptable scope = ctx.initStandardObjects();
ctx.evaluateString(scope, source, uri, 1, null);

org.mozilla.javascript.JavaScriptException: 
Error: unknown environment (http://oasjs.kataweb.it/adagiojs/gele.js#84)
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
at script(http://oasjs.kataweb.it/adagiojs/gele.js:83)
at script(http://oasjs.kataweb.it/adagiojs/gele.js:41)
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
at org.mozilla.javascript.Context.evaluateString(Context.java:1219)

**Comment by gbrail** [comment]
Normally I pass the source code (aka a String that represents the
JavaScript that I want to run) as the second parameter to "evaluateString."
Alternately, there is a version of that function that takes a Reader. Are
you expecting something else, like for it to use HTTP to read your source
code and evaluate it?

On Mon, Jul 27, 2015 at 7:41 AM, Ivan Di Francesco <notifications@github.com
> wrote:

> My call:
> String uri = "http://oasjs.kataweb.it/adagiojs/gele.js"
> Context ctx = ContextFactory.getGlobal().enterContext();
> Scriptable scope = ctx.initStandardObjects();
> ctx.evaluateString(scope, source, uri, 1, null);
>
> org.mozilla.javascript.JavaScriptException:
> Error: unknown environment (http://oasjs.kataweb.it/adagiojs/gele.js#84)
> at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
> at script(http://oasjs.kataweb.it/adagiojs/gele.js:83)
> at script(http://oasjs.kataweb.it/adagiojs/gele.js:41)
> at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
> at
> org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
> at
> org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
> at org.mozilla.javascript.Context.evaluateString(Context.java:1219)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/223>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>
<http://iloveapis.com/>

**Comment by sainaen** [comment]
Well, the error 
> Error: unknown environment (http://oasjs.kataweb.it/adagiojs/gele.js#84)

tells what and where exactly went wrong: that script tries to guess which environment it's being run in: vanilla browser, something with AMD exports (with `define.amd`) or something that supports CommonJS-like (`module.exports`), but there's no such things when you run scipt inside Rhino like that, so script fails.

What you could do to satisfy this check is define `window` global variable in the context, but after checking the environment, it tries to work with browser specific stuff, like checking `document.cookie` and using `document.write`, so without those it probably will not work as Rhino doesn't provide them.
