### ISSUE TITLE
Failure propagation of Ant target "junit"

### ISSUE THREAD

**Issue by hartwork** [mozilla/rhino#226]
Hi!

When calling target `junit`, failure is not propagated: the ant process returns code 0 despite failure.
To my understanding that target is intended to work with current use by target `junit-coveragereport`

```
  <target depends="junit" name="junit-coveragereport" >
    [..]
    <fail message="JUnit test(s) failed" if="junitFailed" ></fail>
  </target>
```

and is suppressing failure propagation by design in a way.

To have both worlds together, I would like to propose adding a "proxy target" `junit-propagate` or so to `testsrc/build.xml` like

```
+  <target depends="junit" name="junit-propagate" >
+    <fail message="JUnit test(s) failed" if="junitFailed" ></fail>
+  </target>
```

and have the master `build.xml` call that, instead, i.e.

```
   <target depends="compile" name="junit" >
-    <ant antfile="testsrc/build.xml" target="junit" ></ant>
+    <ant antfile="testsrc/build.xml" target="junit-propagate" ></ant>
   </target>
```

It would
- keep the current interface all working
- no longer have ant return 0 despite failures

What do you think?

**Comment by gbrail** [comment]
We're trying to leave Ant behind and use Gradle. Some day soon we'll take the ant targets out.

Can you give it a try using Gradle?

**Comment by eshepelyuk** [comment]
Btw, test failures are also being ignored in `Gradle` build script.
See this flag
```
ignoreFailures = true
```

**Comment by hartwork** [comment]
Hello again,

> We're trying to leave Ant behind and use Gradle. Some day soon we'll take the ant targets out.
> Can you give it a try using Gradle?

My Linux distro does not have an official package for Gradle, yet. So not easily.

> Check the flag `ignoreFailures = true`

I will keep it in mind, thanks!

**Comment by eshepelyuk** [comment]
You don't need to install `Gradle` dustrubution on your OS. Thanks to (Gradle wrapper)  [https://docs.gradle.org/current/userguide/gradle_wrapper.html]
Please check `Rhino` readme for a example if running `Gradle` tasks just from `Rhino` source folder.

**Comment by hartwork** [comment]
With `ignoreFailures = false` in `build.gradle`, `gradlew test` did propagate failure and returned code 1. The summary was:
```
8635 tests completed, 2 failed, 2 skipped
:test FAILED
```
Could you flip `ignoreFailures` to `false` or introduce an alternative target that does not ignore failures?
Once the test suite passes, it would allow users to report regressions that depend on differences in execution environment.

**Comment by gbrail** [comment]
The gradle build file in "master" now reflects the build status to the shell -- "ignoreFailures" is disabled. I want to try this for a while before closing this because I'm not sure if it will have any other effects.

**Comment by hartwork** [comment]
Excellent. For the record, the commit is caf3fea08cecb617c70c13ead6934cd5b09a2a84.

**Comment by p-bakker** [comment]
> The gradle build file in "master" now reflects the build status to the shell -- "ignoreFailures" is disabled. I want to try this for a while before closing this because I'm not sure if it will have any other effects.

@gbrail has the trail period expired already? It's been 6 years :-)
