### ISSUE TITLE
Wrong result of minus-minus expression

### ISSUE THREAD

**Issue by itzik-bd** [mozilla/rhino#237]
executing ```x--``` while ```x``` is ```undefined``` results with ```undefined``` instead of ```NaN```.

This happens when the expression is inside a function:
```
(function ()
{
	var v;

	print("v   " + v);
	print("v-- " + v--);
})();
```
running the above program on Rhino outputs:
```
v   undefined
v-- NaN
```
while the expected results is:
```
v   undefined
v-- undefined
```

Run on:
```
Rhino 1.7.6 2015 04 15
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) Client VM (build 25.60-b23, mixed mode)
```

**Comment by tuchida** [comment]
I will write test and send pull request.
https://github.com/mozilla/rhino/compare/master...tuchida:decrement-undefined
