### ISSUE TITLE
cannot run ajax code in rhino 1.7.7

### ISSUE THREAD

**Issue by aurelianr** [mozilla/rhino#257]
Hello 

I successfully integrated the rhino 1.7.7 into an android project and it worked for basic js functions with parameters like following:
			private String javaScriptCode = "function sum(a, b) { return a + b; }";

I tried also a more complicated code with ajax 

function Test() { 
		var request = $.ajax({
		method: "GET",
		crossDomain: true,  
		cache:false,  
		dataType: 'jsonp',
		url: "REST_SERVICE_URL_HERE",      
		contentType: 'application/json'
		});

		request.done(function( data ) {   
		   alert(data); 
		   var el =  document.createElement("h1")
el.id=data;
el.innerHTML = data;
document.body.appendChild(el);
		  });
			
		request.fail(function( jqXHR, textStatus, errorThrown ) {
		  alert(textStatus + ': ' + errorThrown);
		});
}

and I encountered the following error:
12-30 08:13:58.601: E/AndroidRuntime(3640): org.mozilla.javascript.EcmaError: ReferenceError: "$" is not defined. (script#21)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4019)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1917)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1856)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1558)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at script.Test(script:21)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at ro.star.storage.MainActivity$1.run(MainActivity.java:90)
12-30 08:13:58.601: E/AndroidRuntime(3640): 	at java.lang.Thread.run(Thread.java:841)

Would you tell me if is it ajax supported in rhino 1.7.7 or I having a wrong rhino appeal in the following code ?

Context context = Context.enter();
				try {
					context.setOptimizationLevel(-1);

				    ScriptableObject scope = context.initStandardObjects();
				    Scriptable that = context.newObject(scope);
				    
                                 Function fct = context.compileFunction(scope, scriptTest, "script", 20, null);
				    Object result = fct.call(
				            context, scope, that, new Object[] {});//2, 3
				    
				    
				    
				    String rrrr = String.valueOf( Context.jsToJava(result, int.class));
				    
				} finally {
				    Context.exit();
				}

Best Regards,
Aurelian

**Comment by gbrail** [comment]
There's no built in object called "ajax" or "$ajax" in Rhino. Not sure if
you're hoping to include it from some third-party library, but it's not in
Rhino.

On Wed, Dec 30, 2015 at 8:34 AM, aurelianr <notifications@github.com> wrote:

> Hello
>
> I successfully integrated the rhino 177 into an android project and it
> worked for basic js functions with parameters like following:
> private String javaScriptCode = "function sum(a, b) { return a + b; }";
>
> I tried also a more complicated code with ajax
>
> function Test() {
> var request = $ajax({
> method: "GET",
> crossDomain: true,
>
> cache:false,
>
> dataType: 'jsonp',
> url: "REST_SERVICE_URL_HERE",
>
> contentType: 'application/json'
> });
>
>     requestdone(function( data ) {
>        alert(data);
>        var el =  documentcreateElement("h1")
>
> elid=data;
> elinnerHTML = data;
> documentbodyappendChild(el);
> });
>
>     requestfail(function( jqXHR, textStatus, errorThrown ) {
>       alert(textStatus + ': ' + errorThrown);
>     });
>
> }
>
> and I encountered the following error:
> 12-30 08:13:58601: E/AndroidRuntime(3640): orgmozillajavascriptEcmaError:
> ReferenceError: "$" is not defined (script#21)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimeconstructError(ScriptRuntimejava:3951)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimeconstructError(ScriptRuntimejava:3929)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimenotFoundError(ScriptRuntimejava:4019)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimenameOrFunction(ScriptRuntimejava:1917)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimename(ScriptRuntimejava:1856)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptInterpreterinterpretLoop(Interpreterjava:1558)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at scriptTest(script:21)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptInterpreterinterpret(Interpreterjava:815)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptInterpretedFunctioncall(InterpretedFunctionjava:109)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptContextFactorydoTopCall(ContextFactoryjava:393)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptScriptRuntimedoTopCall(ScriptRuntimejava:3282)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> orgmozillajavascriptInterpretedFunctioncall(InterpretedFunctionjava:107)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> rostarstorageMainActivity$1run(MainActivityjava:90)
> 12-30 08:13:58601: E/AndroidRuntime(3640): at
> javalangThreadrun(Threadjava:841)
>
> Would you tell me if is it ajax supported in rhino 177 or I having a wrong
> rhino appeal in the following code ?
>
> Context context = Contextenter();
> try {
> contextsetOptimizationLevel(-1);
>
>                 ScriptableObject scope = contextinitStandardObjects();
>                 Scriptable that = contextnewObject(scope);
>
>                              Function fct = contextcompileFunction(scope, scriptTest, "script", 20, null);
>                 Object result = fctcall(
>                         context, scope, that, new Object[] {});//2, 3
>
>
>
>                 String rrrr = StringvalueOf( ContextjsToJava(result, intclass));
>
>             } finally {
>                 Contextexit();
>             }
>
> Best Regards,
> Aurelian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/257>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by aurelianr** [comment]
Hello gbrail,

That ajax object is from jquery libray. I updated my js code:

 <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.3.min.js"></script>
function Test() { 
		var request = $.ajax({
		method: "GET",
		crossDomain: true,  
		cache:false,  
		dataType: 'jsonp',
		url: "http://stsbu-01n152:8099/PdfEditService/PdfEditServiceREST.svc/PdfEditServiceREST/TestService",      
		contentType: 'application/json'
		});

		request.done(function( data ) {   
		   alert(data); 
		   var el =  document.createElement("h1")
el.id=data;
el.innerHTML = data;
document.body.appendChild(el);
		  });
			
		request.fail(function( jqXHR, textStatus, errorThrown ) {
		  alert(textStatus + ': ' + errorThrown);
		});
}

However I am still not able to execute this code using rhino in android:

   AssetManager am = getApplicationContext().getAssets();
				        InputStream is = am.open("test.js");
				        String source = convertStreamToString(is);
				        Main.processSource(context,  source );
				
				        System.out.println(" xx " + Main.getOut());

**Comment by oberhamsi** [comment]
@aurelianr rhino doesn't have the browser JS APIs jquery requires. you could try with something like env.js but if you need to make http requests, it's probably easier to look for a java library and use that from rhino.

**Comment by aurelianr** [comment]
Thanks allot for your reply. I take a look to env js but i found hard to integrate with android.
