### ISSUE TITLE
v1.7.7 Compiled With JDK 6?

### ISSUE THREAD

**Issue by reid-spencer** [mozilla/rhino#258]
I was using nu.validator which uses Rhino for some testing and [ran into an issue with it](https://github.com/validator/validator/issues/206). It turns out something Rhino 1.7.7 does (access Object.keys) isn't compatible with JDK7 or JDK8 since it is compiled with JDK 6. That's 3 years out of date. 

It would be helpful for people making use of Rhino if it a version of it could be released (to maven central) that was compiled with a modern version of Java.

**Comment by gbrail** [comment]
A lot of people use Rhino in a wide variety of projects. We removed Java
1.5 support in a recent release and I don't recall hearing about too many
problems with that, although I know that there was at least one project
that had a problem. It's my impression that there's still a reasonable
amount of code out there that runs in Java 6, so if we removed Java 6
support then I'm guessing that we'd break a larger number of projects.

And keep in mind that one advantage of Rhino over the new JS engine in Java
8 (Nashorn) is that Rhino doesn't require Java 8 to run.

We could consider making a future Rhino release Java 7-only but I'd like to
hear if there are folks on the mailing list who that will break.

On Tue, Jan 5, 2016 at 4:09 PM, Reid Spencer <notifications@github.com>
wrote:

> I was using nuvalidator which uses Rhino for some testing and ran into an
> issue with it <https://githubcom/validator/validator/issues/206> It turns
> out something Rhino 177 does (access Objectkeys) isn't compatible with JDK7
> or JDK8 since it is compiled with JDK 6 That's 3 years out of date
>
> It would be helpful for people making use of Rhino if it a version of it
> could be released (to maven central) that was compiled with a modern
> version of Java
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/rhino/issues/258>.
>



-- 
*Greg Brail* | *apigee <https://apigee.com/>* | twitter @gbrail
<http://twitter.com/gbrail> @apigee <https://twitter.com/apigee>

**Comment by reid-spencer** [comment]
@gbrail - why does it need to be one or the other? Can you not release artifacts for JDK6 and 7 (or 8) ?

**Comment by gbrail** [comment]
Well the "proper" way to do this IMHO is to edit built.gradle so that it builds two JARs -- one with "sourceVersion" 1.6, and another with "sourceVersion" 1.7. Then it's simple to publish to Maven Central.

I'm not sure how to do this in Gradle off the top of my head but there are others in the community who can help, and you are of course welcome to submit a PR.

**Comment by gbrail** [comment]
We now have the target JVM and source level set to "1.8" in build.gradle, and I build all releases with Gradle. I think we can now retire ant...

**Comment by gbrail** [comment]
The master branch is now built with 1.8 and subsequent releases (1.7.8 and up) will require Java 8 to run. (I know, just in time for Java 9!)
