### ISSUE TITLE
IllegalAccessException on Android 6.0.1 when using ScriptableObject.defineClass with static inner class

### ISSUE THREAD

**Issue by zhuowei** [mozilla/rhino#259]
It seems that Android 6.0's ART runtime has a bug where public constructors of private static inner classes are mistakenly considered private when using reflection.

The stack trace is:

```
01-09 19:12:23.891 19512 19750 W System.err: java.lang.IllegalAccessException: java.lang.Class<net.zhuoweizhang.mcpelauncher.ScriptManager$NativePlayerApi> is not accessible from java.lang.Class<org.mozilla.javascript.ScriptableObject>
01-09 19:12:23.891 19512 19750 W System.err: 	at java.lang.reflect.Constructor.newInstance(Native Method)
01-09 19:12:23.891 19512 19750 W System.err: 	at org.mozilla.javascript.ScriptableObject.buildClassCtor(Unknown Source)
01-09 19:12:23.891 19512 19750 W System.err: 	at org.mozilla.javascript.ScriptableObject.defineClass(Unknown Source)
01-09 19:12:23.891 19512 19750 W System.err: 	at org.mozilla.javascript.ScriptableObject.defineClass(Unknown Source)
01-09 19:12:23.891 19512 19750 W System.err: 	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:236)
01-09 19:12:23.891 19512 19750 W System.err: 	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:179)
01-09 19:12:23.891 19512 19750 W System.err: 	at java.lang.Thread.run(Thread.java:818)
```

The crashing line is https://github.com/mozilla/rhino/blob/Rhino1_7_7_RELEASE/src/org/mozilla/javascript/ScriptableObject.java#L1339

The (simplified) code that causes the error:

```
	public static void initJustLoadedScript(Context ctx, Script script, String sourceName) {
		Scriptable scope = ctx.initStandardObjects(new BlockHostObject(), false);
		ScriptableObject.defineClass(scope, NativePlayerApi.class);
	}
	private static class NativePlayerApi extends ScriptableObject {
		public NativePlayerApi() {
			super();
		}

		@JSStaticFunction
		public static double getX() {
			return 0.0;
		}
		@Override
		public String getClassName() {
			return "Player";
		}
	}
```

I'm using Rhino 1.7.7 on Android 6.0.1 (Nexus 6P), although I can reproduce it on 1.7_r4 as well. This doesn't happen on Android 5.1 and before, suggesting that it's an Android 6.0 bug.

I'm currently working around the issue by adding a `protoCtor.setAccessible(true);` just before the faulting line, but that doesn't seem like a clean solution.

**Comment by F43nd1r** [comment]
This looks like a bugfix instead of a bug to me. Stackoverflow agrees - http://stackoverflow.com/questions/23180476/public-constructor-of-a-private-class. You should not be able to access that constructor. Apparently this is buggy on 5.1 and below.
