### ISSUE TITLE
Request for console mode debugger

### ISSUE THREAD

**Issue by githideoyon** [mozilla/rhino#261]
While current rhino supports AWT Gui mode debugger, my environment does not allow to use java AWT. 
I needs to build console type simple debug utility to step into the scripts and variable of rhino and to set break points. Current debug Shell is almost similar to jrunscript.

**Comment by p-bakker** [comment]
For anyone coming by this issue and still looking for some console-based debugging: maybe the ShellDebugger mentioned in https://wiki.eclipse.org/JSDT/Debug/Rhino/Embedding_Rhino_Debugger#Testing_Remote_Rhino_Locally could be of use
