### ISSUE TITLE
Caching ContinuationPending exception or allow subclassing it

### ISSUE THREAD

**Issue by spielzeugland** [mozilla/rhino#266]
In a project we are using continuations quite heavily. There are multiple interceptions per script call. For performance reasons we would like to avoid the cost of creating a ContinuationPending exception every time by overriding org.mozilla.javascript.Context#captureContinuation(). We would care about setting the right continuation and application state. Unfortunately the constructor of ContinuationPending exception is package visible only. Making it protected would be one option to solve this for us.

**Comment by gbrail** [comment]
That's a simple thing to fix and I don't see what it would hurt (pending tests). 

Any chance you'd be able to try it out yourself and create a pull request?

**Comment by gbrail** [comment]
Thanks for the PR!
