### ISSUE TITLE
potential ToBolean ecmascript spec error Rhino v1.7R3  bundled in rt.jar

### ISSUE THREAD

**Issue by farzonl** [mozilla/rhino#271]
This does not look to be an issue in your master branch, i'm trying to track down  what is going wrong. Any help you all can provide would be amazing. The build server I am using has a JDK 7 instance I myself am using java 8. I believe this means I am using   Nashorn locally, hence the problem I am seeing on committing. It looks like the version in question is Mozilla Rhino v1.7R3 pre-release (http://www.oracle.com/technetwork/java/javase/jdk7-relnotes-418459.html). I don't see a  1.7R3 branch on github but do see a 17R1 and a 17R2.

this is the offending code in one of the ant build files: sName is an empty string
<![CDATA[
if(sName)
{
...
}
]]>

according to the spec if conditions do the following
if(toboolean(getvalue("")))
looking as far back as ecmascript 3 the behavior of toBoolean on strings should be:

"The result is false if the argument is the empty string (its length is zero); otherwise
the result is true."

which is exactly what you all do and Nashorn does, so I am really confused as to why my build machine  is evaluating this if statement as true. If you all have any insightful answers that would be awesome. as a work around I have changed this if statement to check for null and empty string explicitly, so this is not a blocking issue for me and I am not looking for a fix. I am just curious why I saw a build break in the first place.

**Comment by sainaen** [comment]
First of all, are you absolutely sure that `sName` is *always* an empty string and there's no way to observe the effects in your app as if code inside of this particular `if` was executed when it wasn't?

To me, coercion of empty strings to `false` is such an important and widely used language feature that we would hear about a bug of this kind the next day after release if not earlier. :)

But, to be sure, I just did an experiment using Oracle JDK 1.7.0_80-b15 and a test class:

```java
import javax.script.*;

public class Runner {
        public static void main(String... args) throws ScriptException {
                ScriptEngineManager mngr = new ScriptEngineManager();
                ScriptEngine engine = mngr.getEngineByName("JavaScript");
                engine.eval(args[0]);
        }
}
```

```
$ javac Runner.class
$ java Runner 'var sName = ""; if (sName) print("WAT"); else print("OK")'
```
and got an `OK` back, so (unsurprisingly) it works as expected.

Can you try to run this experiment on your build server?

**Comment by farzonl** [comment]
I spent some time reducing the ant build files. Upon further testing sName
is not a type string its a type object. attributes.get("name") does not
return the type I expected and my comparisons were coercing it to a string.
a typeof check confirmed the issue for me.

Thank you Ivan for the sanity check. my new assumption is something else
was coercing this object to a string locally that doesn't happen on the
build machine.

These are the important: environment variables of the build machine

Apache Ant(TM) version 1.9.6 compiled on June 29 2015
java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

Here is the reduced ant file I wrote:
<project name="jsScriptTest" basedir="." default="run-java">
<target name="build-java">
<scripttest name="" />
<exec dir="${basedir}" executable="javac" failonerror="true">
<arg line="Runner.java"/>
</exec>
</target>
<target name="run-java" depends="build-java">
<scripttest name="" />
<exec dir="${basedir}" executable="java" failonerror="true">
<arg line='Runner'/>
</exec>
</target>
<scriptdef name="scripttest" language="javascript">
<attribute name="name"/>
<![CDATA[
var sName = attributes.get("name");
if(sName)
{
                        print(typeof sName);
print("sname is:" + sName);
}
]]>
</scriptdef>
</project>

**Comment by sainaen** [comment]
Well, `sName` *is* a String.

It's just that it is an instance of `java.lang.String` and [for Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java#Java_Strings_and_JavaScript_Strings) it's a different thing from JavaScript's `String`. Nashorn on the other hand [uses](http://hg.openjdk.java.net/jdk8/jdk8/nashorn/file/096dc407d310/src/jdk/nashorn/internal/runtime/JSType.java#l168) `java.lang.String` as JS `String` and provides expected JS behavior for them.

So this script:
```js
var s = new java.lang.String("");
if (s) {
  print("yep");
} else {
  print("nope");
}
```
will print "yep" when executed by Rhino, because `s` is a non-null reference to object, which is coerced to `true`, and "nope" in Nashorn, because there it's just an empty String, not object.

**Comment by farzonl** [comment]
ah so it was a compiler compat issue. Good to know, @sainaen  thanks for Investigating this with me!

**Comment by sainaen** [comment]
glad I could help. also, thanks for bringing this up and not dismissing as a ‘weird JS stuff’, it was fun to figure out. :)
