### ISSUE TITLE
How to write to a object implemented in java in javascript?

### ISSUE THREAD

**Issue by faywong** [mozilla/rhino#276]
I implemented a document object in java and bind it to name "document" in the global scope.

When i write it in javascript like this:

``` javascript
document.someobj = 'some value';
```

The rhino engine report a error as it trap into java and can't find the 'someobj' accessor in it.

**So how can i achieve writing to a object implemented in java in javascript?**

Any advice is appreciated.

**Comment by p-bakker** [comment]
Closing this as it contains too little information to triage.

If you are still looking for an answer, please reopen with reproducible code
