### ISSUE TITLE
Support Object.assign()

### ISSUE THREAD

**Issue by asashour** [mozilla/rhino#280]
Please support Object.[assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)().

**Comment by human33** [comment]
[Commit](https://github.com/mozilla/rhino/commit/9a5191ed36f44674d2c2639186ab0a2d7056f2bd).

**Comment by gbrail** [comment]
Yes, forgot to update the issue. Thanks!
