### ISSUE TITLE
Question: What is the difference between issues here and in Bugzilla?

### ISSUE THREAD

**Issue by alisajedi** [mozilla/rhino#283]
Hello
* This is not a bug report. I just have a question.
I am a researcher at University of Alberta, doing research on bug assignment in Github and Bugzilla.

This project is also on Mozilla (https://bugzilla.mozilla.org/describecomponents.cgi?product=Rhino) and there are some issues there.

What is the difference between the bugs reported in Bugzilla and the issues reported here in Github? 
My intuition is that the issues listed in the Github repository are the ones that the developers found under development, but the bugs addressed in Bugzilla are for every user in the open source community. 
Is that true? Please correct me if I'm wrong.
Thank you.

**Comment by tntim96** [comment]
The Rhino project migrated to Github some time back. For some history on that see [this thread](https://groups.google.com/forum/#!topic/mozilla-rhino/SLh_RjYfLjA).

As Gihub has it's own issue tracker which integrates with it's UI (automatic cross-referencing between bugs, PRs and commit messages), it makes sense to raise new bugs on Github. Also, PRs are much nicer to deal with than attached patches.

For more Github integrations see:
* https://help.github.com/articles/autolinked-references-and-urls/
* https://help.github.com/articles/closing-issues-via-commit-messages/

I think Bugzilla is now effectively obsolete for this project.

**Comment by alisajedi** [comment]
Thank you.
