### ISSUE TITLE
new Error() has no .stack

### ISSUE THREAD

**Issue by ntrrgc** [mozilla/rhino#284]
This is a unit test from Rhino (https://github.com/mozilla/rhino/blob/master/testsrc/org/mozilla/javascript/tests/ErrorPropertiesTest.java#L66-L75):

```
@Test
public void mozillaStack() {
    RhinoException.useMozillaStackStyle(true);
    testScriptStackTrace("null.method()", "@myScript.js:1" + LS);
    final String script = "function f() \n{\n  null.method();\n}\nf();\n";
    testScriptStackTrace(script, "f()@myScript.js:3" + LS + "@myScript.js:5" + LS);
    testIt("try { null.method() } catch (e) { e.stack }", "@myScript.js:1" + LS);
    final String expectedStack = "f()@myScript.js:2" + LS + "@myScript.js:4" + LS;
    testIt("function f() {\n null.method(); \n}\n try { f() } catch (e) { e.stack }", expectedStack);
}
```

Currently it passes, but if you threw a constructed error like this, it would not:

```
testIt("try { throw new Error('app exception') } catch (e) { e.stack }", "@myScript.js:1" + LS);
```

The error output is this:

```
expected:<@myScript.js:1
> but was:<org.mozilla.javascript.Undefined@6ac6998d>
Expected :@myScript.js:1

Actual   :org.mozilla.javascript.Undefined@6ac6998d
```

I can reproduce the issue easily with minimal Java code, but it works fine in the CLI. Is this intended behavior? Why?

```
package com.example.test;

import org.mozilla.javascript.Context;
import org.mozilla.javascript.RhinoException;
import org.mozilla.javascript.Scriptable;

public class Main {
    public static void main(String[] args) {
        Context ctx = Context.enter();
        ctx.setGeneratingDebug(true);
        ctx.setOptimizationLevel(-1);
        Scriptable global = ctx.initStandardObjects();

        String stack = (String)ctx.evaluateString(global, "try{throw new Error('')} catch(e){ e.stack }", "code.js", 1, null);
        System.out.println(stack);
    }
}
```

**Comment by shturec** [comment]
I'm not a contributor and cannot answer you question but in case you need a workaround here is what I found out. 

In a nutshell you need the [FEATURE_LOCATION_INFORMATION_IN_ERROR](https://github.com/mozilla/rhino/blob/6420e464a890faba5a47ead45e6f1d5050f95260/src/org/mozilla/javascript/Context.java#L265) flag enabled (which is off by default) for your Context. The way I did this was to init a global  [ContextFactory](https://github.com/mozilla/rhino/pull/rhino/src/org/mozilla/javascript/ContextFactory.java) overriding the `hasFeatures `method only, return true if this particular features is requested and delegate everything else to the original implementation.

See [here](https://github.com/mozilla/rhino/pull/109#issuecomment-339030178) for a more detailed explanation.

For what it's worth, I personally think that traceability in terms of traces must be a feature enabled by default. Somebody might argue that it's available in the java part of the stack anyway but that alone is fairly insufficient if you try to build something more sophisticated on the JS scripting side like in my case. I never got a valid reason beyond explanation 'for historical reasons' which doesn't sound convincing to me at all. Its just annoying that you have to go through all this for a simple stack trace...

**Comment by gbrail** [comment]
The new PR makes all Error objects have a stack, and also errors have stacks even if "FEATURE_LOCATION_IN_ERROR" is off and the filename is not present.
