### ISSUE TITLE
String.prototype.replace ( regex, function )

### ISSUE THREAD

**Issue by egmose** [mozilla/rhino#289]
Discover that replace did not follow ECMAscript 5 in Service Now and the told be they used Rhino 1.6R5.
I test with the newest version. Stil seems to produce an error.

C:\Users\tpe\Downloads\rhino1_7R4\rhino1_7R4>java -jar js.jar
Rhino 1.7 release 4 2012 06 18
js> var a = "this string has a char we need to escape. it's was right their";
js> a.replace(/'/g, escape);
js: invalid string escape mask

**Comment by egmose** [comment]
It was pointed out to me that https://github.com/mozilla/rhino/issues/289 might be related

**Comment by egmose** [comment]
This seems related, by the error message? https://bugzilla.mozilla.org/show_bug.cgi?id=367627

**Comment by sainaen** [comment]
This is an issue with `escape()`, not a `String.prototype.repalce()`:
1. Rhino supports a non-standard second argument `mask` for the `escape()` that is a bitmask of what things should be escaped. It has to be a number smaller than 8 (mask's length is three bits). When it has an invalid value you'll get this error
1. `replace()` provides three arguments to its callback: a matched substring, a match position, the whole string
1. for the string in the this issue, position of the first match is 44, which isn't a valid mask value

I think we should turn it off at language levels >= ES6 and hide it behind a feature flag.

**Comment by p-bakker** [comment]
As this issue isn't about replace, but about escape, I'm closing this in favor of https://github.com/mozilla/rhino/issues/774
