### ISSUE TITLE
License for Rhino

### ISSUE THREAD

**Issue by bashok001** [mozilla/rhino#293]
I am trying to use Rhino on a project that I am working on. I was looking at MDN for licensing requirements which states, `Rhino is open source. As of release 1.7R4 Rhino is available under MPL 2.0.` I am planning to use the latest release which is 1.7.7.x, which I understand should be on MPL 2.0 . But when I open the LICENSE.txt, the first line states at `The majority of Rhino is licensed under the MPL 2.0:` here: https://github.com/mozilla/rhino/blob/master/LICENSE.txt#L1

I am wondering if there is a "minority" part of source which is not covered under MPL2.0. If so, which, can you point me to the license for that part. If not, can we remove that line from LICENSE.txt?

**Comment by gbrail** [comment]
Rhino is distributed under the MPL 2.0. I'm not an open-source attorney so I'd hesitate to give you any more specific advice.
