### ISSUE TITLE
 illegal character error with "0x60" [`(Unicode Character 'START OF GUARDED AREA' (U+0096))]

### ISSUE THREAD

**Issue by commonsuppliz** [mozilla/rhino#294]
I am trying to js html5 complie code at http://codepen.io/waisbren89/pen/gwvVpP

Rhino throws 

---------Rhino Evaluator Detail----------
Message: illegal character (#102)
Source : 
Details:  illegal characterLineNumber :102
Column :26
-----------------------------------------------

<html charset="utf-8">
<head>
</head>
<body>
<script>
var s1 = `hsla(222,100%,11%,11)`;
document.write(s1);
</script>
</body>
</html>

This works in Chrome, Firefox and Edge.
Rhino needs to handle  'START OF GUARDED AREA' (U+0096) correctly.

**Comment by sainaen** [comment]
This is a duplicate of #325.
Character with a code 0x60 (or U+0060) is a grave accent or a backtick. It's a part of Template Literals feature that is not supported by Rhino right now.
