### ISSUE TITLE
Target of javaPrimitiveWrap in WrapFactory includes not primitive wrapper classes.

### ISSUE THREAD

**Issue by hatanaka-akihiro** [mozilla/rhino#295]
WrapFactory with javaPrimitiveWrap = false does not wrap

- java.lang.String
- java.lang.Character
- subclasses of java.lang.Number
- java.lang.Boolean

I think "subclasses of java.lang.Number" is problem.
Because subclasses of java.lang.Number includes "not primitive wrapper classes" such as java.math.BigDecimal, java.math.BigInteger.

I would like to expect "not primive wrapper classes".
I think suitable javaPrimitiveWrap target is below.

- java.lang.String
- java.lang.Character
- java.lang.Byte
- java.lang.Short
- java.lang.Integer
- java.lang.Long
- java.lang.Float
- java.lang.Double
- java.lang.Boolean

regards.

**Comment by gbrail** [comment]
So are you suggesting that we change the target to include those specific classes?

That makes sense to me. However I don't know what this might break...

**Comment by hatanaka-akihiro** [comment]
I would like to exclude java.math.BigDecimal and  java.math.BigInteger from target of javaPrimitiveWrap.

In javascript, I want to avoid being aware of java.lang.String.

I think I can use javaPrimitiveWrap to this purpose.

However, I cannot make javaPrimitiveWrap false, because javaPrimitiveWrap targets java.math.BigDecimal and  java.math.BigInteger.

**Comment by gbrail** [comment]
I spent a bunch of time last week trying to build a test case for this and
I wasn't able to figure out what the problem is. The interaction between
native code being called from Rhino, WrapFactory, and the javaPrimitiveWrap
method seems to be pretty complex.

If you could supply a test case that shows what you're trying to do then we
could see what the options are. Otherwise, the reason why WrapFactory
exists and is settable in the Context is so that you can customize the
behavior if you wish.

**Comment by hatanaka-akihiro** [comment]
I wrote Test class.

[RhinoTest.java.txt](https://github.com/mozilla/rhino/files/1331822/RhinoTest.java.txt)

I think there is sense of unity in case of javaPrimitiveWrap = false.

**Comment by gbrail** [comment]
Thanks for the test case -- that makes it much clearer. Here is a PR that includes a fix, plus your test code.

https://github.com/mozilla/rhino/pull/339

Unfortunately the decision as to the result of "typeof" on a BigInteger or BigNumber is happening somewhere else, not in WrapFactory. I'm not sure where that is yet, or whether changing it also would cause big problems for existing code -- I'm kind of inclined to say that we shouldn't change that now.

Please let me know if it's OK to include your test code in the project.

**Comment by hatanaka-akihiro** [comment]
Of cause, OK. Please use my code.

**Comment by gbrail** [comment]
OK -- fixed that. I'm not sure about the other problem -- BigInteger instances being shown as a "number" type - that may be a more intrusive change.

https://github.com/mozilla/rhino/pull/339
