### ISSUE TITLE
Stacktraces don't include the column number

### ISSUE THREAD

**Issue by kjg** [mozilla/rhino#304]
When I run a node app using node the stack traces look like:

```
error: Unhandled Exception:
    at process._tickDomainCallback (node.js:463:13)
```

When I run that same app under rhino via trireme, stack traces look like

```
error: Unhandled Exception:
    at process._tickDomainCallback (node.js:463)
```

There are some node packages like [node-stack-trace](https://github.com/felixge/node-stack-trace) that [assume there will be a column number](https://github.com/felixge/node-stack-trace/blob/4a282316db4a2a93bdc91c6bc06c085ba878d5af/lib/stack-trace.js#L42) in the trace.

Ref: https://github.com/apigee/trireme/issues/153

**Comment by gbrail** [comment]
Rhino doesn't seem to have the column number in compiled mode. However, when using "V8" stack trace mode, the stack trace should look just like V8. So, we append a column number "0" to every stack line so that least libraries that parse the stack trace (welcome to the wacky world of Node) can work.
