### ISSUE TITLE
DataView offset parameter is ignored

### ISSUE THREAD

**Issue by joeknoll** [mozilla/rhino#314]
When creating a new DataView in javascript, the offset parameter is ignored.  Looking at the source code (NativeDataView and NativeArrayBufferView) this is confirmed.

```javascript
var buffer = new ArrayBuffer( 4 );
var view1 = new DataView( buffer );
view1.setUint8( 0, 0xFF );
var view2 = new DataView( buffer, 2, 1 );
var test = view2.getUint8( 0 );
```
variable test now contains 0xFF and not 0 as expected.

**Comment by gbrail** [comment]
That is a big miss in the test coverage. Fortunately it's a simple fix. Thanks!

**Comment by gbrail** [comment]
Fixed in master.
