### ISSUE TITLE
rhino-1.7.7.2.zip contains duplicate files

### ISSUE THREAD

**Issue by ilovezfs** [mozilla/rhino#321]
The first duplicate is
```
unzip -qq /Users/joe/Library/Caches/Homebrew/rhino-1.7.7.2.zip
replace rhino1.7.7.2/src/org/mozilla/javascript/NativeDate.java? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

Here's a list of all files in the zip file: https://gist.github.com/ilovezfs/4c34930e3d6037a4da01df00920fa4bf

As you can see, there are quite a few duplicates.

One can work around this by using `unzip -qqo` but that shouldn't be necessary.

**Comment by gbrail** [comment]
Fixed this in https://github.com/mozilla/rhino/pull/338. I also moved the tag to include the commit that fixes build.gradle and uploaded fixed ZIP files to GitHub so that they should now extract without problem.

**Comment by ilovezfs** [comment]
Thanks @gbrail! https://github.com/Homebrew/homebrew-core/pull/18635
