### ISSUE TITLE
Template Literals / backticks Not Working

### ISSUE THREAD

**Issue by dylanh724** [mozilla/rhino#325]
This is a pretty core ECMA6 feature that has been around for a decent while now -- any chance template literals and backticks are coming soon?

```
var myName = 'Jon Snow';
var name = `Greetings, ${myName}!`; // Error
// Expected: 'Greetings, Jon Snow!'
```

**Comment by gbrail** [comment]
Anyone who is willing to spend time on the codebase is welcome to
contribute this enhancement. However there is no one working on it AFAIK.

**Comment by dylanh724** [comment]
Ah, I'm so bad at Java. Perhaps another year. It would take me ages just to get it out of the box.

**Comment by p-bakker** [comment]
This is a dup of #243, so should be closed as such imho
