### ISSUE TITLE
Rhino for Android ：int  parameter be converted to Double

### ISSUE THREAD

**Issue by ZhanQiangWu** [mozilla/rhino#327]
my problem ：
I use Rhino to run js code in Android. The js code is :
var data= app.request('api/entity/detail', {
	"entityId": "0ccd079d-ec1f-404e-a9d5-cfbe965aca6b",
	"recId": "26e6dc92-dab8-4a0c-a26f-1606e78038b0",
	"needPower":0
});
when it runs it will call function request() in Android, but the json input will be converted to 
{
	"entityId": "0ccd079d-ec1f-404e-a9d5-cfbe965aca6b",
	"recId": "26e6dc92-dab8-4a0c-a26f-1606e78038b0",
	"needPower":0.0
}
as you can see,the value of 'needPower' is converted to 0.0, and its type become Double,but i want its correct type is Int and its value is 0;  
Thanks for help!

**Comment by gbrail** [comment]
JavaScript doesn't have integers -- it only has "numbers." Same goes for JSON. Internally Rhino sometimes uses ints and sometimes doubles, and it tries to figure one from another. The Rhino compiler tries to be smart and figure out when it's dealing only with integers, but in interpreted mode I'm not sure how smart Rhino is.

Is this happening in interpreted or compiled mode?

Either way, I don't think this would be easy to fix.

**Comment by ZhanQiangWu** [comment]
It happens in interpreted mode.
Thank you so much for your assistance.

**Comment by p-bakker** [comment]
Closing this issue as it seems answered.

Note though that the Object > JSON conversion inside app.request must handle this: if using Rhino's built-in JSON.stringify, it owuld output: `..."needPower":0}`
