### ISSUE TITLE
Make Rhino work with Java 9

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#352]
It just doesn't. Java 9 is supposed to be backward compatible, so we have to figure this out.

**Comment by gbrail** [comment]
Upgrading Gradle helps a lot.

There are a number of new test failures around String.prototype.trim, and a few date-parsing test failures. The rest passes.

**Comment by gbrail** [comment]
Sounds like the main test failures are coming from the fact that Java 9 uses a different set of Unicode encodings by default than previous Java releases. These might not be actual test failures but a different interpretation of Unicode from what was done before versus what's done in Java 9.

http://openjdk.java.net/jeps/252

**Comment by p-bakker** [comment]
@gbrail Think this one can be closed? Builds on Java versions >8 & < 16 seem to work just fine no?

**Comment by gbrail** [comment]
Yep -- works and we're adding CI.
