### ISSUE TITLE
Function.prototype.apply fails with "Array like" second argument

### ISSUE THREAD

**Issue by tmallery** [mozilla/rhino#355]
TypeError: second argument to Function.prototype.apply must be an array

With this test code:
function test() { numArgs = arguments.length; }
test.apply(this, {'length':2, '0':'turkey', '1':'gravey'});

Per Mozillas MDN this should be allowed: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply

**Comment by p-bakker** [comment]
Seems long fixed
