### ISSUE TITLE
API changes report for snapshot of Rhino

### ISSUE THREAD

**Issue by lvc** [mozilla/rhino#359]
Hi,

I'd like to share report on API changes and backward compatibility for snapshot of the Rhino library: https://abi-laboratory.pro/java/tracker/timeline/rhino/

BC — binary compatibility
SC — source compatibility

The snapshot package is taken from here: https://oss.sonatype.org/content/repositories/snapshots/org/mozilla/rhino/

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![rhino-1](https://user-images.githubusercontent.com/1517837/32536193-6186d5a8-c46e-11e7-8d58-39c93ae7ff73.png)
![rhino-2](https://user-images.githubusercontent.com/1517837/32536192-6169b0d6-c46e-11e7-863b-513c6e40e993.png)

**Comment by gbrail** [comment]
Thanks. I'm not sure what to do with this information but it's neat to have.
