### ISSUE TITLE
Does not support es6??

### ISSUE THREAD

**Issue by zhenruyan** [mozilla/rhino#367]
org.mozilla.javascript.ScriptOrFnNode.getParamOrVarIndex(Ljava/lang/String;)

**Comment by gbrail** [comment]
Rhino supports some features of ES6. You can find some information on the
compatibility table (although it needs an update!)

http://mozilla.github.io/rhino/compat/engines.html

I'm not sure I understand what your question is however.

**Comment by Bigil-ragu** [comment]
"for..of" loop is not supported by Rhino. It reports an error stating "missing ; after for loop initializer"

**Comment by sjkillen** [comment]
A little late, but babel.js is a tool that can convert most modern JavaScript features (ES2015+)
To older versions of JavaScript
See the babel column in this table:
https://kangax.github.io/compat-table/es6/
