### ISSUE TITLE
Download page on mozilla website has confusing message about qualified release

### ISSUE THREAD

**Issue by vitgorbunov** [mozilla/rhino#375]
Following https://groups.google.com/forum/#!topic/mozilla-rhino/67Iy-A19upU

When I go to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Download_Rhino it says "Rhino 1.7R5 is the most recent qualified release."
However this version is 2 years old.

It seems that this message is outdated.

**Comment by gbrail** [comment]
OK -- I fixed this page with the latest release. Thanks!
