### ISSUE TITLE
1.7.8 RC1: Dynamic Scopes vs. initStandardObjects (NativeSymbol) 

### ISSUE THREAD

**Issue by raimi** [mozilla/rhino#377]
As discussed in https://groups.google.com/forum/#!topic/mozilla-rhino/ez3kr8-o0oI : there is an issue in my specific way of using dynamic scopes initStandardObjects, namely NativeSymbol.

I prepared a testcase.

**Comment by raimi** [comment]
To be clear: passing sealed = false to initStandardObjects(ScriptableObject scope, boolean sealed) makes the problem go away.

**Comment by gbrail** [comment]
Here's a PR for this with a test case:

https://github.com/mozilla/rhino/pull/381

Can you try it out? I'd like to merge it before we do Rhino 1.7.8 later this week.

**Comment by raimi** [comment]
Good news: This fixes both the test-case and our application. Perhaps you can accept both my and your PR? Doesn't hurt to have more tests :)

**Comment by gbrail** [comment]
Fixed this one in https://github.com/mozilla/rhino/pull/378.
