### ISSUE TITLE
HasOwnProperty method in js throws exception

### ISSUE THREAD

**Issue by tosha-220** [mozilla/rhino#379]
I try to make native object from map by recursive transforming each value to native object by making
nobj.defineProperty(entry.getKey(), value, READONLY);
In js code i see that my object is [object Object] but when i call HasOwnProperty function its throw 
org.mozilla.javascript.EcmaError: TypeError: Cannot find default value for object.

**Comment by sainaen** [comment]
What is the type of an argument that you pass to `hasOwnProperty`? It supposed to be a String, but I suspect that it's not.

**Comment by gbrail** [comment]
Can you post a few lines of sample code? Sometimes that makes it a lot
easier to understand what you mean...
