### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by havrikov** [mozilla/rhino#386]
When evaluating the attached file , a `NullPointerException` is thrown.
[rhino_npe.zip](https://github.com/mozilla/rhino/files/1691901/rhino_npe.zip)
Rhino version: `1.7.7.2`
Kotlin code to reproduce the issue if `path` points to the attached file:
```
File(path).reader().use {
            val context = Context.enter()
            val scope = context.initStandardObjects()
            context.evaluateReader(scope, it, path, 1, null)
        }
```

**Comment by sainaen** [comment]
Thanks for reporting this one too!

Here’s simplified reproducer:
```js
const [y,y] = [];
```

`IRFactory` uses `Parser`'s [`createDestructuringAssignment()`](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Parser.java#L3887-L3907) to transform destructuring assignment into a series of regular assignments. When it realizes that we’re trying to declare constant `y` twice, it tries to report an error, but uses normal [`addError()`](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Parser.java#L235) that expects `TokenStream` to be present (`ts`) to construct an error message with position of the offending element.

I see that [`addWarning()`](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Parser.java#L200) and [`addStrictWarning()`](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Parser.java#L185), for example, check if `ts` is `null` and set token’s start position to `-1` and length to `0` when it is. The fix could be as simple as adding the same check to `addError()`, if we don’t care about printing an exact position of the re-declaration in the error message.

**Comment by sainaen** [comment]
@havrikov 
I wonder, did you use some fuzzer to find #385 and this one? The code looks autogenerated.

**Comment by havrikov** [comment]
Yes, I am currently exploring grammar-based fuzzing.

**Comment by sainaen** [comment]
Oh, sounds awesome! Test case reduction still requires work though. 😉

**Comment by Bamagik** [comment]
Just submitted a PR, seems to have fixed the issue, however, I am unsure whether it outputs the expected result as desired.

**Comment by p-bakker** [comment]
The nullPointer error reported here got fixed in https://github.com/mozilla/rhino/pull/987

Created a followup case (#989), as the error thrown now for `const [y,y] = []` is a TypeError, while it should be a SyntaxError
