### ISSUE TITLE
Can not use generator

### ISSUE THREAD

**Issue by XsJIONG** [mozilla/rhino#396]
I runned follow javascript code but got a exception:
function* counter() {
  var c=0;
  while (true)
    yield c++;
}
var gen=counter();

After reading the source code(Parser.java), I found that if the parser find a "function" keyword, it requires that the follow symbol must be "(" or it will throw an exception

Plz fix it!

**Comment by sainaen** [comment]
Rhino implements older version of iterators and generators, not the ones introduced in ES6/ES2015. In this version, you don’t need an asterisk:
```js
function counter() {
  var c = 'a'.charCodeAt(0);
  while (c <= 'z'.charCodeAt(0))
    yield String.fromCharCode(c++);
}
for (let h in counter()) print(h);
// prints out letters from 'a' to 'z'
```
For more examples you can check out older versions of [MDN page on Iterators and generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators$revision/109528).

I agree, it would be great to have this updated, but there’s just not many people working on Rhino right now.

**Comment by Xs-JIONG** [comment]
I tried your code but also got an exception
org.mozilla.javascript.EvaluatorException: missing ; before statement (Main.js#4)
How to fix it?

**Comment by sainaen** [comment]
Weird, I’m not getting any errors. How do you run it?
