### ISSUE TITLE
Invokedynamic breaks CommonJS require()

### ISSUE THREAD

**Issue by m0wfo** [mozilla/rhino#40]
After merging the invokedynamic branch with 1.7 / 1.8 branches, Rhino generates a `ClassCastException` when `require('./foo.js')` is called. The stack trace looks something like [this](https://gist.github.com/2604618)

**Comment by gbrail** [comment]
We are not likely to ever merge the very old "invokedynamic" branch despite some cool work there, so I am going to close this.
