### ISSUE TITLE
For some cases I am getting Javascript Execution Error:Access to Java class "java.lang.String" is prohibited.

### ISSUE THREAD

**Issue by ravichittari** [mozilla/rhino#400]
when some JS is written and exchanged as variables between java and javascript .. running into this exception Javascript Execution Error:Access to Java class "java.lang.String" is prohibited.

**Comment by p-bakker** [comment]
Closing this for now as too little information is provided to act upon.

Please reopen with steps to reproduce this if this is still an issue
