### ISSUE TITLE
smalljar build with Gradle?

### ISSUE THREAD

**Issue by alastaircoote** [mozilla/rhino#413]
(I'm not too well versed in the world of Java, so forgive any ignorance here!)

It looks like you switched from using Ant to Gradle to power the build process at some point, and when that happened the `smalljar` target disappeared. Checking out https://github.com/mozilla/rhino/commit/fa682fa1f878431d0563e1dd662fe8934d32388b and running the Ant build worked fine, so I'm wondering if it's possible to resurrect for the new build process? I only ask because I'm trying to make the smallest-possible version to include in an Android app, where you can't set an optimizationLevel higher than -1 anyway.

**Comment by p-bakker** [comment]
@gbrail what do you think, should we resurrect `smalljar`? 

Here's it's definition in the last commit that contained it: https://github.com/mozilla/rhino/blob/48196be96e9f1a83f30c05e62ad4a399b78e77ce/build.xml#L101

Otherwise I think we should tag this with label `won't fix` and close the issue

**Comment by gbrail** [comment]
I think we should mark it "wont fix". We introduced the "runtime jar" which
has a similar effect, and results in a jar that is more useful for
embedding since it doesn't include the unsafe code in "tools."
