### ISSUE TITLE
Need information about published vulnerabilities for version 1.7R2

### ISSUE THREAD

**Issue by Vyshakh18** [mozilla/rhino#426]
Hi,
As a part of GDPR compliance exercise we are trying to assess the vulnerabilities present in Mozilla Rhino Javascript engine , **version 1.7R2**
Is there any link, where I can find the list of published vulnerabilities for this version (or any version for that matter)
Any help in this regard is highly appreciated.

Thanks,
Vyshakh

**Comment by Vyshakh18** [comment]
This might be off-topic, but just asking, is Mozilla Rhino 1.7.9 backward compatible with 1.7R2?

**Comment by gbrail** [comment]
We have always made an effort to guarantee backward compatibility by being
careful not to break existing tests and to introduce feature flags when
necessary, and to use the "language version" property of the Context class
for major changes. So the answer is basically, "yes."

However bugs have cropped up over the years and for any particular issue
I'd suggest being careful and testing as much as you can. We can help
advise you on specific issues should they arise!

**Comment by p-bakker** [comment]
Closing as this issue doesn't contain any actionable items
