### ISSUE TITLE
Expiry of cached commons-js script entity not updated if corresponding file resource not updated on filesystem

### ISSUE THREAD

**Issue by dhogan** [mozilla/rhino#431]
Line 281 of the UrlModuleSourceProvider currently reads:
_return lastModified == urlConnection.getLastModified();_
It should read
_return lastModified != urlConnection.getLastModified();_

This error prevents the expiry date of a cached, file-based commons-js module from being updated despite the absence of filesystem modifications. Thus the ModuleSourceProviderBase will not recognize that the module entity does not require revalidation (if block on line 37 of ModuleSourceProviderBase), resulting in filesystem resolution of the commons-js entity with every script reference.

**Comment by travishaagen** [comment]
https://github.com/mozilla/rhino/pull/432

**Comment by p-bakker** [comment]
Looks like this was closed by #432 a while back
