### ISSUE TITLE
What's going on with ES6 feats?

### ISSUE THREAD

**Issue by dylanh724** [mozilla/rhino#434]
ES6 has been out for ages and is missing core features like ${} string templating, "let" keyword and =>'s to make cleaner, more-readable code with scope protections.

When will these be added? Why aren't they added already (not asking aggressively -- but literally wondering how come this seemingly has little to no priority)?

Using Rhino compared to vanilla JS, when there is no other option, creates sub-par readability and scope risks. Since JS changes so often (while these core new ES6 feat's probably won't change for a long time), it also doesn't help adapt to non-Rhino projects. It sort of reminds me of using VB.NET instead of C#, these days where it's similar, yet feels dated and isn't a good experience to adapt to newer stuff. 

That last part may appear to be a personal issue, but since Mozilla is all about innovation and education, it's relevant, taking many steps back, much compared to modern FireFox vs Internet Explorer 6.

**Comment by dylanh724** [comment]
Ah, did you know the major BaaS, GameSparks, recently bought by Amazon, uses Rhino? That's why I'm interested in it - because I have to use it haha. I'll let them know about the es6 flag.

**Comment by d-oderbolz** [comment]
Also ServiceNow, one of the leading ITSM Platforms is making heavy use of Rhino. They could assign a few devs to Rhino, I think...

**Comment by xaoseric** [comment]
> Ah, did you know the major BaaS, GameSparks, recently bought by Amazon, uses Rhino? That's why I'm interested in it - because I have to use it haha. I'll let them know about the es6 flag.

We also make use of Rhino in Cobra, the rendering engine of LoboBrowser.

**Comment by black-snow** [comment]
HtmlUnit also uses rhino (a fork with fixes and improvements - https://github.com/HtmlUnit/htmlunit-rhino-fork).

**Comment by p-bakker** [comment]
Closing this case, as the question is sorta answered and there are no actionable items in this case

Note that we now have milestones for each JavaScript (EcmaScript) version from ES5 onwards and we're slowly, but surely identifying all the bits we're missing or area's where we're not spec-compliant and adding cases for those issues to the milestones, in the hope of driving our focus and hopefully inspire some to contribute :-)
