### ISSUE TITLE
issue with compressReader

### ISSUE THREAD

**Issue by ghost** [mozilla/rhino#446]
Hi there,

I 'm using IntelliJ to compile a module but I caught in this problem

Error:(81, 16) java: cannot find symbol
  symbol:   method compressReader(org.mozilla.javascript.tools.shell.Global,org.mozilla.javascript.Script,java.lang.String,java.lang.String,int,<nulltype>)
  location: variable cx of type org.mozilla.javascript.Context

Do you know the reason? 
Thanks

**Comment by gbrail** [comment]
I don't know -- that method isn't part of Rhino from what I can see. Not
sure what else to suggest...

**Comment by Zam76** [comment]
Thank you very helpful, I thought it was from Rhino seeing the errors.
The thing is very strange, on Eclipse it runs, on IntelliJ no.

Thank you I will investigate.
Simone

**Comment by p-bakker** [comment]
Closing this as it doesn't seem related to Rhino
