### ISSUE TITLE
Getting SyntaxError: invalid object initializer - on legit JS code

### ISSUE THREAD

**Issue by itaishalom** [mozilla/rhino#447]
Hi, as far as I understand JS, the below code should work but causes exception when evaluated - 

```
var icons = [];
let RED = 'RED';
let DARK= 'DARK';
icons.push( { name : 'Itai', RED ,DARK}); // which means  icons.push( { name : 'Itai', RED:'RED' ,DARK:'DARK'}); 
```
Will this syntax be supported?
('1.7.9' - Android)

**Comment by sainaen** [comment]
> Will this syntax be supported?

Since it’s in the ECMAScript spec, yes, _at some point_ someone might add support for this syntax to Rhino. But, quoting @gbrail :

> There is no one working on Rhino right now as a full time job. Right now there are a few people around the world who use it as part of other projects and periodically make improvements and fix bugs when they can. We're always welcome to accept proposals for new features or pull requests to implement them!

**Comment by RuralHunter** [comment]
https://exploringjs.com/es6/ch_overviews.html#_new-object-literal-features-1

**Comment by p-bakker** [comment]
Fixed with https://github.com/mozilla/rhino/pull/853
