### ISSUE TITLE
Endless loop and crush when using Stringify on NativeObject

### ISSUE THREAD

**Issue by itaishalom** [mozilla/rhino#450]
NativeJson.stringify(...) I get:
![img_20180621_091733](https://user-images.githubusercontent.com/9066121/41705666-540542a4-7542-11e8-9742-a43e6566e5d0.jpg)

**Comment by gbrail** [comment]
Does this happen for every native object or a particular one? Can you attach a test that reproduces this?

**Comment by itaishalom** [comment]
It happens when Is put an object on the scope with JSParser (let's call it thiz and thiz is JSONObject that has a field ("b,"text") ) , and on the JS code I set something like thiz.a = thiz.b; and then I try to parse it back to string and to JSONObject using Gson but the problem occurs on Stringify. Any way I wrote my own recursive function that parses back Native object to hashMap without going into endless loop.
I'll try to write a test code on Sunday for you if this example is not enough.
