### ISSUE TITLE
Context#getImplementationVersion does not work on Android

### ISSUE THREAD

**Issue by TheBrokenRail** [mozilla/rhino#459]
```java
cx.getImplementationVersion();
```
This returns ```null``` instead of a version on Android.

**Comment by p-bakker** [comment]
The method reads from the META-INF/MANIFEST.MF file, as per https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/ImplementationVersion.java

My guess is that you're using a minifier of sorts that either removes or modifies the file, thus the code cannot determine the version number anymore.

Closing this for now. If the above is not the case, please reopen with additional info
