### ISSUE TITLE
Circular JSON

### ISSUE THREAD

**Issue by TheBrokenRail** [mozilla/rhino#460]
When Running ```JSON.stringify``` on a circular object like ```this```, it throws a StackOverflow error instead of throwing an EcmaError or EvaluationError, so it needs to be caught separately.

**Comment by rPraml** [comment]
I ran in a similar, maybe the same issue. I have a java map. On each access, the same object is wrapped in a NativeJavaObject and therefore both objects are not longer equal

As workaround I copied the NativeJSON class, to org/mozilla/javascript/NativeJSON2 and unwrapped the element before it was put in the Stack (had also to change it to Stack<Object>

Example (must be done on two places)
```
...
		Object trackValue = value;
		if (value instanceof Wrapper) {
			trackValue = ((Wrapper) value).unwrap();
		}
		if (state.stack.search(trackValue) != -1) {
			throw ScriptRuntime.typeError0("msg.cyclic.value");
		}
		state.stack.push(trackValue);
...
```
then, the new objec must be registered with `NativeJSON2.init(...)` - it replaces the original javascript JSON object

cheers
Roland
