### ISSUE TITLE
getLineNumbers misses the first line

### ISSUE THREAD

**Issue by OLSander** [mozilla/rhino#477]
The line numbers returned by DebuggableScript#getLineNumbers do not include the first line of a script if the first line is a debuggable line.

Reproducible with 1.7.9:
```
public class Main {

	public static void main(String[] args) {
		printLineNumbers("var a = 123;");
		printLineNumbers("\nvar a = 123;");
	}

	private static void printLineNumbers(String source) {
		ContextFactory.getGlobal().call(new ContextAction() {

			@Override
			public Object run(Context context) {
				context.setGeneratingDebug(true);
				context.setOptimizationLevel(-1);
				Script script = context.compileString(source, null, 0, null);
				int[] lineNumbers = Context.getDebuggableView(script).getLineNumbers();
				System.out.println(Arrays.toString(lineNumbers));
				return null;
			}
		});
	}
}
```

Expected output:
```
[0]
[1]
```

Actual output:
```
[]
[1]
```

I believe this is related to the "lineno != lineNumber" condition in CodeGenerator:
```
    private void updateLineNumber(Node node)
    {
        int lineno = node.getLineno();
        if (lineno != lineNumber && lineno >= 0) {
            if (itsData.firstLinePC < 0) {
                itsData.firstLinePC = lineno;
            }
            lineNumber = lineno;
            addIcode(Icode_LINE);
            addUint16(lineno & 0xFFFF);
        }
    }
```

.. which fails specifically for the first line since the initial value of lineNumber is zero.

Apologies if this is a known issue, I failed to find any similar reports.

**Comment by gbrail** [comment]
This looks like a pretty straightforward thing to put in a PR for someone who is looking for an issue to work on!

**Comment by camnwalter** [comment]
It looks like if we just set the initial value https://github.com/mozilla/rhino/blob/82416a171354427422f0bcca8c3206b4a5ae4105/rhino/src/main/java/org/mozilla/javascript/CodeGenerator.java#L41 to -1 then it should work?

This breaks some of the `StackTraceTest`s `failureStackTraceMozilla` and `failureStackTraceMozillaLf`, but I think those might be wrong. According to the comment above `StackStyle.MOZILLA`,
```
    /**
     * This stack trace style comes from the old Mozilla code: <code>
     * functionName()@fileName:lineNumber</code>
     */
```
, yet the test expected result, https://github.com/mozilla/rhino/blob/82416a171354427422f0bcca8c3206b4a5ae4105/tests/src/test/java/org/mozilla/javascript/tests/StackTraceTest.java#L59 omits the `:lineNumber`.
