### ISSUE TITLE
StringBuilder/Buffer support in scripting broken

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#496]
I think due to https://github.com/mozilla/rhino/commit/141dc4f5c2947884e0cc4b4313da8e9a6a6141da#diff-8f122a374db26c040ca0460f9c5b4541L1015 it is no longer possible to utilize StringBuffer/Builder in JavaScript, as all instances of CharSequence become ConString instances or something.

While I understand that the ConString optimization alleviates the need to use StringBuffer/Builder, it breaks existing code and makes inline Java code clumsy,  for example the implementation of the characters method of org.xml.sax.helpers.DefaultHandler now looks something like `cellValue += new java.lang.String["(char[])"](chars.slice(start, start + length))`, whereas before it looked like `cellValue.append(chars, start, length)`

**Comment by gbrail** [comment]
I can understand this this changed things. However that particular change was merged in 2011 and it'd probably make things worse in different ways to change it now.

As I recall the Nashorn Engine in Java 8 and 9 does the same thing, and in fact that bit of it was written by the same developer.

ConsString does include a toString() method which flattens the string if it needs flattening...

**Comment by p-bakker** [comment]
See renewed discussion [here](https://github.com/mozilla/rhino/discussions/1206)
