### ISSUE TITLE
Strange behaviour of MD4 library in Rhino

### ISSUE THREAD

**Issue by Mich-b** [mozilla/rhino#515]
I’m using this MD4 library in Rhino and in NodeJS: https://github.com/emn178/js-md4

In Rhino, the output of md4.hex(‘hello world’)= caa4cbe5b1dcda3b7100d2e3709edba8

In NodeJS, the output of md4.hex(‘hello world’)=aa010fbc1d14c795d86ef98c95479d17

It seems the NodeJS result is the correct one. Is this a bug in Rhino?

**Comment by delchev** [comment]
Problematic part:
```
var buffer = new ArrayBuffer(4);
var buffer8 = new Uint8Array(buffer);
var blocks = new Uint32Array(buffer);
buffer8[0] = 101;
result = JSON.stringify(blocks);
```
> Rhino: {"0":1694498816}
> V8: {"0":101}

**Comment by delchev** [comment]
More test data:

```
var buffer = new ArrayBuffer(32);
var buffer8 = new Uint8Array(buffer);
var buffer32 = new Uint32Array(buffer);

buffer32[1] = 111111;
```

V8
--

**buffer8:** {"0":0,"1":0,"2":0,"3":0,"4":7,"5":178,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":0,"27":0,"28":0,"29":0,"30":0,"31":0}
**buffer32:** {"0":0,"1":111111,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0}

Nashorn
---

**buffer8:** 
{"0":0,"1":0,"2":0,"3":0,"4":7,"5":178,"6":1,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":0,"27":0,"28":0,"29":0,"30":0,"31":0}
**buffer32:** {"0":0,"1":111111,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0}

Rhino
--

**buffer8:** {"0":0,"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":1,"10":178,"11":7,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":0,"27":0,"28":0,"29":0,"30":0,"31":0}
**buffer32:** {"0":0,"1":111111,"2":0,"3":0}

**Comment by delchev** [comment]
OK, figured it out. @rbri has fixed this https://github.com/mozilla/rhino/pull/436/commits/4ab12abf8b704d4bfa9ddcbc0ad16c010980db71 and seems planned for 1.7.11 release. It is about the defaulting of the big/little endianness encoding.

To configure it:
```
	static {
		ContextFactory.initGlobal(new ContextFactory() {
			@Override
			protected boolean hasFeature(Context cx, int featureIndex) {
				...
				if (featureIndex == Context.FEATURE_LITTLE_ENDIAN) { // 19
					return true;
				}
				return super.hasFeature(cx, featureIndex);
			}
		});
	}
```

V8 and Nashorn are defaulting to Little Endian while Rhino is defaulting to Big Endian as it should be according to the spec https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays.

With the configuration above the MD4 module works with Rhino in the same way as it is with V8/Node.

**Comment by Mich-b** [comment]
Thanks for investigating this. Is there a way to enforce little endianness by changing the MD4 code, without having to change the Rhino context or without having to wait for an update?

**Comment by gbrail** [comment]
Good catch. The native array in Java uses big endian ordering because
that's the native byte ordering of Java, regardless of platform. The recent
patch gives you control over this using the Context class.

I'd argue that if this MD4 code is supposed to be truly portable code, and
if it expects its output to be in a particular byte order, then it should
use the DataView class directly so that it can explicitly set the byte
order.

**Comment by gbrail** [comment]
Closing since I believe this is controllable using Context.
