### ISSUE TITLE
Feature request: implement  String.prototype.padStart(), String.prototype.padEnd(), and Array.prototype.includes()

### ISSUE THREAD

**Issue by manishmotwani3** [mozilla/rhino#521]
Hi, the implementations of the following functions is missing in the latest version of Rhino.
Can we add these?

String.prototype.padEnd( maxLength [ , fillString ] )
https://www.ecma-international.org/ecma-262/8.0/#sec-string.prototype.padend

String.prototype.padStart( maxLength [ , fillString ] )
https://www.ecma-international.org/ecma-262/8.0/#sec-string.prototype.padstart

Array.prototype.includes ( searchElement [ , fromIndex ] )
http://www.ecma-international.org/ecma-262/8.0/index.html#sec-array.prototype.includes

**Comment by rbri** [comment]
Have created a pull request for  padStart and padEnd. Includes is already there.

**Comment by rbri** [comment]
I think we can close this
