### ISSUE TITLE
ArrayBuffer.byteLength

### ISSUE THREAD

**Issue by manishmotwani3** [mozilla/rhino#522]
As per the ECMA-262 v6, if the object doesn't belong to the ArrayBuffer class then invoking getting byteLength property should throw a type error. ("If O does not have an [[ArrayBufferData]] internal slot, throw a TypeError exception.") (source: https://www.ecma-international.org/ecma-262/6.0/#sec-get-arraybuffer.prototype.bytelength).  However, I get "undefined" instead of TypeError. 

passing test case:
var buffer = new ArrayBuffer(8);
var bytes = buffer.byteLength;
// expected output: 8
// actual output: 8

failing test case
var buffer = 8;
var bytes = buffer.byteLength;
// expected output: TypeError
// actual output: undefined

**Comment by rbri** [comment]
Running your failing example in some browser shell (https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/byteLength) returns undefined.

var buffer = 8;
var bytes = buffer.byteLength;
console.log(bytes);

**Comment by Jugolo** [comment]
It is correct it should be undefined. Number is converted to Number object
and when trying to get property length from that object it should return
undefined becuse that prototype not exsist.

tir. d. 19. feb. 2019 20.57 skrev RBRi <notifications@github.com>:

**Comment by manishmotwani3** [comment]
I was automatically generating tests to verify if the implementation satisfies the constraint: "If O does not have an [[ArrayBufferData]] internal slot, throw a TypeError exception." described in the specification of _get ArrayBuffer.prototype.byteLength_ property. 
I suppose your reasoning of the generated test (described above) is correct and it can not actually verify if the implementation satisfies the constraint. Following test case shows a correct way to do that and it passes in Rhino by throwing TypeError. 

const proto = ArrayBuffer.prototype;
const desc = Object.getOwnPropertyDescriptor(proto, 'byteLength');
const num = 8;
try {
  var bytes = desc.get.call(num);
  console.log(bytes);
}
catch(e)
{
  console.log(e instanceof TypeError);   //  true (if implementation is correct)
}
