### ISSUE TITLE
Incorrect comment node position

### ISSUE THREAD

**Issue by nabice** [mozilla/rhino#533]
Here move all comment nodes to root node
https://github.com/mozilla/rhino/blob/33ac8131afdee4ba24b37929623370aeae3ea7ca/src/org/mozilla/javascript/Parser.java#L699-L701

When we change the parent of comment node:
https://github.com/mozilla/rhino/blob/33ac8131afdee4ba24b37929623370aeae3ea7ca/src/org/mozilla/javascript/ast/AstNode.java#L250-L264
`setRelative` do not work fine.

https://github.com/mozilla/rhino/blob/33ac8131afdee4ba24b37929623370aeae3ea7ca/src/org/mozilla/javascript/ast/AstNode.java#L255-L258

**Comment by rbri** [comment]
Can you please add a more general description of your problem and some kind of test case  / sample code.

**Comment by nabice** [comment]
sample code:
`function a() {
    //testtest                                                                                                         
   function b() {
        //password                                                                                                     
    }
}`

Absolute Position of `//password` should be 56, but 23 we got
