### ISSUE TITLE
proguard problem about  rhino in Android

### ISSUE THREAD

**Issue by currydou** [mozilla/rhino#540]
compile 'io.apisense:rhino-android:1.0'
  
TextView resultTextView = findViewById(R.id.result_text_view);
    String currentText = resultTextView.getText().toString();
    boolean valid = checkForValidity();
    double result=0;
    if(valid){
        ScriptEngine engine = new ScriptEngineManager().getEngineByName("rhino");
        try{
            result = (double)engine.eval(currentText);
        }catch(Exception e){
            Toast.makeText(this,"Exception Raised",Toast.LENGTH_SHORT).show();
        }
        currentText = currentText +"\n"+ "="+(result);
    }
    resultTextView.setText(currentText);

NullPointerException after proguard 

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object javax.script.ScriptEngine.eval(java.lang.String)' on a null object reference

i tried these.But failed.
-keep class org.mozilla.** { *; }
-keep class javax.script.** { *; }

**Comment by gbrail** [comment]
I don't have proguard or know much about it.

I do know that "rhino" was a supported script engine in old versions of Java, but it hasn't been for a while. So it's likely that "getEngineByName" is correctly returning null.

**Comment by PragyaSingla** [comment]
I am getting same issue after proguard. Getting null pointer exception while evaluating engine

val engine = ScriptEngineManager().getEngineByName("javascript")
engine.eval("") // at line line

**Comment by tonygermano** [comment]
I don't think this issue is related to anything in this repository.

https://github.com/APISENSE/rhino-android

This mentions at the bottom of the README that Proguard will cause issues.

**Comment by tonygermano** [comment]
I think this issue can be closed as it is basically half of the issues opened against the APISENSE/rhino-andriod repository.

https://github.com/APISENSE/rhino-android/issues/1
https://github.com/APISENSE/rhino-android/issues/4
https://github.com/APISENSE/rhino-android/issues/8
https://github.com/APISENSE/rhino-android/issues/10
 https://github.com/APISENSE/rhino-android/issues/11

The workaround in issue 10 is to use Rhino directly instead of the apisense ScriptEngine with Proguard.

**Comment by tonygermano** [comment]
And https://github.com/APISENSE/rhino-android/issues/8#issuecomment-592074381 indicates it was resolved by an Andriod SDK update.

**Comment by p-bakker** [comment]
Assuming resolved as per comments by @tonygermano
