### ISSUE TITLE
Missing downloadable jar and zip in the latest release, 1.7.10

### ISSUE THREAD

**Issue by chenrui333** [mozilla/rhino#559]
It looks like that we missed the downloadable jar and zip files in the latest release.

![image](https://user-images.githubusercontent.com/1580956/58049493-02a1c380-7b1b-11e9-9c41-21de0465a8d3.png)

**Comment by gbrail** [comment]
OK. Please note that this is the release from last April, newly updated on GitHub.

**Comment by chenrui333** [comment]
That is interesting to know! :)

**Comment by chenrui333** [comment]
Sounds like 1.7.9 is still the latest?

**Comment by gbrail** [comment]
No -- 1.7.10 is still the latest release. 1.7.11 will be available in about
a week unless someone turns up a big regression. Check out the "1.7.11 RC2"
release on GitHub and also on Maven Central.
