### ISSUE TITLE
Cannot execute for loop statement

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#563]
When Rhino execute the following code, the for loop statement cannot be executed. This happens in Rhino 1.7R3, 1.7R4, 1.7R5, 1.7.9, 1.7.10.

```
function foo(argc){
    for (key in argc){
          print(argc[key]);
     }
}

foo("hello");
```

**Comment by gbrail** [comment]
This works fine in 1.7.11.

**Comment by yeguixin** [comment]
@gbrail I tested in the latest rhino version 1.7.11. This is the same problem.

**Comment by gbrail** [comment]
How are you invoking Rhino? This is one of those things that works when the
language version is set to VERSION_ES6, or with the "-version 200" flag to
the Rhino command line tool.

**Comment by yeguixin** [comment]
Thanks @gbrail  Do it only work when the language version is ES6 or higher?

**Comment by gbrail** [comment]
Yes. I'm sorry, I don't recall who made this change or why it doesn't work
with other language levels -- there might be some others on the list who
could do some research on that.
