### ISSUE TITLE
Index of for-in statement starts from 1 not 0.

### ISSUE THREAD

**Issue by Implementist** [mozilla/rhino#566]
**When I run the following case the index starts from 1. It should be 0.**
```
var array = new Uint8Array(3);
print(array.length);
for (var a in array){
    print(a);
}
```
**The result is:**
```
3
1
2
```
**This problem shows in version 1.7.9**

**Comment by gbrail** [comment]
I don't see this happening on 1.7.11 -- it correctly starts at zero.
