### ISSUE TITLE
Can Array.prototype.push.apply() function pass argument of function type?

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#569]
> Testcase

```
  1 function foo(array){
  2    var a = [0,1,2];
  3    Array.prototype.push.apply(array, a);
  4    print(array);
  5 }
  6
  7 var NISLParameter0 = function(){
  8    print("run to this");
  9 };
 10
 11 //var NISLParameter0 = [2,1,0];
 12
 13 foo(NISLParameter0);
```

> Outputs

function () {
    print("run to this");
}

I tested in the latest version.

**Comment by p-bakker** [comment]
Your testcase is incorrect: .apply(...) expects an array of values as second parameter. If you don't want to wrap the function value in an array, use .call(...) instead
