### ISSUE TITLE
A SyntaxError that Rhino cannot throw when parsing

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#571]
#### Test case:

```
var foo = function (result) {
        if(false) {
                return509..prototype.call({
                        result: 24
                });
        }
        return result;
};
foo(false);
```

#### Command:
> java -jar rhino-[version].jar -debug -version 200 testcase.js

When executing the above testcase, Rhino doesn't report the SyntaxError (Line 3), while other JS engines such as SpiderMonkey, V8 can shown as follows.
#### V8 outputs:
> test/testcase.js:3: SyntaxError: Unexpected token .
>                 return509..prototype.call({
>             ^
> SyntaxError: Unexpected token .

**Comment by p-bakker** [comment]
The expected syntax error being for the double dots (`..`), right?

Rhino supports (the deprecated) E4X (XML for JavaScript), where double dots are valid syntax

Are you running with E4X turned on or off?

**Comment by p-bakker** [comment]
Closing this as I've created a more narrow-focused follow-up case to properly disable all E4X extensions when E4X is disabled: #990
