### ISSUE TITLE
Can Rhino redefine the length property of Array Object?

### ISSUE THREAD

**Issue by yeguixin** [mozilla/rhino#572]
#### Test case:

```
  var foo = function () {
          var arr = [];
          print(arr.length);
          Object.defineProperty(arr, "length", {
                  get: function(){
                          return 11;
                  }
          });
          print(arr.length);
  };
 
  foo();
```

#### Command:
> java -jar rhino-[version].jar -debug -version 200 testcase.js

> Outputs: 
> 0
> 11

This testcase shows that rhino can redefine get method (Line 4 - 8), while other JS engines such as SpiderMonkey, V8 cannot.

**Comment by rbri** [comment]
Made a fix for this.

**Comment by p-bakker** [comment]
Duplicate of #574
