### ISSUE TITLE
An error should be thrown when defining a property for a read-only variable in strict mode.

### ISSUE THREAD

**Issue by Implementist** [mozilla/rhino#573]
As the title suggests, the testcase is:
```
var func = function (number) {
    "use strict";
    number.snippetText = "";
};
func(-334918463);
```
The defination and assignment at the third line leads to an exception when I run this testcase in V8 and SpiderMonkey. But Rhino doesn't throws any exception.

**Comment by ty5491003** [comment]
@rbri Please have a look this, i think this, I think it might be a implementation bug of rhino.

**Comment by rbri** [comment]
The fix for this seems simple, but it shows another problem. Will try to build a fix.

**Comment by Implementist** [comment]
@ty5491003 Thanks for your assistance.

**Comment by rbri** [comment]
Can you please leave this open until i have a fix ready.
