### ISSUE TITLE
Surplus parameters should be ignored

### ISSUE THREAD

**Issue by Implementist** [mozilla/rhino#581]
According to ES standard 5.1 Chapter `15.5.4.11`, `String.prototype.replace(searchValue, replaceValue)` should be called with two parameters and surplus parameters should be ignored.

**The testcase is:**
```
var func = function (argument) {
    return argument.replace("NonCommercial", "NCpattern", "($28,");
};
var Parameter0 = ";W.b[V";
func(Parameter0);
```

**The output is:**
```
js: uncaught JavaScript runtime exception: SyntaxError: invalid flag after regular expression
```

**This error shows with version 1.7.11.**

**Comment by rbri** [comment]
Made a fix for this.
