### ISSUE TITLE
The Enumerable Issue when new Object

### ISSUE THREAD

**Issue by YaoHouyou** [mozilla/rhino#582]
### Testcase:
````
var foo = function () {
	var obj = new Object("z");
	var p = obj.propertyIsEnumerable('0');
	print("Property '0' is Enumerable: " + p);
};
foo();
````
### Command:
`java -jar ./rhino/rhino-1.7.11.jar -debug -version 200 testcase.js`
### Output:
`Property '0' is Enumerable: false`

### Expected output:
`Property '0' is Enumerable: true`

### Description:
According to ECMAScript-262, the value of p should be “true”, but rhino outputs “false”. Does rhino support the ECMAScript-262 standard in this case?

**Comment by rbri** [comment]
Made a fix for this.
