### ISSUE TITLE
Map and Set don't work with concatenated strings

### ISSUE THREAD

**Issue by cleiner** [mozilla/rhino#583]
I have been trying to run some third-party code on Rhino 1.7.11 and noticed that Map and Set don't always behave as expected. Here are two test cases to reproduce the issue:

```javascript
  var myMap = new Map([['key1', 'value1'], ['key2', 17]]);
  for(let i = 1; i <= myMap.size; i++) {
    let key = 'key' + i;
    print(myMap.get(key));
  }
```
Expected output: `value1`, `17` | Actual output: `undefined`, `undefined`

```javascript
var mySet = new Set(['word1', 'word2']);
for(let i = 0; i <= mySet.size; i++) {
  let value = 'word' + i;
  print(mySet.has(value));
}
```
Expected output: `false`, `true`, `true` | Actual output: `false`, `false`, `false`

Due to the string concatenation, Rhino passes a ConsString instance to the NativeMap/NativeSet methods which is of course not equal to the String that was added to the collection initially.

Unlike #247 and #496 there's no obvious or intentional Java-interop here, so I hope this warrants a separate issue.

**Comment by rbri** [comment]
Will try to fix that
