### ISSUE TITLE
Fallback to interpreter fails when using a reader to compile

### ISSUE THREAD

**Issue by emukidid** [mozilla/rhino#592]
When Context.compileImpl is called with a Reader rather than a String to supply the source, if the compilation fails due to ClassFileFormatException and we try to use the interpreter for a second attempt, the second parse on [this line](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Context.java#L2538) will fail as the Reader would've already run through all available data.

One possible workaround is to comment out [this line](https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/Context.java#L2516) so that we always have the source in the String rather than the Reader.

**Comment by rbri** [comment]
have made a possible fix for this- please have a look

**Comment by emukidid** [comment]
The change seems fine, but personally when I fixed it locally (as I needed an immediate fix) I just made it always read into a String from the reader if it was in use and just re-used that. I mean at some point you're going to read from the Reader into a String anyway, why not just do it earlier and keep it around for both cases.
