### ISSUE TITLE
ParseInt() returns NAN,0 for some numbers

### ISSUE THREAD

**Issue by mdukehall** [mozilla/rhino#594]
https://github.com/mdukehall/javascript-algorithms/blob/master/reverseint.js
Running this in rhino works fine for most numbers.
'008', '009' return as 0 and '-900' returns as NaN.

**Comment by moreheadm** [comment]
I'm not a normal contributor but I took a look at this today. What's happening in that Rhino assumes the number is octal, and parses up to the invalid character.

ES5 says that leading 0s should not be interpreted to mean the string is octal (https://www.ecma-international.org/ecma-262/10.0/index.html#sec-parseint-string-radix).

I'll submit a PR for this.
