### ISSUE TITLE
NoSuchMethod when using JavaAdapter

### ISSUE THREAD

**Issue by SoulSen** [mozilla/rhino#598]
```js
var WebSocketClient = org.java_websocket.client.WebSocketClient

var WSClient = new JavaAdapter(WebSocketClient, { 
    onOpen: function(handshakeData) {},
    onMessage: function(message) {
        var json = Utilities.getJsonString(message)
        if (json) {
            if(json["user_joined"]) {
                ChatLib.command("party " + json["userJoined"])
            }
        } else {
            // If errors its prob this.send()
            send(JSON.stringify({"error": "invalid json returned"}))
        }
    },
    onClose: function(code, reason, remote) {},
    onError: function(ex) {}
})
``` 
I'm using a websockets library which is from https://github.com/TooTallNate/Java-WebSocket but whenever doing this I get this error https://mystb.in/newanuguxa.coffeescript. I'm trying to subclass [this](https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/java/org/java_websocket/client/WebSocketClient.java). This confuses me since when subclassing other classes they work fine.

**Comment by liu1352183717** [comment]
Attempt to write to field 'int c.m.b.e.a$b.b' on a null object reference

java.lang.NullPointerException: Attempt to write to field 'int c.m.b.e.a$b.b' on a null object reference

**Comment by liu1352183717** [comment]
Did you solve it, I also encountered the same problem?

**Comment by XeroAlpha** [comment]
> Did you solve it, I also encountered the same problem?

I don't think you have the same problem. NullPointerException and NoSuchMethod are not the same. I will talk to you with QQ.

**Comment by p-bakker** [comment]
The class you're trying to extend doesn't have a default constructor and you're not passing in any constructor arguments (last param to the new JavaAdapter(...) call, after your implementation object)
