### ISSUE TITLE
Syntax error with comments in array declaration

### ISSUE THREAD

**Issue by indradoneill** [mozilla/rhino#602]
The following javascript generates a syntax error when recording comments is enabled: var array = [/* */];

It can be solved by removing the "break" at the end of the "if (compilerEnv.isRecordingComments())" block in the method peekToken() in Parser.java .

**Comment by PalAditya** [comment]
Hi, this project seems quite interesting. Can I have a go at this issue, please?

**Comment by gbrail** [comment]
Of course you can! This project rarely suffers from an excess of
contributors. I'll keep in mind that you are looking at this and feel free
to reach out if you have questions.
