### ISSUE TITLE
Concat method in new Rhino jar

### ISSUE THREAD

**Issue by saurabhtct** [mozilla/rhino#613]
While using rhino-1.7.11.jar in concat of two arrays , concatenated array is not getting flattened. As advised in some blogs, tried using arrayname[Symbol.isConcatSpreadable] = true; after setting Context.VERSION_ES6. But this can be used only in script, is there any way to use it in Java code. Here is the code i tried.

import org.mozilla.javascript.Context;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;

public class JavaScriptExample {
	public static void main(String[] args) {
		String evaluationScript = " var cars = [\"Saab\", \"Volvo\", \"BMW\"];" + "var models = [2008, 2010];"
				+ "cars[Symbol.isConcatSpreadable] = false;" + "cars.concat(models);";
		Context cx = Context.enter();
		cx.setLanguageVersion(Context.VERSION_ES6);
		try {
			Scriptable scope = cx.initStandardObjects();
			// Pass the Stock Java object to the JavaScript context
			Object wrappedOut = Context.javaToJS(System.out, scope);
			ScriptableObject.putProperty(scope, "out", wrappedOut);
			Object obj = cx.evaluateString(scope, evaluationScript, "EvaluationScript", 1, null);
			System.out.println(obj);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

**Comment by p-bakker** [comment]
Tested this withy the latest master and see no problems here, so closing this case

Note: you used `cars[Symbol.isConcatSpreadable] = false;` instead of `cars[Symbol.isConcatSpreadable] = true;`) in your sample
