### ISSUE TITLE
concat of two arrays not working after upgrading to rhino.jar from js.jar

### ISSUE THREAD

**Issue by saurabhtct** [mozilla/rhino#614]
After upgrading to rhino.jar from js.jar, concatenation of two arrays in javascript are not getting flattened. What is the best way to resolve this issue. Sample code:

import org.mozilla.javascript.Context;
import org.mozilla.javascript.Scriptable;
import org.mozilla.javascript.ScriptableObject;

public class JavaScriptExample {
	public static void main(String[] args) {
		String evaluationScript = " var cars = [\"Saab\", \"Volvo\", \"BMW\"];" + "var models = [2008, 2010];"
				 + "cars.concat(models);";
		Context cx = Context.enter();
		try {
			Scriptable scope = cx.initStandardObjects();
			Object wrappedOut = Context.javaToJS(System.out, scope);
			ScriptableObject.putProperty(scope, "out", wrappedOut);
			Object obj = cx.evaluateString(scope, evaluationScript, "EvaluationScript", 1, null);
			System.out.println(obj);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

**Comment by gbrail** [comment]
Can you tell us more about what version of Rhino you're using?

**Comment by saurabhtct** [comment]
It's rhino-1.7.10.

**Comment by p-bakker** [comment]
Tested this with the latest code on master and the output of your sample code is the follow array: ["Saab","Volvo","BMW",2008,2010]

So it looks like this issue has been solved
