### ISSUE TITLE
How Can I reinit Packages

### ISSUE THREAD

**Issue by TIIEHenry** [mozilla/rhino#618]
when I load dex on android , I found that I can`t use Packages to get the JavaClass.I received JavaPackage unexpectedly.So I found Packages are inited in Content.enter,but I dont know how to fix it.Could someone help me?

**Comment by p-bakker** [comment]
Closing this issue as it doesn't contain enough info for triaging. 

If you feel like there's an issue in Rhino, please reopen with more info
