### ISSUE TITLE
Extending class without a default constructor

### ISSUE THREAD

**Issue by Anuken** [mozilla/rhino#627]
I have a class with some methods that I would like to extend in JS. Code:

```java
package com.mypackage;

class C{

    public C(String name){ /* ... */ }

    public void run(){ /** ... */ }
}
```

My goal is to create an anonymous class which overrides a few methods. In Java, this would look like the following:
```java
new C("name"){
    public void run(){ /** ... */ }
}
```

I have tried the following approaches to get it implemented in JS. Assume the class "C" is imported:

- `new C("name"){ run: function(){ /** ...**/ } }`: throws `Java constructor for "com.mypackage.C" with arguments "string,object" not found.`
- `new JavaAdapter(C("name"), {run: function(){ /** ...**/ }})`: throws `TypeError: Argument 0 is not Java class: <instance of C>.`
- `new JavaAdapter(C, "name", {run: function(){ /** ...**/ }})` throws `Argument 1 is not Java class: <instance of C>. (global.js#391)`
- `new JavaAdapter(Block, {run: function(){ /** ...**/ }})`: throws `Wrapped java.lang.NoSuchMethodException: adapter1.<init>(org.mozilla.javascript.Scriptable, org.mozilla.javascript.ContextFactory`

Most likely related to #598.

**Comment by FalseHonesty** [comment]
`JavaAdapter` mandates that that any arguments passed after the implementation object will be passed on to the super constructor. In this case, I believe that the correct usage would be:
```js
new JavaAdapter(C, {run: function(){ /** ...**/ }}, "name")
```

**Comment by Anuken** [comment]
That works, thanks!

**Comment by michaschulze** [comment]
I have more or less the same problem and my to be extended class has to constructors which are overloads. How can I control which one of these constructors gets called? For example, I would like to subclass org.eclipse.swt.widgets.Dialog and Dialog has two constructors. Till now, I had no success in subclassing it with the help of JavaAdapter. Do you have any idea how this could be reached?
