### ISSUE TITLE
I developed a JS type static analysis library based on this

### ISSUE THREAD

**Issue by 823984418** [mozilla/rhino#634]
[Library](https://github.com/823984418/JsType).
I open source by GPL3.
What do I need to do for calling Rhino MPL?(such as copy MPL?)

**Comment by gbrail** [comment]
If you're asking a licensing question, especially about GPL compatibility,
I'm afraid that I can't answer you other than to say, please consult a good
IP attorney with experience in open source. If someone else would like to
chime in, then please do!

**Comment by p-bakker** [comment]
Closing this issue as it's not related to Rhino directly
