### ISSUE TITLE
A possible bug about this in strict mode.

### ISSUE THREAD

**Issue by YiWen-y** [mozilla/rhino#639]
###### Revision
rhino-1.7.11

###### Test case
```
var NISLFuzzingFunc = function() {
    "use strict";
    print(this);
};
NISLFuzzingFunc();
```

###### Execution steps
    java -jar rhino-1.7.11.jar -debug -version 200 testcase.js

###### Output
    [object global]

###### Expected behavior
    undefined

###### Description
According to ES standard, `this` is not converted to the global object in strict mode, the initial value of `this` should be undefined. However, when running this test case blow, the output of rhino is `[object global]`.
The references are as follows:
http://www.ecma-international.org/ecma-262/5.1/index.html#sec-C

**Comment by rbri** [comment]
This is an duplicate of #442.
