### ISSUE TITLE
Rhino 1.7.7.2 incorrect date on readme

### ISSUE THREAD

**Issue by leela52452** [mozilla/rhino#643]
[Rhino 1.7.7.2](https://github.com/mozilla/rhino/tree/Rhino1_7_7_2_Release#releases) incorrect date on [releases](https://github.com/mozilla/rhino/tree/Rhino1_7_7_2_Release#releases) section

**Comment by p-bakker** [comment]
It's sightly off, but so are others. Not worth it to fix imho, so closing this issue. If you feel strongly about this, please provide a PR
