### ISSUE TITLE
A question about String.prototype.search

### ISSUE THREAD

**Issue by YiWen-y** [mozilla/rhino#651]
###### Revision
rhino-1.7.11

###### Test case
```
var NISLFuzzingFunc = function() {
    print(typeof String.prototype.search);
    print(String.prototype.search(1, 1));
};
NISLFuzzingFunc();
```

###### Execution steps
    java -jar rhino-1.7.11.jar -debug -version 200 testcase.js

###### Output
```
function
js: uncaught JavaScript runtime exception: SyntaxError: invalid flag after regular expression
```

###### Expected behavior
```
function
-1
```

###### Description
The ES standard does not stipulate a processing method when String.prototype.search has two parameter, but other engines execute normally after ignoring illegal parameters, such as v8, Spider Monkey, and chakra. For rhion, it throw a SyntaxError exception when this happens. Is this a bug about rhino?

**Comment by rbri** [comment]
Will try to let Rhino work like the rest

**Comment by rbri** [comment]
Have added a test case for this - seems to be no longer a problem with the current sources.

**Comment by rbri** [comment]
Can you please review the test and maybe close this.
