### ISSUE TITLE
Is Mozilla Rhino based JSR-223 (javax.script) Engine Coming Back?

### ISSUE THREAD

**Issue by CanIGetaPR** [mozilla/rhino#655]
Now that Java has deprecated and then removed the Nashorn JSR-223 (javax.script) engine, are there any plans to make a new Rhino one so that built-in javascript can continue and people using the javax script API don't have to switch to using pure rhino code?

**Comment by p-bakker** [comment]
Yes, since [v1.7.13](https://github.com/mozilla/rhino/releases/tag/Rhino1_7_13_Release)
