### ISSUE TITLE
An issue about Array.prototype.map

### ISSUE THREAD

**Issue by YiWen-y** [mozilla/rhino#659]
###### Revision
rhino-1.7.11

###### Test case
```
var f = function() {
    var obj = [0,1];
    var a = obj.map(function() {return obj;});
    print(a);
};
f();
```

###### Execution steps
    java -jar rhino-1.7.11.jar -debug -version 200 testcase.js

###### Output
 ```
0,1,
```
###### Expected behavior
 ```
0,1,0,1
```

###### Description
According to ES Standard, each element in the array `obj` should execute the callback function of `Array.prototype.map`. Therefore, when running this testcase blow, the output of rhino should be `0,1,0,1`.
The references are as follows:
ecma-international.org/ecma-262/5.1/index.html#sec-15.4.4.19

**Comment by tonygermano** [comment]
The problem actually appears to be with the print function, which is not part of any standard.

This test case produces the same result as your example:
```
var f = function() {
    var obj = [0,1];
    var a = [obj,obj];
    print(a);
};
f();
```

Whereas this test case:
```
var f = function() {
    var obj = [0,1];
    var a = obj.map(function() {return obj;});
    print(JSON.stringify(a));
};
f();
```

Produces the expected result of:
```
[[0,1],[0,1]]

**Comment by rbri** [comment]
Can reproduce this here. Will try to fix it.
