### ISSUE TITLE
Add support for javax.script.ScriptEngineManager (JSR-223)

### ISSUE THREAD

**Issue by Horcrux7** [mozilla/rhino#660]
With JDK 15 the support for Nashorn is removed. It will be nice if there will be a simple replacement of the JavaScript Engine.

The follow code return null also if I add the latest Rhino version to the classpath.

```java
import javax.script.ScriptEngine;
import javax.script.ScriptEngineFactory;
import javax.script.ScriptEngineManager;
...
ScriptEngineManager factory = new ScriptEngineManager( getClass().getClassLoader() );
ScriptEngine engine = factory.getEngineByName( "JavaScript" );
```

**Comment by Horcrux7** [comment]
The follow Project can be a good start point: https://github.com/zeroboo/java-scripting-rhino-jdk8/

**Comment by A-Herzog** [comment]
There is also a bit newer version of java-scripting-rhino-jdk8 here:
https://mvnrepository.com/artifact/cat.inspiracio/rhino-js-engine/1.7.10

In general, the wrapper for Rhino works, but in my use case (many calls of always the same short script) it provides a very bad performance, because a string is recompiled with every script call (see `printSource` in `RhinoScriptEngine.java`). If this is a cached, calling Rhino gets much faster. My patched version of java-scripting-rhino-jdk8 can be found here:
https://github.com/A-Herzog/Warteschlangensimulator/blob/master/Simulator/tools/Rhino/workspace-rhino_fast.zip
(Sorry, I don't know much about how Rhino works internally, so this is all I can offer.)
I would be pleased to see Rhino ensuring the future of a JS engine in Java.

**Comment by gbrail** [comment]
Taking the work that you have already done and merging it with the existing
Rhino code so that it can be used easily with vanilla Rhino would be a
great way for someone new to the project to contribute!

**Comment by A-Herzog** [comment]
Thank you for your encouraging answer. I really would like to help, but I'm not very experienced in Git so I would not dare to integrate the code in such a relevant project (even if of course using a separate branch). But if a base version of script engine would be part of Rhino, I could apply my optimizations (and also help to clean up and Javadoc the code a bit more). On my workloads (running the same small script many times) I can bring Rhino to about 35% of the Nashorn performance. That's not perfect but compared to the default Rhino version (as far as I remember something like 1% of Nashorn performance - again: on my workload, not in general) a big step.

As Nashorn saidly gets removed from default JDK soon, I would really like to see a fast, general available and easy to use Rhino version.

There is a second aspect to check before including the code. The old Rhino script engine code still says "Copyright (c) 2006, Sun Microsystems, Inc.". I don't know the current license state of this code and I don't know how to find out the path of this code from Sun to Github. I think this must be checked first in any case.

**Comment by Horcrux7** [comment]
@A-Herzog I think not that the license is compatible that you can simple copy it. It must start from new.

@gbrail Do you would accept a PR with the feature? Are there any requirements like a preferred package?

**Comment by gbrail** [comment]
I started working on this in a new PR:

https://github.com/mozilla/rhino/pull/703

However, I have to get back to other things and I don't use ScriptEngine in real life so I don't know what I don't know.

@Horcrux7 if you have an opportunity, can you please try this out and finish it according to the requirements of people here then that'd be a nice contribution! 

I'm happy to have you fork this into a new PR and I can take a look.

**Comment by Horcrux7** [comment]
Thanks for the start. Currently it does not work. I will try to fix it. Can take some days.

**Comment by Horcrux7** [comment]
@gbrail My mistake. I have not see that you habe create a new artifact rhino-engine.jar. I have test it first with https://jitpack.io/ which has not populated this extra jar file. After building it locally I was able to run the most tests. Can be a problem with the build script or jitpack.io.

My testing show that there is some behavior difference with `Bindings`. The Nashorn Engine has use the `get` method on the fly if needed. The Rhino engine is calling `entrySet` in `applyBindings`. This required that all possible values must be evaluated. Also if never needed. This can be a large performance decrement.

A typical use case for a JavaScript engine is that an application has its own DSL with a large count of objects. A customer can add some scripts for customizing the application. In this use case only a very small count of the keywords is used in the script.

Is it possible to create a wrapper object that wraps the Bindings that can be injected without iterating over all keys?

**Comment by gbrail** [comment]
Thanks for testing this -- I understand what you mean about the bindings. I'll update the PR in a way that makes more sense and doesn't copy everything.

**Comment by gbrail** [comment]
I updated the PR:

https://github.com/mozilla/rhino/pull/703

could you give it another try? The Bindings work the way that you expect. I think that Nashorn has a different set of built-in functions and probably some other differences -- I'm interested in understanding what Nashorn does differently that we should emulate.

Thanks!

**Comment by Horcrux7** [comment]
Great, all my tests are green now. Will this be part of the next release?

**Comment by Horcrux7** [comment]
I see that in the `publishing` there is no reference to the artifact `rhino-engine`. Is this what you want?

**Comment by garydgregory** [comment]
When is it fair to expect a new release with this and #703 ?

**Comment by gbrail** [comment]
I just updated an issue for this:

https://github.com/mozilla/rhino/issues/734

I don't expect to do it for a few weeks -- I'm targeting early August. At
that point, we might call the one after it "1.8" and open up a few bigger
changes.

**Comment by p-bakker** [comment]
Closing, as v1.7.13 has been released a while ago

**Comment by alexanderankin** [comment]
any hints on where these actually landed in maven central? they are not in rhino or rhino runtime jars. they appear in the source jar for rhino, oddly enough. I checked with "jar tf"
