### ISSUE TITLE
A possible issue about `String.prototype.split` of Rhino.

### ISSUE THREAD

**Issue by ty5491003** [mozilla/rhino#664]
### Testcase
```js
var a = '123 456 789'.split(undefined, 0);
print(a);
```

### Expect Output
[]

### Rhino Actual Output
['123 456 789']

### Other JS Engines Output
[]

### Rhino Version
1.7.11

### ECMA Script Standard
In ES Standard( 5.1/6/10), i see `If lim = 0, return A.` , it means that if the second parameter of split function is `0`, the return code should be a empty list, but rhino give me a not-empty list. So i suspect it's a bug of rhino's implementation of split function. 

Please let me know the result whether this is a bug or not. Looking forward to your reply, thanks! :laughing:

**Comment by rbri** [comment]
this is fixed with commit 7397f279bbe8d8ea38da2b2adf2f1d24367d5821

**Comment by ty5491003** [comment]
@rbri I get it, thanks for your work!!!
