### ISSUE TITLE
A possible issue about Object.assign

### ISSUE THREAD

**Issue by YaoHouyou** [mozilla/rhino#667]
According to ES6, when try to set propertiy to first parameter of Object.assign, if it is failed, a TypeError should be throw. However, rhino does not throw any exception.
### Testcase:
``` javascript
Object.assign("%ED%AF%BF", "S$o~>ixg2lC?5fn");
```
### Command:
```shell
java -jar rhino/rhino-1.7.12.jar -debug -version 200 testcase.js
```
### Output:
```
```

### Expected output:
Throw TypeError exception.

### References:
http://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.assign
http://www.ecma-international.org/ecma-262/6.0/index.html#sec-set-o-p-v-throw

**Comment by p-bakker** [comment]
works correctly in the latest master
