### ISSUE TITLE
Rhino 1.7R4 produce java.lang.StackOverflowError when opt != -1

### ISSUE THREAD

**Issue by dimzon** [mozilla/rhino#67]
I'm trying to run uglifyJS in Rhino 1.7R4

this command line produce valid output:
java -cp js.jar org.mozilla.javascript.tools.shell.Main -opt -1 rhinoUglifyJS.js  

this command line produce java.lang.StackOverflowError
java -cp js.jar org.mozilla.javascript.tools.shell.Main -opt 0 rhinoUglifyJS.js  

I uploaded rhinoUglifyJS.js to http://www.sendspace.com/file/h42zif

**Comment by p-bakker** [comment]
Closing this issue as it looks to be configuration related and not an issue in Rhino itself
