### ISSUE TITLE
Locale is always French (at least on French platforms)

### ISSUE THREAD

**Issue by hervegirod** [mozilla/rhino#680]
I have a PC for which default Locale is "fr", and even if I set 
`context.setLocale(<some locale")` to any other locale, I still have messages in French. It work if I do
this:
```
Locale locale = new Locale("");
context.setLocale(locale);
```
The reason is that there is only the following resource files on Rhino 1.712:
- `org.mozilla.javascript.resources.Messages`
- `org.mozilla.javascript.resources.Messages_fr`
And the code in Rhino does:
```
ResourceBundle rb = ResourceBundle.getBundle("org.mozilla.javascript.resources.Messages", locale);
```
Which means that Rhino can only find the "fr" resource.

**Comment by gbrail** [comment]
Can you suggest how we fix this?

Also, if anyone is looking to contribute to Rhino, someone generously
contributed the French message bundle many years ago and I'm sure it's up
to date. And obviously there are no other languages supported. Translating
the messages into the language you know best might help a lot of developers!

**Comment by gbrail** [comment]
And sorry, I meant, I'm sure it's NOT up to date!

**Comment by rbri** [comment]
I can contribute a German translation

**Comment by hervegirod** [comment]
Hello, if the French localization is not up to date, I can contribute to make it up to date with the last version. Also I don't think my own specific fix is the right way to do it in the library, but I will look at the code and try to propose something to fix it.

**Comment by gbrail** [comment]
I'm still not sure I understand the original issue. It sounds like the
problem is that the resource bundles aren't set correctly in the classpath,
so French messages are being displayed when they shouldn't. Is that the
case?

Otherwise, today Rhino only supports English and French messages and unless
someone contributes another translation (like German -- thanks!) then those
are the only choices we have.

**Comment by hervegirod** [comment]
Yes, that's exactly that! Maybe it's only when the machine is configured as French though.
