### ISSUE TITLE
An issue about the Object construtor

### ISSUE THREAD

**Issue by NWU-NISL** [mozilla/rhino#697]
Testcase:
```javascript
var NISLFuzzingFunc = function(nislMutationParameter0, nislMutationParameter1){
    var t = Object.create(nislMutationParameter0, nislMutationParameter1);
    print(t.toString);
    print(t.valueOf);
    t = Object(t);
    print(t.toString);
    print(t.valueOf);
    var a = t.toString();
    print(a);
}
var nislMutationArgument0 = null;
var nislMutationArgument1 = undefined;
NISLFuzzingFunc(nislMutationArgument0, nislMutationArgument1);
```

Output:
undefined
undefined
function toString() { [native code for Object.toString, arity=0] }
function valueOf() { [native code for Object.valueOf, arity=0] }
[object Object]

 
Expected Output:
undefined
undefined
undefined
undefined
JavaScript runtime exception: TypeError: Cannot find default value for object.

Description:
When executing the above testcase, Rhino modifies the "toString" and "valueOf" properties of the object 't' at line 5. But according to ECMAScript-262,  the Object constructor should return the argument directly  if the argument is an Object.  So, it seems that Rhino shouldn't modify the "toString" and "valueOf" properties and throw a TypeError at line 8;

Contributor: @yaohouyou @QuXing9

**Comment by p-bakker** [comment]
Tested with latest master and seems to work correctly now
