### ISSUE TITLE
Object.assign doen't update property in time

### ISSUE THREAD

**Issue by RuralHunter** [mozilla/rhino#711]
If the property definition is changed during the assign progress, rhino doesn't reflect the change in time. The code below(LanguageVersion=Context.VERSION_ES6) ends in different results with rhino and browser(Firefox):
```javascript
var oa=Object.defineProperty({},"a", {
                        enumerable: true,
                        get: function () {
                            Object.defineProperty(this, "b", {
                                value: 3,
                                enumerable: false
                            });
                        }
                    });

var ob=Object.assign(oa, {b: 2});
Object.assign({b: 1},ob);
print('ob.b='+ob.b+', enum='+Object.getOwnPropertyDescriptor(ob,"b").enumerable);
```
Rhino: ob.b=2, enum=true
Firefox: ob.b=3, enum=false

The problem is at the second call of the Object.assign. ob.a has a getter function which re-defines property b. During the value assignment, the getter is called. In rhino, the the new definition of b doesn't take effective so that ob.b still holds the old definition.

**Comment by rbri** [comment]
Am 11. Juni 2020 09:03:30 MESZ schrieb Rural Hunter <notifications@github.com>:
>If the property definition is changed during the assign progress, rhino
>doesn't reflect the change in time. The code
>below(LanguageVersion=Context.VERSION_ES6) ends in different results
>with rhino and browser(Firefox):
>```javascript
>var oa=Object.defineProperty({},"a", {
>                        enumerable: true,
>                        get: function () {
>                            Object.defineProperty(this, "b", {
>                                value: 3,
>                                enumerable: false
>                            });
>                        }
>                    });
>
>var ob=Object.assign(oa, {b: 2});
>Object.assign({b: 1},ob);
>print('ob.b='+ob.b+',
>enum='+Object.getOwnPropertyDescriptor(ob,"b").enumerable);
>```
>Rhino: ob.b=2, enum=true
>Firefox: ob.b=3, enum=false
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/rhino/issues/711

Nice catch, I'm on vacation at the moment. Will try to fix this next week.

**Comment by rbri** [comment]
Hi Rural,

sorry for being that late on this but i'm overloaded in my daily job.
This issue is the catch of the month (from my point of view). No idea why this was in the code for so long (since 08/2017).

Will merge the fix into core-js and inform as usual via twitter if the new HtmlUnit snapshot is out.

Again thanks for the well prepared bug report.
    Ronald

**Comment by RuralHunter** [comment]
No problem at all. Thanks for the great support all the time.

**Comment by rbri** [comment]
There is usual no need to close an issue. The issue gets closed automatically at the moment greg merges the PR into the master.
