### ISSUE TITLE
'name' and 'length' properties of Functions should be configurable

### ISSUE THREAD

**Issue by gbrail** [mozilla/rhino#715]
This is part of ECMAScript's section on Function objects (currently 19.2). A lot of test262 tests will pass if this is fixed.

Fixing this means modifying BaseFunction to not only return the right attributes but to allow those attributes to be deleted.

**Comment by rbri** [comment]
Sounds great - i guess you are already working on this....

**Comment by gbrail** [comment]
I mostly know what to do -- the "IdScriptableObject" interface makes this
harder and I'm in progress of creating an alternative based on lambdas --
but we still need to fix it in BaseFunction itself.

However, I created this so I could put the idea aside while working on
other stuff, so if you or someone else has time to try it and most
importantly figure out which of the many tests it affects, that would be a
big help! I'll put a comment here if I look at it.

**Comment by p-bakker** [comment]
@gbrail as the lambda-based stuff is in now (if I'm not mistaken), could you elaborate how the lambda stuff makes it easier?

On a sidenote: https://github.com/mozilla/rhino/issues/963 also requires changing existing implementations to be spec-compliant and while {Map,Set).size is implemented correctly from a spec point of view, I feel the IdScriptableObject approach makes the implementation a lot more cumbersome that it maybe ought to be.

I tried something like this in the init method of NativeRegExp to add the `unicode` property, skipping the creation of a NativeObject descriptor first, but the interfered:
```
        proto.setGetterOrSetter("unicode", 0, (c, s, thisObj, args) -> {
        	if (!(thisObj instanceof NativeRegExp)) return null;

        	NativeRegExp re = (NativeRegExp) thisObj;

        	return ScriptRuntime.wrapBoolean((re.getFlags() & JSREG_UNICODE) != 0);
        }, false);
        proto.setAttributes("unicode", READONLY | DONTENUM);
```

**Comment by p-bakker** [comment]
Resolved by https://github.com/search?q=repo%3Amozilla%2Frhino+a6aa8f8a29c2f62335fdcd2acda0ebc3ce732889&type=commits and https://github.com/mozilla/rhino/pull/1398
