### ISSUE TITLE
继承抽象类问题

### ISSUE THREAD

**Issue by liu1352183717** [mozilla/rhino#745]
请问如何使用JavaAdapter实现继承抽象类的功能呢？

**Comment by XeroAlpha** [comment]
请参见官方文档[Scripting_Java](https://developer.mozilla.org/zh-CN/docs/Mozilla/Projects/Rhino/Scripting_Java#JavaAdapter%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0)，如果问题已解决，请close这个Issue。Issue不是用来提问的。
