### ISSUE TITLE
An issue about String.prototype.big

### ISSUE THREAD

**Issue by NWU-NISL** [mozilla/rhino#765]
According to ES6.0, when using method [[call]] to modify 'this' of `String.prototype.big`, update 'this' into 'null' or 'undefined' will raise a TypeError. And many other methods like `String.prototype.small`, `String.prototype.fontsize`, which are defined in Annex B have the same situations. This may be an issue of Rhino.

#### version

```
1.7.12
```

#### command

```
java -jar rhino/rhino-1.7.12.jar -debug -version 200 testcase.js
```

#### testcase

```javascript
var v0 = function(){
    return String.prototype.big.call(null);
};
var result = v0();
print(result);
```

#### output

```
<big>null</big>
```

#### expected output

```
TypeError: big: 'this' is null or undefined
```

contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by rbri** [comment]
Will have a look....
