### ISSUE TITLE
An issue about the %TypedArray%.prototype.subarray().

### ISSUE THREAD

**Issue by NWU-NISL** [mozilla/rhino#768]
**Revision**

rhino-1.7.12

**Test case**

```javascript
var NISLFuzzingFunc = function(){
    var a = new Uint32Array(1)
    return a.subarray();
}
var NISLFuzzingResult = NISLFuzzingFunc();
print(NISLFuzzingResult);
```

**Execution steps**

```javascript
java -jar rhino/rhino-1.7.12.jar -debug -version 200 testcase.js
```

**Output**

```javascript
Error: invalid arguments.
```

**Expected behavior**

```javascript
Output 0.
```

**Description**

According to ES standard, the parameters of %TypedArray%.prototype.subarray() is optional,but rhino reported an error when I didn't pass parameters to this function.Therefore,I think there may be a problem here.

Contributor : @Haobin-Lee

**Comment by rbri** [comment]
Will have a look....
