### ISSUE TITLE
A question about NewTarget of String constructor

### ISSUE THREAD

**Issue by NWU-NISL** [mozilla/rhino#770]
A String object is  constructed with the keyword `new`. When calling `Object.seal` to deal with the object, a `NullPointerException` is thrown by rhino. I guess there may be something created when creating the object. Because other engines like SpiderMonkey, Hermes and jerryscript don't throw any exception, does this result in any non-portability? Or is there any information I have missed?

#### version

```
1.7.12
```

#### command

```
java -jar  rhino/rhino-1.7.12.jar -debug -version 200 testcase.js
```

#### testcase

```javascript
function main() {
var v2 = new String(123);
var p = Object.getOwnPropertyNames(v2);
for(var i in p){ 
   print(p[i],v2[p[i]]);
}
var v4 = Object.seal(v2);
print(v4);
}
main();
```

#### output

```
0 1
1 2
2 3
length 3
Exception in thread "main" java.lang.NullPointerException
```

#### expected output

```
0 1
1 2
2 3
length 3
123
```

contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by rbri** [comment]
Looks like this is no longer an issue in the current version.

**Comment by NWU-NISL** [comment]
Really? Thanks for your reply anyway. I'll try the current version.
