### ISSUE TITLE
Object.assign() should copy undefined properties, I think

### ISSUE THREAD

**Issue by dcitron** [mozilla/rhino#780]
Hi! It looks like `Object.assign()` should copy undefined properties:

```
console.log(Object.assign({"a":undefined}, {"b":undefined}))
Object { a: undefined, b: undefined }
```

However, the Rhino code is skipping undefined values:

```
          case ConstructorId_assign:
          {
            if (args.length < 1) {
              throw ScriptRuntime.typeError1("msg.incompat.call", "assign");
            }
            Scriptable targetObj = ScriptRuntime.toObject(cx, thisObj, args[0]);
            for (int i = 1; i < args.length; i++) {
              if ((args[i] == null) || Undefined.isUndefined(args[i])) {
                continue;
              }
              Scriptable sourceObj = ScriptRuntime.toObject(cx, thisObj, args[i]);
              Object[] ids = sourceObj.getIds();
              for (Object key : ids) {
                if (key instanceof String) {
                  Object val = sourceObj.get((String) key, sourceObj);
                  if ((val != Scriptable.NOT_FOUND) && !Undefined.isUndefined(val)) { // <=== HERE
                    targetObj.put((String) key, targetObj, val);
                  }
                } else if (key instanceof Number) {
                  int ii = ScriptRuntime.toInt32(key);
                  Object val = sourceObj.get(ii, sourceObj);
                  if ((val != Scriptable.NOT_FOUND) && !Undefined.isUndefined(val)) {  // <=== AND HERE
                    targetObj.put(ii, targetObj, val);
                  }
                }
              }
            }
            return targetObj;
          }
```

Is there a reason for those `!Undefined.isUndefined(val)` checks?

Thanks!

**Comment by tonygermano** [comment]
https://www.ecma-international.org/ecma-262/11.0/index.html#sec-object.assign

Section 19.1.2.1, step 4.a.iii.2 seems to indicate the check is appropriate.

**Comment by gbrail** [comment]
Thanks for the analysis of the spec. You may indeed be right.

I'm sure that there are tests in the "test262" directory for this. Some of them may be disabled (in test262.properties) which is usually a sign that we missed something. Perhaps if you try looking to see what's enabled and enabling anything that might be disabled regarding Object.assign, we might be able to quickly zero on on the correct behavior.

**Comment by tonygermano** [comment]
@dcitron I'm not experienced with reading these specs nor am I an expert on javascript internals. I do think your interpretation is correct. I am still a bit confused about how `desc` could be undefined when `nextKey` is an element of `keys`, which in turn is the list of `from.OwnPropertyKeys`. Wouldn't the property have to exist, and therefore `desc` would never be undefined, or is there some case that I'm not thinking of?

**Comment by tuchida** [comment]
Perhaps there aren't tests in the latest "test262".
https://github.com/tc39/test262/tree/b2e9dff2816cceb5ee84c0c226c50a31d01a7297/test/built-ins/Object/assign
I greped undefined in this directory.

**Comment by p-bakker** [comment]
My reading of the spec is that the `If desc is not undefined` is just a spec safeguard for the unlikely scenario where OwnPropertyKeys returns a key for which GetOwnProperty returns undefined. Not sure if that is an invariant against which the spec has put measures in place, but otherwise such a scenario could occur with a Proxy object

Regardless, the spec is pretty clear that there should NOT be a check on the value of the property, so assign should copy over properties with an undefined value

**Comment by rbri** [comment]
Sorry but i have to reopen this issue. tuchida's fix seems to introduce a new problem. Have applied this change to HtmlUnit and one library tests failed.
Spend some time to find the reason. Will make a pr with a test case.

Maybe @tuchida can have a look (please).

**Comment by p-bakker** [comment]
@tuchida are you looking into this?

**Comment by tuchida** [comment]
Yes, I look it lightly. However, I could not proceed because I was not sure which specification `Scriptable.put`, `ScriptableObject.putProperty`, etc. each corresponded to (e.g. `[[Set]]`).
Sorry, but if anyone can fix this, it would be helpful.

**Comment by dcitron** [comment]
Hi, @tuchida -- since this was all due to me in the first place, lemme take a look and see if I can come to any conclusions. I'll start with @rbri 's test case :)

**Comment by rbri** [comment]
@tuchida @dcitron great - thanks

**Comment by dcitron** [comment]
Apologies for the delay! I haven't forgotten! I'll try to get to it this coming week.

**Comment by dcitron** [comment]
Hi @tuchida and @rbri ! I have a fix that passes all `./gradelw test` tests against **rbri:assign_with_prototoype** -- in other words, it should fix #1195

Here's what I found: the current code is not perfectly following the flow specified by https://262.ecma-international.org/12.0/#sec-ordinarysetwithowndescriptor

![image](https://user-images.githubusercontent.com/46792062/176961211-c87e01a5-3f85-4f13-846b-149d8ea1551f.png)

What's happening right now (if I'm correct!) is:
- the two new `AbstractEcmaObjectOperations.put()` functions that were added in #1186 are implementing Step 2 above, and walking up to the parent (prototype) object to call _parent.putImpl(..., Receiver, ...)_
- but `ScriptableObject.putImpl()` is not creating/setting the requested property on the _Receiver_
  - in the case that `this != start` it is grabbing the parent (prototype) slot and doing nothing with it -- the ultimate call to `slot.setValue()` is a no-op if the owner and the "start" (Receiver) are not the same 

My fix involves doing the right thing at step 3.d.iv and 3.d.ii in the picture above, which means:
- if `this` is not the _Receiver_
  - if the property is a value (not a setter) and is not read-only, invoke _Receiver.putImpl()_ to allow the correct (start) object to get the intended property.

I hope any of that makes any kind of sense! In short, my change is to add this code here:

![image](https://user-images.githubusercontent.com/46792062/176962687-d801d09a-ece9-4ae7-be88-420dd9f86ce2.png)

I also made a small change to Slot.java to factor out `isReadOnly()` into a function to be called there.

Question!!! How should I proceed? I think I cannot push changes directly to **rbri:assign_with_prototoype**, right?

Should I just make my own fork and my own branch and push my changes plus @rbri's test case and make a whole new PR? What's the correct procedure here?

**Comment by p-bakker** [comment]
Have no pointers on what the best way to proceed is, just wanted to say: great analyses!

Note that this fix might also fix some test262 tests that are currently not passing. You could check that by running the test262 TestSuite and see if any such tests are reported. If yes, you can regenerate test262.properties. See https://github.com/mozilla/rhino/tree/master/testsrc for the docs about doing so

**Comment by rbri** [comment]
Many thanks!

> Should I just make my own fork and my own branch and push my changes plus @rbri's test case and make a whole new PR? What's the correct procedure here?

I think this will be the right way.

**Comment by dcitron** [comment]
Great! I'll do that and I'll see about the test262 suite as well.

**Comment by dcitron** [comment]
> Note that this fix might also fix some test262 tests that are currently not passing. You could check that by running the test262 TestSuite and see if any such tests are reported.

Hi, @p-bakker -- I tried to do that, but it didn't report anything. Did I miss a step or does this mean that my fix didn't fix any of the test262 tests?

```
$ ./gradlew test --tests org.mozilla.javascript.tests.Test262SuiteTest --rerun-tasks -DupdateTest262properties

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 4m 36s
5 actionable tasks: 5 executed

$ git status testsrc/test262.properties 
nothing to commit, working tree clean
```

**Comment by dcitron** [comment]
Do I need to do anything else or is it sufficient that the PR is currently open?

**Comment by rbri** [comment]
Sorry but we are all overloaded with work - will have a look at the weekend

**Comment by dcitron** [comment]
> Sorry but we are all overloaded with work - will have a look at the weekend

No rush at all! It took me forever and a day to even fix it! I just wanted to make sure I wasn't still blocking anything :)

**Comment by rbri** [comment]
@gbrail, @p-bakker, @tuchida what do you think? Can i merge this?

**Comment by rbri** [comment]
Juste made another PR for this (https://github.com/mozilla/rhino/pull/1294) will try both suggested solutions using the HtmlUnit test suite and report the results here.

**Comment by rbri** [comment]
Have done some tests with the new PR (#1294) in HtmlUnit

Works fine - the related problem is fixed with this and the performance is unchanged.
From my point of view we should go with this one.

@gbrail @p-bakker @tuchida @dcitron what do you think?

**Comment by rbri** [comment]
PR #1294 fixes this (hopefully) finally
