### ISSUE TITLE
An issue about the Math.max().

### ISSUE THREAD

**Issue by NWU-NISL** [mozilla/rhino#781]
**Revision**

rhino-1.7.13

**Test case**

```javascript
var NISLFuzzingFunc = function(){
    var a = {
        valueOf: function(){
            print(1);
        }
    };
    var b = Math.max(NaN,a);
};
NISLFuzzingFunc();
```

**Execution steps**

```javascript
java -jar rhino/rhino-1.7.13.jar -debug -version 200 testcase.js
```

**Output**

```javascript
No output.
```

**Expected behavior**

```javascript
Output 1.
```

**Description**

When I passed NaN and an object with the "valueOf" attribute value as a callable function to the first and second parameters of Math.max, chakra did not execute this function. According to the ES standard, the ToNumber operation is performed on each parameter of Math.max, and the "valueOf" attribute value function of the second parameter will be executed.

Contributor : @Haobin-Lee

**Comment by morfav** [comment]
I would like to pick this up if OK.
