### ISSUE TITLE
Infinite loop in getTopLevelScope

### ISSUE THREAD

**Issue by oswetto** [mozilla/rhino#786]
Hi @gbrail,
 I think I found an infinite loop in the getTopLevelScope method in [ScriptableObject ](https://github.com/mozilla/rhino/blob/f53a60b144e82b7823ae4e1613c98b8e8d09b6ae/src/org/mozilla/javascript/ScriptableObject.java)class.
In this method, the parent is never null, I found it while parsing this script [http://pagead2.googlesyndication.com/pagead/show_ads.js](http://pagead2.googlesyndication.com/pagead/show_ads.js) 
This bug is only present with this script

public static Scriptable getTopLevelScope(Scriptable obj)
    {
        System.out.println("getTopLevelScope ");
        for (;;) {
            Scriptable parent = obj.getParentScope();
            System.out.println("parent getTopLevelScope" + parent.);
            if (parent == null) {
                System.out.println("obj getTopLevelScope" + obj);
                return obj;
            }
            obj = parent;
        }
    }

**Comment by gbrail** [comment]
Do you have any more information that we could use to reproduce this? That particular script parses but doesn't run because it needs some additional information (like a doc tree at "document") to run.
