### ISSUE TITLE
A Question about Scriptable

### ISSUE THREAD

**Issue by dprutean** [mozilla/rhino#789]
I want to migrate a project from Nahorn to Rhino. I have to add via Java some member variables to a given object. Is this possible and how? In Nashorn I have used AbstractJSObject by implementing the hasMember() and getMember() methods.

**Comment by gbrail** [comment]
You have a few options. There is a good but very old tutorial on MDN that still makes sense:

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Embedding_tutorial

There are likely others on the mailing list or with example code on GitHub that can show the various options.

**Comment by p-bakker** [comment]
@dprutean closing this case as a pointer to the docs was provided and no further questions were asked.

If you have further questions, feel free to reopen
