### ISSUE TITLE
eval butchers returns

### ISSUE THREAD

**Issue by DeltaNedas** [mozilla/rhino#790]
`eval('()=>{const a = ["no"]; return "egg" + a[0]}')()`
this should return `"eggno"`, but instead returns `a[0] + "egg"[0]`, `"noe"`

**Comment by DeltaNedas** [comment]
did mozilla actually fire everyone

**Comment by gbrail** [comment]
$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar -version 200
Rhino 1.7.14-SNAPSHOT 2020 12 01
js> eval('()=>{const a = ["no"]; return "egg" + a[0]}')()
eggno

Works for me. If you have a reproducer for a particular version then perhaps someone else might want to look.
