### ISSUE TITLE
Negative 0 output incorrectly

### ISSUE THREAD

**Issue by morfav** [mozilla/rhino#791]
While investigating one of the beginner tasks, I noticed that 

`print(-0)` outputs 0, instead of the expected -0. This also means that the result of `Math.min(-0, 0)` is printed incorrectly.

Please let me know if this is an issue.

**Comment by gbrail** [comment]
I haven't had a chance to dig in to it, but you might be able to look at
some of the tests in the test262 submodule and see if we have good coverage
for negative zero in general -- it may well be that the problem is with the
"print" function or something that it depends on.

**Comment by morfav** [comment]
Yes, it IS the print function, sorry I wasn't explicit enough. The value being returned is correct until it gets to the output stage.

**Comment by morfav** [comment]
I did a quick investigation.
Mozilla MDN output is:
console.log(-0.0) // -0
console.log(-0) // -0
console.log(Number(-0)) // -0
console.log(String(-0.0)) // "0"
console.log(Number(-0).toString()) // "0"

Invoking print on any of those using Rhino always outputs 0.

So this isn't an issue if print is meant to implicitly convert to string.

Please let me know if I should close the issue.
