### ISSUE TITLE
Backward compatibility java.util.{List,Map} interop

### ISSUE THREAD

**Issue by tuchida** [mozilla/rhino#820]
ref. #713
```js
var h = new java.util.HashMap();
h.put('a', 123);
h.a;  // 123.0
h.put('put', 123);
h.put; // 123.0
h.put('put', 123);
// js: "<stdin>", line 7: uncaught JavaScript runtime exception: TypeError: Cannot call property put in object {a=123.0, put=123.0}. It is not a function, it is "object".
//	at <stdin>:7
```
- Is it possible to have problems with code written in the past?
- Is there a how to make sure to call `java.util.HashMap#put`?

**Comment by tuchida** [comment]
Treating JS Object like HashMap has various problems (e.g. `__proto__`). I think you should consider compatibility with ES6 Map.

**Comment by tuchida** [comment]
> Is there a how to make sure to call java.util.HashMap#put?
```js
var h = new java.util.HashMap();
new java.util.HashMap().put.call(h, 'a', 123);
h; // {a=123.0}
```

**Comment by tuchida** [comment]
```js
var a = new java.util.HashMap();
a.put('1', 123);
a['1']; // js: Java class "java.util.HashMap" has no public instance field or method named "1".
```

**Comment by tuchida** [comment]
@gbrail This issue can be critical. What do you think?

**Comment by gbrail** [comment]
This seemed like a nice convenience function, but you're right that it results in JavaScript objects that behave in strange ways, and it indeed means that things work a bit differently than they did before. Unfortunately we did a release since then, although I don't know how many people are using it. Perhaps we should add a feature flag on the Context object so that this functionality is not enabled by default.

I can see the attraction of making it possible for the JavaScript Map and Set to be made interoperable with existing Java Map and Set classes, but unfortunately the iteration semantics are very different and the result would be Map and Set objects that don't work like JavaScript Maps and Sets anyway.

**Comment by tuchida** [comment]
For example, browser's localStorage looks like this:
```js
localStorage.setItem('a', 1);
localStorage.a; // 1
localStorage.setItem('setItem', 1);
localStorage.setItem; // function
localStorage.setItem('1', 1);
localStorage['1']; // 1
localStorage[1]; // 1
```
Perhaps emulating this would be a little better.

**Comment by syjer** [comment]
Hi, as a I proposed this PR, the goal was a better compatibility with nashorn, which allow this kind of java map <-> js object behaviour. My guess would be to check how they handled this cases.

**Comment by gbrail** [comment]
They do appear to work differently:

jjs> var m = new java.util.HashMap();
jjs> m.foo = 123;
123
jjs> m['foo'];
123
jjs> m.get('foo');
123
jjs> m.put('get', 2);
null
jjs> m.get;
2
jjs> m.get('get');
2

js> var m = new java.util.HashMap();
js> m.foo = 123;
123
js> m['foo'];
123.0
js> m.get('foo');
123.0
js> m.put('get', 2);
null
js> m.get;
2.0
js> m.get('get');
js: uncaught JavaScript runtime exception: TypeError: Cannot call property
get in object {foo=123.0, get=2.0}. It is not a function, it is "object".

Nashorn seems to either have some special handling of function properties
versus non-function properties, or something.

At this point I'd prefer if we opened an issue to track what the
differences are and thought about what to change,

**Comment by tuchida** [comment]
Nashorn:
```js
// $ jjs -v
// nashorn 1.8.0_275
var h = new java.util.HashMap();
h.put('put', 1);
h.put('put', 2);   // OK
(h.put)('a', 2);  // OK
var put = h.put;
put('a', 2); // <shell>:1 TypeError: put is not a function
(0, h.put)('a', 2);  // <shell>:1 TypeError: 0 ,> h.put is not a function
```
Rhino:
```js
(function() {
  eval("var x = 1;");
  (0, eval)("var x = 2;");
  print(x); // 1
}());
print(x); // 2
```
https://github.com/tc39/test262/blob/041da54c02ae7d17edb8c134ab7691c4f643bafe/test/language/eval-code/indirect/var-env-var-non-strict.js
Is it feasible with `Icode_CALLSPECIAL`?

**Comment by tuchida** [comment]
```js
var h = new java.util.HashMap();
h.put(new String('abc'), 1);
h.put(new String('abc'), 2);
JSON.stringify(Object.keys(h)); // ["abc","abc"]
```

**Comment by tuchida** [comment]
ref. #839

**Comment by tuchida** [comment]
ref.  #836
It is now disabled.
Probably the problem occurs only with `NativeJavaMap`, and `NativeJavaList` is not a problem since it only accesses numbers.
