### ISSUE TITLE
Getting error on release due to Proguard

### ISSUE THREAD

**Issue by AnjuJohnson** [mozilla/rhino#823]
I have implemented Rhino library successfully and it is working fine in debug apk.But for release apk it is show errors like 

org.mozilla.javascript.ContextFactory.makeContext (ContextFactory.java)
org.mozilla.javascript.Context.enter (Context.java:4)
com.remitbee.app.app.utils.Encryption.AESUtil.set_values (AESUtil.java:4)
com.remitbee.app.app.utils.Encryption.AESUtil.encrypt (AESUtil.java:4)

and
org.mozilla.javascript.VMBridge.makeInstance (VMBridge.java:3)
org.mozilla.javascript.ContextFactory.makeContext (ContextFactory.java)
org.mozilla.javascript.Context.enter (Context.java:4)
com.remitbee.app.app.utils.Encryption.AESUtil.set_values (AESUtil.java:4)
com.remitbee.app.app.utils.Encryption.AESUtil.encrypt (AESUtil.java:4)

Iam using Proguard and I have use proguard rules:
-keep class org.mozilla.** { *; }
-dontwarn org.mozilla.javascript.**
-dontwarn org.mozilla.classfile.**

But still shows error in release apk.Anyone please help me?

**Comment by fanok1** [comment]
the same problem

**Comment by AnjuJohnson** [comment]
@fanok1  I could fix it using this proguard rule

-keep class org.mozilla.javascript.** { *; }
-dontwarn org.mozilla.javascript.**
-dontwarn org.mozilla.classfile.**
