### ISSUE TITLE
Addition with string literal does not conform to ECMAScript spec

### ISSUE THREAD

**Issue by pastelmind** [mozilla/rhino#832]
* Rhino version: 1.7.13

If an object has both a `toString()` and a `valueOf()` method, which return different values, then adding (`+`) with a string literal causes an unexpected behavior:

```js
// Not standards-compliant:
({ toString: () => "foo", valueOf: () => 123 }) + "bar";
// Rhino:                   "foobar"
// SpiderMonkey (Firefox):  "123bar"
// V8 (Node.js, Chrome):    "123bar"
```

Using anything other than a string literal appears to trigger the "correct" behavior. For example, the following works:

```js
// Okay:
({ toString: () => "foo", valueOf: () => 123 }) + 1000;
// Rhino:                   1123
// SpiderMonkey (Firefox):  1123
// V8 (Node.js, Chrome):    1123

// Okay:
let stuff = "bar";
({ toString: () => "foo", valueOf: () => 123 }) + stuff;
// Rhino:                   "123bar"
// SpiderMonkey (Firefox):  "123bar"
// V8 (Node.js, Chrome):    "123bar"

// Okay:
({ toString: () => "foo", valueOf: () => 123 }) + String("bar");
// Rhino:                   "123bar"
// SpiderMonkey (Firefox):  "123bar"
// V8 (Node.js, Chrome):    "123bar"
```

## What spec is this violating?
According to the ECMA spec (I checked [ES5.1](https://262.ecma-international.org/5.1/#sec-11.6.1) and [ES6](https://262.ecma-international.org/6.0/#sec-addition-operator-plus)), the behavior in this case can be roughly summarized to:

1. Call `ToPrimitive(left)` with no hint &rarr; `lprim`
2. Call `ToPrimitive(right)` with no hint &rarr; `rprim`
3. If either `lprim` or `rprim` is string, use string concatenation
4. Otherwise, use numeric addition

The `ToPrimitive()` operation tries both `valueOf()` and `toString()` to determine the primitive value of an object:

* If the type hint is String:
   1. If `toString()` returns a primitive value, use it
   2. If `valueOf()` returns a primitive value, use it
* If the type hint is Number (with no hint, this is the default):
   1. If `valueOf()` returns a primitive value, use it
   2. If `toString()` returns a primitive value, use it

## Why is this happening?
I don't know.

Hypothesis: If either operand is a string literal...

* Rhino supplies a "String" hint to the other object, or...
* Rhino calls `toString()` directly and skips the normal `ToPrimitive()` operation

**Comment by tuchida** [comment]
```sh
$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar -opt -1
Rhino 1.7.14-SNAPSHOT 2021 02 01
js> ({ toString: () => "foo", valueOf: () => 123 }) + "bar";
123bar

$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar -opt 0
Rhino 1.7.14-SNAPSHOT 2021 02 01
js> ({ toString: () => "foo", valueOf: () => 123 }) + "bar";
foobar

$ java -jar buildGradle/libs/rhino-1.7.14-SNAPSHOT.jar -opt 9
Rhino 1.7.14-SNAPSHOT 2021 02 01
js> ({ toString: () => "foo", valueOf: () => 123 }) + "bar";
foobar
```

**Comment by tuchida** [comment]
https://github.com/mozilla/rhino/blob/70b9f49b70ff287877e810f16d8b282e61875fe4/src/org/mozilla/javascript/optimizer/BodyCodegen.java#L1229-L1233

**Comment by gbrail** [comment]
Thanks for fixing @tuchida !
