### ISSUE TITLE
Iterable Java Object

### ISSUE THREAD

**Issue by tuchida** [mozilla/rhino#839]
I implemented `Symbol.iterator` of `NativeJavaMap` and `NativeJavaList`.
https://github.com/mozilla/rhino/compare/master...tuchida:iterable-javamap-and-javalist

This allows us to write the following.
```js
var list = new java.util.ArrayList();
list.add(123);
for (var e of list) {
  print(e); // 123
}

var map = new java.util.HashMap();
map.put('abc', 123);
for (var [k, v] of map) {
  print([k, v]); // abc,123
}
```
However, this does not make `java.util.Set`, etc. iterable.

So I decided that `Symbol.iterator` exists in all `java.lang.Iterable`.
https://github.com/mozilla/rhino/compare/master...tuchida:iterable-javaobject
`java.util.Set`, etc., will also be iterable, but the writing style is different between JavaScript `Map`.
```js
for (var {key, value} of javaMap.entrySet()) ;
for (var [key, value] of jsMap) ;
```

Which do you think is better?

**Comment by tuchida** [comment]
Perhaps it would be useful to be able to convert from `java.util.Map` to JavaScript `Map`.
```js
var javaMap = new java.util.HashMap();
var jsMap = new Map(javaMap);
```
`Map` takes an iterable, so if entry is returned as an array, it can be converted.
https://262.ecma-international.org/11.0/#sec-map-iterable
There is also a way to accept `java.util.Map`, regardless of the iterable specification.

**Comment by tuchida** [comment]
Do you know how Nashorn is doing? Or do you know where I can find the latest Nashorn?

**Comment by tonygermano** [comment]
Not sure if this is helpful or not, but Rhino does already have a way to handle java.lang.Iterable that even works on older versions.

```javascript
Rhino 1.7.6 2015 04 15
js> var javaMap = new java.util.HashMap({a:'b',c:'d'})
js> for (var e in Iterator(javaMap.entrySet())) print([e.key,e.value])
a,b
c,d
```
The older version did not like the destructuring assignment.

**Comment by tuchida** [comment]
https://github.com/mozilla/rhino/blob/70b9f49b70ff287877e810f16d8b282e61875fe4/src/org/mozilla/javascript/NativeIterator.java#L164-L167

**Comment by tuchida** [comment]
It would be useful to be able to do this as well.
```js
var jsObj = Object.fromEntries(javaMap)
```

**Comment by tonygermano** [comment]
> Is there a use case where you want to iterate `java.util.Iterator` instead of `java.lang.Iterable`?

`java.lang.Iterable` has only been around since 1.5, so I suppose there are some older classes that return an `Iterator`, but do not implement `Iterable`.

**Comment by JojOatXGME** [comment]
I just randomly came across this issue without having any take on this topic. I just want to mention that `java.util.stream.Stream` does also not implement `java.util.Iterator`. Also see https://stackoverflow.com/q/20129762/4967497.

**Comment by tuchida** [comment]
> Do you know how Nashorn is doing? Or do you know where I can find the latest Nashorn?

https://github.com/openjdk/nashorn/blob/eeb49deee91fb86cecc4d05c3925dae80fa9ead3/src/org.openjdk.nashorn/share/classes/org/openjdk/nashorn/internal/runtime/ScriptRuntime.java#L408-L429

**Comment by tuchida** [comment]
ref. #846
I made it like this.
Thank you for all your help.
