### ISSUE TITLE
 Make findPrototypeId faster

### ISSUE THREAD

**Issue by tuchida** [mozilla/rhino#847]
ref. https://github.com/mozilla/rhino/pull/837#discussion_r579541215

It seems to be faster to use Java7's strings switch for `findPrototypeId`.
https://github.com/mozilla/rhino/compare/master...tuchida:improve-findPrototypeId
https://gist.github.com/tuchida/a8141c9946b0b597cdb2b171a3b8be5f

I think it is better to change to strings switch as it is more maintainable than generating code with org.mozilla.javascript.tools.idswitch.Main.
If there seems to be no problem, I will create a Pull Request.

**Comment by rbri** [comment]
Have done a short test by hacking SwitchGenerator to generate your switch. After regenerating nearly all classes i found no real difference when running Test262SuiteTest.

Will do some more testing... but if this seems to have no negative effect maybe we can use this to have a more cleaner code.

**Comment by tuchida** [comment]
Thank you for fixed and merged.
