### ISSUE TITLE
how to simulate js property access as java get method

### ISSUE THREAD

**Issue by liming-coder** [mozilla/rhino#849]
hi,

we have many java apis like this:
Application.getWorkbooks().getActiveDocument().getRange().getText().
how can we write js code as the following without changing java side code:
Application.Workbooks.ActiveDocument.Range.Text

Thanks

**Comment by tonygermano** [comment]
You can write it exactly the same way as the java code. This will work in javascript, too.
```javascript
Application.getWorkbooks().getActiveDocument().getRange().getText()
```
You can also write it like 
```javascript
Application.workbooks.activeDocument.range.text
```
See the section where it talks about JavaBeans in https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Scripting_Java

**Comment by liming-coder** [comment]
checked and java bean works.

thanks.

**Comment by rbri** [comment]
@gbrail i think we can close this

**Comment by gbrail** [comment]
Glad you got help!
