### ISSUE TITLE
OSGi Manifest

### ISSUE THREAD

**Issue by KnisterPeter** [mozilla/rhino#86]
Please add OSGi manifest headers to the rhino release.

**Comment by dereklindner** [comment]
+1

**Comment by ogattaz** [comment]
+1

**Comment by jboesl** [comment]
+1

**Comment by p-bakker** [comment]
Are there still relevant headers missing from Rhino jars? Couldn't find much info on which headers are mandatory, except [here](https://www.ibm.com/docs/en/was-zos/9.0.5?topic=files-example-osgi-bundle-manifest-file) is seems to suggest that `Build-Name` is a mandatory one (that we don't include yet)

The full jar has:
```java-properties
Implementation-Title: Mozilla Rhino
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-SymbolicName: org.mozilla.rhino
Bundle-Version: 1.7.13
Export-Package: org.mozilla.javascript,org.mozilla.javascript.ast,org.mozilla.javascript.annotations
Implementation-Version: 1.7.13
Built-Date: 2020-09-02
Implementation-URL: http://www.mozilla.org/rhino
Main-Class: org.mozilla.javascript.tools.shell.Main
Implementation-Vendor: Mozilla Foundation
Built-Time: 10:27:05
```
The runtime jar has:
```java-properties
Implementation-Title: Mozilla Rhino
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-SymbolicName: org.mozilla.rhino-runtime
Bundle-Version: 1.7.13
Export-Package: org.mozilla.javascript,org.mozilla.javascript.ast,org.mozilla.javascript.annotations
Implementation-Version: 1.7.13
Built-Date: 2020-09-02
Implementation-URL: http://www.mozilla.org/rhino
Implementation-Vendor: Mozilla Foundation
Built-Time: 10:27:05
```

**Comment by KnisterPeter** [comment]
@p-bakker I do not use these anymore, so I cannot say for sure.

**Comment by p-bakker** [comment]
Tnx for your response.

Had a further look and determined that the 'Bundle-SymbolivName' is the only mandatory header.

Since we include this header already, I'm closing this issue. If anything might still be missing, feel free to reopen
