### ISSUE TITLE
Missing conversion from javadate to nativedate

### ISSUE THREAD

**Issue by vdkuil** [mozilla/rhino#89]
Because of this missing conversion, comparison between java dates and javascript dates is not possible.

I do have a patch for this, however.. I cannot see where to put the diff so others can review this.

**Comment by p-bakker** [comment]
These sorts of things can be dealt with using a custom WrapFactory, which allows you to overwrite the default conversion from Java land > JavaScript land.

See https://github.com/mozilla/rhino/blob/399b9f05a8effd48f105afc25e7f4a5dd8ffebf7/examples/PrimitiveWrapFactory.java for an example of a custom wrap factory

And this is a code snippet if what you could do to convert Java Date instances to JavaScript Date instances:
```
		if (obj instanceof Date)
		{
			return cx.newObject(scope, "Date", new Object[] { Double.valueOf(NativeDate.convertToUTCMillisFromJava(((Date)obj).getTime())) });
		}
```
