### ISSUE TITLE
In the JS code, how to call the parent class function of the Java object? Or how to cast to the parent class?

### ISSUE THREAD

**Issue by Humenger** [mozilla/rhino#900]
![image](https://user-images.githubusercontent.com/27600008/118957931-85bcb500-b993-11eb-8397-6ddb2916fc51.png)
![image](https://user-images.githubusercontent.com/27600008/118958041-a08f2980-b993-11eb-804a-c0d5b99160ac.png)

**Comment by tonygermano** [comment]
You would have to actually subclass the java class using a JavaAdapter if you want to call super methods in javascript. In the `onCreate` function in your JavaAdapter you can call the super method like `this.super$onCreate(bundle)`

**Comment by p-bakker** [comment]
Assuming @tonygermano answered the question, I'm closing this case.

Feel free to reopen if you have further questions
