### ISSUE TITLE
Support ES2015 Computed Property Names

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#913]
Case just to track this specific ES6 feature (and how hard can it be to implement :-) ) and also because some tests in Test262 are disabled because they use this feature (and thus we cannot run them)

```
var name = 'myPropertyName';

Object.keys({
   [x] = 'someValue';
})[0] === name; // to yield true
```

**Comment by rPraml** [comment]
I've tried it here https://github.com/FOCONIS/rhino/commit/98ef8154bc056589daecbcc98c47d0b45f2b1f4a but I was lost in the ByteCode-generation for different optimization levels. Some tests will run, but some trigger a Kit.codeBug

**Comment by tuchida** [comment]
I tried to implement this in the past, but I think it was difficult to evaluate them in the proper order.
https://github.com/tuchida/rhino/commit/0fef518cbecfb9fd5fdd9703216b0dec184975f9

```js
var obj = {
  [exp1]: exp2,
  "str1": exp3,
  [exp4]: exp5
};
```

**Comment by p-bakker** [comment]
Great to see there are already 2 attempts underway, guess I shouldn't start a third :-)

Any thoughts on which one seems to be more feasible? Both seem to take quite a different approach. Just by quickly browsing through the changes (for just the interpreted impl.) in either branch, it seems @rPraml 's approach has a lot smaller footprint (but no idea though if it covers all angles)

FYI: think in both branches, this feature exclusion in Test262SuiteTest should also be removed: https://github.com/mozilla/rhino/blob/master/testsrc/org/mozilla/javascript/tests/Test262SuiteTest.java#L78

**Comment by tuchida** [comment]
I don't have any plans to move forward with the implementation right now, as it is a long time ago on my branch.
