### ISSUE TITLE
Support ES2015 unicode escape sequence additions 

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#917]
ES6 added the `\u{...}` escape sequence format to allow escaping unicode values > FFFF

See https://exploringjs.com/es6/ch_unicode.html for example

**Comment by tuchida** [comment]
I am implementing this and have noticed a few things.

- In Rhino, Unicode escaped identifier does not throw an error when it is the same as a reserved keyword, but this is a violation of the specification.
  https://github.com/mozilla/rhino/blob/c275c35f160ef7b035002c67c3540ba317964351/testsrc/org/mozilla/javascript/tests/ParserTest.java#L1122-L1126
  - Here is the cause.
  https://github.com/mozilla/rhino/blob/c275c35f160ef7b035002c67c3540ba317964351/src/org/mozilla/javascript/TokenStream.java#L755-L761
- In Rhino, an incomplete Unicode escape does not throw an error, but it is a violation of the specification.
  https://github.com/mozilla/rhino/blob/c275c35f160ef7b035002c67c3540ba317964351/testsrc/tests/ecma/LexicalConventions/7.7.4.js#L172
  - Here is the cause.
  https://github.com/mozilla/rhino/blob/c275c35f160ef7b035002c67c3540ba317964351/src/org/mozilla/javascript/TokenStream.java#L985

I can be modified as per specifications, but it would be breaking changes. It might be better to control it with some flag. These may be different issues.

**Comment by p-bakker** [comment]
I've implemented this as well as part of trying to implement the 'u'/Unicode option for regexes and ran into the same problems, see 
https://github.com/mozilla/rhino/issues/958#issuecomment-1057366529

Also see that above comment for my thoughts on fixing this: enable the spec compliant behavior in a new ECMASCRIPT language version

**Comment by p-bakker** [comment]
Also, the commit that implemented that specific behavior for keyword is [['+([0-9])?(.{+([0-9]),x}).x', 'master', 'next']](https://github.com/mozilla/rhino/commit/323f151a23216832ac01ff7e790b62cffc2ac0ac)

The commit references an issue 490, but I cannot find any reference to that, so no idea why exactly this was implemented this way

**Comment by p-bakker** [comment]
Think I found what the '490' referred to: issue report against Closure Compiler on the archived Google Code project, see http://blickly.github.io/closure-compiler-issues/#490

**Comment by tuchida** [comment]
- #1383

This has been supported.
