### ISSUE TITLE
Referencing an Object key that is a number/integer

### ISSUE THREAD

**Issue by aw20** [mozilla/rhino#92]
We are passing in a NativeObject to a function that has an inner object that has a number for a key.

document = {
  "12345": {
    "a":1
  },
  "abc": {
    "a":1
  }
};

function r( document ){
  var x = document["12345"];
  var y = document["abc"];
}

x will be undefined, y will be the correct value.

Using the latest official release from the RHINO site.

**Comment by p-bakker** [comment]
Closing this as as stated it cannot be reproduced. Is this is still an issue, please reopen and provide a reproducible sample
