### ISSUE TITLE
org.mozilla.javascript.EcmaError: ReferenceError: "parseSql" is not defined. (mysource#1)

### ISSUE THREAD

**Issue by nxf75** [mozilla/rhino#921]
The rhino cannot identify the JS file after the webpack package is loaded and ther version of rhino is 1.7.13, jdk is 1.8, webpack is 4.15.1
What's the reason?

**Comment by p-bakker** [comment]
Based on the current description its hard to tell what might be going on. Feel free to reopen this case if you have some code to demonstrate the issue
