### ISSUE TITLE
Put old ES3 reserved words behind a flag

### ISSUE THREAD

**Issue by pwnall** [mozilla/rhino#93]
Rhino currently chokes on this code that contains an ES3 reserved word.

``` javascript
options.long
```

Java keywords that aren't used in JavaScript are not reserved anymore, as of ES5:
http://ecma-international.org/ecma-262/5.1/#sec-7.6.1
https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Reserved_Words

For this reason, I think that the JS tokenizer should only choke on ES3 reserved words when a flag is set. (or, even better, not at all)

The relevant code seems to be here:
https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/TokenStream.java#L135

Once that is fixed, the map below should probably be re-generated.
https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/TokenStream.java#L153

**Comment by p-bakker** [comment]
Closing as this works now in Rhino, at least with Context.VERSION_ES6 as language level:
```
var obj = {};
obj.volatile = 123;
obj.long = 456
```
