### ISSUE TITLE
Support ES2021 number separators

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#935]
For example: 1_050.95 instead of 1050.95

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#numeric_literals

**Comment by p-bakker** [comment]
Really? Then I've must have done something wrong while checking it. Will retest tomorrow and close this issue if it indeed works as expected

**Comment by rbri** [comment]
see https://github.com/mozilla/rhino/commit/7eb2346ac1604efde0ccf9fb70bffeb024b1e4d8

**Comment by p-bakker** [comment]
Tested again, indeed already works. No idea what I did wrong the first time around :-)

Anyway, great, I'll close this one again
