### ISSUE TITLE
Git project

### ISSUE THREAD

**Issue by asashour** [mozilla/rhino#94]
Hi all,

I noticed few points in the current Git project:

- There are some confusing tags, like "head" and "done", I believe they should be removed or renamed to something more meaningful
- "build" and "lib" folders should be added to .gitignore
- .csvignore still exists in three places: root, in "toolsrc/org/mozilla/javascript/tools/debugger" and its "downloaded" subfolder.

Thanks,
Ahmed

**Comment by d10** [comment]
This issue can be closed.
