### ISSUE TITLE
Should the default for enabling (the deprecated) E4X be changed to false?

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#955]
E4X is a deprecated standard, but in Rhino it's enabled by default if running on the `default` JavaScript version or a JavaScript version >= 1.6.

**Comment by tonygermano** [comment]
This isn't a "yes" or "no" but some additional information to consider.

I came to know Rhino through https://github.com/nextgenhealthcare/connect (formerly Mirth Connect,) which is a pretty big open source player in the global healthcare market. The server is written in Java, but user created scripts are in Javascript and rely heavily on e4x as most data is processed as XML. Some of my recent PRs have actually been to improve e4x support.

I've looked a bit, and there don't seem to be any great alternatives for processing xml (creating, reading, and modifying with full namespace support) in Rhino that aren't significantly more cumbersome to use for people with little programming experience (as tends to be the case for many healthcare workers tasked with working on these interfaces.)

I haven't looked to see what is controlled by the feature flag, but I would guess it's likely the syntax extensions more so than the operations of the actual objects after they are created? I know at this point in time, I would hate for making this a non-default feature to lead to breaking changes or removal down the road without a good alternative to take its place.

**Comment by p-bakker** [comment]
@tonygermano as we now have the larger discussion at https://github.com/mozilla/rhino/discussions/972, on which you responded with a similar answer as the one above, I'm closing this case, so the 'discussion' continues in the discussion, instead of here
