### ISSUE TITLE
LICENSE.txt missing from rhino-engine-x.x.x and rhino-runtime-x.x.x jars

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#956]
Only seems included in the full rhino-x.x.x.jar

**Comment by carlosame** [comment]
Shouldn't the `NOTICE.txt` file be included in the main and the runtime jars?

**Comment by p-bakker** [comment]
It should imho.

And the full jar also needs the additional license for the threetable used in the debugger, see https://p-bakker.github.io/rhino/license.html

**Comment by carlosame** [comment]
> It should imho.

Fixed in new PR revision.

> And I think the full jar also needs the additional license for the treetable used in the debugger, see https://p-bakker.github.io/rhino/license.html

Looks like two different NOTICE files are needed. That's one of the things that could be dealt with more naturally if the project had a modular layout, with each module having the required NOTICE.txt. Meanwhile, one would need a NOTICE.txt and a NOTICE-tools.txt or anything similar.

**Comment by p-bakker** [comment]
@carlosame am I correct that the following hasn't happened yet?

> Looks like two different NOTICE files are needed. That's one of the things that could be dealt with more naturally if the project had a modular layout, with each module having the required NOTICE.txt. Meanwhile, one would need a NOTICE.txt and a NOTICE-tools.txt or anything similar.

**Comment by carlosame** [comment]
> @carlosame am I correct that the following hasn't happened yet in #1133 while the changes are available in #1124?

I'd suggest dealing directly with Greg about that.
