### ISSUE TITLE
Publish a snapshot build somewhere

### ISSUE THREAD

**Issue by p-bakker** [mozilla/rhino#980]
Think it would be handy if we'd publish a snapshot build somewhere everytime we succesfully push to master, so users of Rhino could try out what's being done on master, without having to go through the motions of checking out the source and building the snapshot jar themselves

**Comment by p-bakker** [comment]
Wondering if through GitHub Actions we could publish the snapshot jar as a [package](https://github.com/mozilla/rhino/packages) on our repo

**Comment by tonygermano** [comment]
I think this is a good idea, and should be possible. We're already compiling with GitHub Actions to run the tests, but right now the only artifacts we are retaining are the reports. We'd probably have to start naming with build versions (timestamps?) to differentiate them instead of naming them all SNAPSHOT.

**Comment by p-bakker** [comment]
My idea was to have every new snapshot overwrite the previous, so couldn't the naming be very straight forward on that case?

**Comment by tonygermano** [comment]
That would be simpler from an implementation standpoint, but harder to know which snapshot version a user was running when reporting bugs or giving feedback.

It looks like as recently as 1.7.11 there were official release candidates before the final release.

https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
Perhaps we could incorporate `GITHUB_RUN_ID` or `GITHUB_RUN_NUMBER` into the filename?

`rhino-1.7.14-snap.${GITHUB_RUN_ID}.jar`?

It's been suggested in https://github.com/mozilla/rhino/issues/966#issuecomment-870926110 and https://github.com/mozilla/rhino/discussions/972#discussioncomment-942137 to move to semantic versioning. I think if that happens what I suggested above will have to change anyway as (nearly?) every PR would trigger a version bump and new release.

I just found this, which looks like a decent write-up on the topic https://css-tricks.com/how-to-automate-project-versioning-and-releases-with-continuous-deployment/

**Comment by carlosame** [comment]
> Wondering if through GitHub Actions we could publish the snapshot jar as a package on our repo

Github packages require authentication to be used, see:

https://github.community/t/download-from-github-package-registry-without-authentication/14407

Github's Maven repository is currently useless.

**Comment by botic** [comment]
Would be great to have a referencable snapshot release for our Ringo 3.0.0 release candidates. I'm building from source atm and 1.7.14 feels very solid so far.

**Comment by gbrail** [comment]
I completed this task -- there are now tasks to publish to Maven Central and to the GitHub repository in the GitHub Actions for this project, and the corresponding secrets are also stored there.

**Comment by p-bakker** [comment]
@gbrail I'm not seeing a 1.7.15 snapshot builds appearing in maven or github packages, while I do see a 1.7.14-SNAPSHOT in github packages (created a while back): https://github.com/mozilla/rhino/packages/1179324?version=1.7.14-SNAPSHOT

Am I wrong to expect some newer snapshot builds somewhere?

**Comment by p-bakker** [comment]
Any word on this @gbrail? Are these snapshots  to be created on every commit, or?

I was looking at https://github.com/oprypin/nightly.link, but our GitHub Action just exposes the reports.zip, not the rhino jar that was built

**Comment by p-bakker** [comment]
@gbrail any update on this? You closed this case a while back, but I'm not seeing any snapshot builds anywhere. 

As mentioned above, it would be nice if one of the runs of the GitHub Action would store (at least) the rhino.jar, so it can be referenced by https://nightly.link/
