### ISSUE TITLE
bigint values convert to java.lang.Double when being passed to java

### ISSUE THREAD

**Issue by tonygermano** [mozilla/rhino#995]
```js
js> var big = BigInt('123')
js> var list = java.util.Collections.singletonList(big)
js> print(list.get(0).getClass())
class java.lang.Double
```
I expect they should be converted to java.math.BigInteger instead.

**Comment by tuchida** [comment]
It looks like a change is needed here.
https://github.com/mozilla/rhino/blob/3e205d7cbdba46f6aba58b8c3bfa89ee69f9b775/src/org/mozilla/javascript/NativeJavaObject.java#L758-L763
